apiVersion: v1
kind: Namespace
metadata:
  name: infisical-system
  labels:
    app.kubernetes.io/name: infisical-csi-provider
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
