apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rocko
  namespace: rocko
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: rocko
    creationPolicy: Owner
  data:
    - secretKey: SLACK_BOT_TOKEN
      remoteRef:
        key: /projects/rocko/SLACK_BOT_TOKEN
    - secretKey: SLACK_APP_TOKEN
      remoteRef:
        key: /projects/rocko/SLACK_APP_TOKEN
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: /projects/rocko/OPENAI_API_KEY
