apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - apps-namespace.yaml
  - external-secret.yaml
  - model-config.yaml
  - agent.yaml
  - software-developer-agent.yaml
  - software-developer-rbac.yaml
  - software-developer-pvc.yaml
  - software-developer-deployment.yaml
  - deployment.yaml
