apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: default-model-config
  namespace: rocko
spec:
  provider: OpenAI
  model: gpt-5.4
  apiKeySecret: rocko
  apiKeySecretKey: OPENAI_API_KEY
