apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nango
  namespace: rocko
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: nango
    creationPolicy: Owner
  data:
    - secretKey: NANGO_AUTH_HEADER
      remoteRef:
        key: /projects/rocko/NANGO_AUTH_HEADER
    - secretKey: NANGO_CONNECTION_ID
      remoteRef:
        key: /projects/rocko/NANGO_CONNECTION_ID
