apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: software-developer-workspace
  namespace: rocko
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: openebs-single-replica
  resources:
    requests:
      storage: 10Gi
