apiVersion: v1
kind: ServiceAccount
metadata:
  name: software-developer
  namespace: rocko
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: software-developer
  namespace: apps
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "configmaps"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: software-developer
  namespace: apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: software-developer
subjects:
  - kind: ServiceAccount
    name: software-developer
    namespace: rocko
