# Buildkite bootstrap pipeline for cuenv
# This generates a dynamic pipeline based on affected tasks
steps:
  - label: ":pipeline: Generate Pipeline"
    command: cuenv ci --dynamic buildkite | buildkite-agent pipeline upload
