apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teleport-github-oauth
  namespace: teleport
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: teleport-github-oauth
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          resources.teleport.dev/allow-lookup-from-cr: "*"
  data:
    - secretKey: client-secret
      remoteRef:
        key: /projects/rawkode-cloud/GITHUB_CLIENT_SECRET
