apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - tls-route.yaml
  - reference-grant.yaml
  - external-secret.yaml
  - role-kube-admin.yaml
  - role-kube-viewer.yaml
  - github-connector.yaml
  - viewer-clusterrolebinding.yaml
