apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV8
metadata:
  name: kube-viewer
  namespace: teleport
spec:
  allow:
    kubernetes_groups:
      - teleport-viewers
    kubernetes_labels:
      "*": "*"
    kubernetes_resources:
      - kind: "*"
        namespace: "*"
        name: "*"
        verbs:
          - get
          - list
          - watch
