apiVersion: openebs.io/v1beta3
kind: DiskPool
metadata:
  name: production-control-plane-01
  namespace: openebs
spec:
  node: production-control-plane-01
  disks:
    - aio:///dev/disk/by-path/pci-0000:07:00.0-nvme-1
