import { sva } from "../../styled-system/css";

/** Content-first technology profiles; all columns share the Academy shell gutter. */
export const academyTechnology = sva({
	slots: [
		"root",
		"hero",
		"breadcrumb",
		"identity",
		"logo",
		"title",
		"description",
		"metadata",
		"actions",
		"link",
		"columns",
		"reading",
		"prose",
		"aside",
		"section",
		"heading",
		"copy",
		"list",
		"video",
		"quote",
		"facts",
		"ruledSection",
		"videoGrid",
		"relatedGrid",
		"related",
		"relatedName",
		"newsletter",
	],
	base: {
		root: {
			width: "full",
			maxWidth: "academy-shell",
			marginInline: "auto",
			paddingInline: "academy-gutter",
			paddingBlock: "8",
			display: "flex",
			flexDirection: "column",
			gap: "10",
			minWidth: "0",
			fontFamily: "academy-text",
			color: "academy.text",
			overflowWrap: "anywhere",
			"& img[hidden]": {
				display: "none",
			},
			"& :where(a, summary):focus-visible": {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
			_lg: {
				paddingBlock: "12",
				gap: "12",
			},
		},
		hero: {
			display: "flex",
			flexDirection: "column",
			gap: "5",
			paddingBottom: "8",
			borderBottom: "hairline",
			borderColor: "academy.border",
			minWidth: "0",
		},
		breadcrumb: {
			display: "flex",
			flexWrap: "wrap",
			gap: "2",
			margin: "0",
			padding: "0",
			listStyle: "none",
			fontSize: "sm",
			color: "academy.textSoft",
			"& li": {
				display: "inline-flex",
				alignItems: "baseline",
				gap: "2",
				minWidth: "0",
			},
			"& a": {
				color: "inherit",
				paddingBlock: "2",
			},
			"& [aria-current]": {
				color: "academy.textMuted",
			},
		},
		identity: {
			display: "flex",
			alignItems: "center",
			gap: "4",
			minWidth: "0",
		},
		logo: {
			width: "12",
			height: "12",
			objectFit: "contain",
			flexShrink: "0",
			_lg: {
				width: "16",
				height: "16",
			},
		},
		title: {
			margin: "0",
			minWidth: "0",
			fontFamily: "academy-display",
			fontSize: "3xl",
			fontWeight: "bold",
			lineHeight: "tight",
			letterSpacing: "tight",
			color: "academy.text",
			_lg: {
				fontSize: "5xl",
			},
		},
		description: {
			margin: "0",
			maxWidth: "academy-copy",
			fontSize: "lg",
			lineHeight: "relaxed",
			color: "academy.textSoft",
			textWrap: "pretty",
		},
		metadata: {
			display: "flex",
			flexWrap: "wrap",
			gap: "4",
			columnGap: "8",
			margin: "0",
			fontSize: "sm",
			lineHeight: "relaxed",
			"& div": {
				minWidth: "0",
				maxWidth: "full",
			},
			"& dt": {
				color: "academy.textMuted",
			},
			"& dd": {
				margin: "0",
				color: "academy.text",
			},
		},
		actions: {
			display: "flex",
			flexWrap: "wrap",
			gap: "2",
			columnGap: "6",
			margin: "0",
			padding: "0",
			listStyle: "none",
			"& a": {
				display: "inline-flex",
				alignItems: "center",
				minHeight: "11",
			},
		},
		link: {
			color: "academy.accent",
			textDecoration: "underline",
			textUnderlineOffset: "3px",
			textDecorationThickness: "1px",
			lineHeight: "relaxed",
			_hover: {
				textDecorationThickness: "2px",
			},
		},
		columns: {
			display: "grid",
			gap: "10",
			alignItems: "start",
			minWidth: "0",
			_lg: {
				gridTemplateColumns: "minmax(0, 1fr) 18rem",
				gap: "12",
			},
		},
		reading: {
			minWidth: "0",
			maxWidth: "academy-copy",
			width: "full",
		},
		prose: {
			minWidth: "0",
			color: "academy.textSoft",
			fontFamily: "academy-text",
			fontSize: "md",
			lineHeight: "relaxed",
			scrollMarginTop: "24",
			"& > :first-child": {
				marginTop: "0",
			},
			"& > :last-child": {
				marginBottom: "0",
			},
			"& :where(p, ul, ol, blockquote, pre, table, figure)": {
				marginBlock: "5",
			},
			"& :where(h1, h2, h3, h4, h5, h6)": {
				fontFamily: "academy-display",
				color: "academy.text",
				fontWeight: "bold",
				lineHeight: "tight",
				marginTop: "10",
				marginBottom: "4",
				scrollMarginTop: "24",
			},
			"& :where(h1, h2)": {
				fontSize: "2xl",
			},
			"& h3": {
				fontSize: "xl",
			},
			"& :where(h4, h5, h6)": {
				fontSize: "lg",
			},
			"& a": {
				color: "academy.accent",
				textDecoration: "underline",
				textUnderlineOffset: "3px",
			},
			"& strong": {
				color: "academy.text",
				fontWeight: "bold",
			},
			"& ul": {
				listStyleType: "disc",
				paddingInlineStart: "6",
			},
			"& ol": {
				listStyleType: "decimal",
				paddingInlineStart: "6",
			},
			"& li": {
				marginBlock: "2",
			},
			"& blockquote": {
				borderInlineStart: "hairline",
				borderColor: "academy.accent",
				paddingInlineStart: "5",
				color: "academy.text",
			},
			"& :where(code, pre)": {
				fontFamily: "academy-mono",
				fontSize: "sm",
			},
			"& pre": {
				maxWidth: "full",
				overflowX: "auto",
				padding: "4",
				borderRadius: "academy-s",
			},
			"& table": {
				display: "block",
				maxWidth: "full",
				overflowX: "auto",
				borderCollapse: "collapse",
			},
			"& :where(th, td)": {
				padding: "3",
				borderBottom: "hairline",
				borderColor: "academy.border",
				textAlign: "start",
			},
			"& :where(img, video, iframe)": {
				maxWidth: "full",
			},
			"& img": {
				height: "auto",
			},
			"& hr": {
				marginBlock: "8",
				borderColor: "academy.border",
			},
		},
		aside: {
			display: "flex",
			flexDirection: "column",
			gap: "8",
			minWidth: "0",
			"& > section + section": {
				borderTop: "hairline",
				borderColor: "academy.border",
				paddingTop: "6",
			},
		},
		section: {
			display: "flex",
			flexDirection: "column",
			gap: "4",
			minWidth: "0",
		},
		heading: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "bold",
			lineHeight: "tight",
			color: "academy.text",
		},
		copy: {
			margin: "0",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "relaxed",
		},
		list: {
			display: "flex",
			flexDirection: "column",
			gap: "4",
			listStyle: "none",
			margin: "0",
			padding: "0",
			minWidth: "0",
		},
		video: {
			display: "flex",
			flexDirection: "column",
			gap: "3",
			minWidth: "0",
			textDecoration: "none",
			color: "academy.text",
			fontFamily: "academy-display",
			fontWeight: "semibold",
			fontSize: "md",
			lineHeight: "snug",
			"& img": {
				width: "full",
				height: "auto",
				aspectRatio: "academy-video",
				objectFit: "cover",
				borderRadius: "academy-s",
			},
			_hover: {
				color: "academy.accent",
				"& span": {
					textDecoration: "underline",
					textUnderlineOffset: "3px",
				},
			},
		},
		quote: {
			margin: "0",
			paddingInlineStart: "4",
			borderInlineStart: "hairline",
			borderColor: "academy.accent",
			color: "academy.text",
			fontSize: "sm",
			lineHeight: "relaxed",
		},
		facts: {
			margin: "0",
			display: "grid",
			gap: "3",
			fontSize: "sm",
			lineHeight: "relaxed",
			"& div": {
				display: "flex",
				flexWrap: "wrap",
				justifyContent: "space-between",
				gap: "2",
			},
			"& dt": {
				color: "academy.textMuted",
			},
			"& dd": {
				margin: "0",
				color: "academy.text",
			},
		},
		ruledSection: {
			display: "flex",
			flexDirection: "column",
			gap: "6",
			minWidth: "0",
			paddingTop: "8",
			borderTop: "hairline",
			borderColor: "academy.border",
			scrollMarginTop: "24",
		},
		videoGrid: {
			display: "grid",
			gridTemplateColumns: "minmax(0, 1fr)",
			gap: "6",
			listStyle: "none",
			padding: "0",
			margin: "0",
			sm: {
				gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
			},
			_lg: {
				gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
			},
		},
		relatedGrid: {
			display: "grid",
			gap: "6",
			listStyle: "none",
			padding: "0",
			margin: "0",
			sm: {
				gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
			},
			_lg: {
				gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
			},
		},
		related: {
			display: "flex",
			alignItems: "start",
			gap: "3",
			minWidth: "0",
			color: "academy.text",
			textDecoration: "none",
			"& img": {
				width: "10",
				height: "10",
				objectFit: "contain",
				flexShrink: "0",
			},
			"& > span": {
				minWidth: "0",
				display: "flex",
				flexDirection: "column",
				gap: "1",
			},
			_hover: {
				color: "academy.accent",
			},
		},
		relatedName: {
			fontFamily: "academy-display",
			fontSize: "lg",
			fontWeight: "bold",
			lineHeight: "snug",
		},
		newsletter: {
			width: "full",
			maxWidth: "academy-copy",
			marginInline: "auto",
			minWidth: "0",
		},
	},
});
