import { sva } from "../../styled-system/css";

export const academySearch = sva({
	slots: [
		"root",
		"header",
		"title",
		"lede",
		"form",
		"field",
		"input",
		"button",
		"filters",
		"filter",
		"groups",
		"groupHeader",
		"count",
		"list",
		"result",
		"resultTitle",
		"description",
		"date",
		"more",
		"pager",
		"empty",
	],
	base: {
		root: {
			width: "full",
			maxWidth: "academy-shell",
			marginInline: "auto",
			paddingInline: "academy-gutter",
			paddingBlock: "10",
			color: "academy.text",
			fontFamily: "academy-text",
		},
		header: {
			display: "grid",
			gap: "5",
			paddingBottom: "8",
			borderBottom: "hairline",
		},
		title: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "academy-title",
			lineHeight: "academy-title",
			letterSpacing: "academy-display",
			fontWeight: "bold",
			overflowWrap: "anywhere",
		},
		lede: {
			margin: "0",
			maxWidth: "academy-copy",
			fontSize: "lg",
			lineHeight: "body",
			color: "academy.textSoft",
		},
		form: {
			display: "grid",
			gap: "3",
			alignItems: "end",
			maxWidth: "academy-copy",
			_sm: { gridTemplateColumns: "minmax(0, 1fr) auto" },
		},
		field: {
			display: "grid",
			gap: "2",
			fontSize: "sm",
			fontWeight: "semibold",
		},
		input: {
			width: "full",
			minWidth: "0",
			minHeight: "12",
			paddingInline: "3",
			fontSize: "md",
			fontWeight: "normal",
			background: "academy.input",
			color: "academy.text",
			border: "hairline",
			borderColor: "academy.inputBorder",
			borderRadius: "academy-s",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		button: {
			minHeight: "12",
			paddingInline: "5",
			background: "academy.accent",
			color: "academy.accentForeground",
			fontWeight: "bold",
			border: "none",
			borderRadius: "academy-s",
			cursor: "pointer",
			_hover: { opacity: "0.9" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		filters: {
			display: "flex",
			flexWrap: "wrap",
			gap: "2",
			margin: "0",
			padding: "0",
			listStyle: "none",
		},
		filter: {
			display: "inline-flex",
			alignItems: "center",
			minHeight: "11",
			paddingInline: "3",
			fontSize: "sm",
			color: "academy.textSoft",
			textDecoration: "none",
			borderBottom: "hairline",
			borderColor: "transparent",
			_hover: { color: "academy.accent", borderColor: "academy.accent" },
			"&[aria-current=page]": {
				color: "academy.accent",
				borderColor: "academy.accent",
				fontWeight: "bold",
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		groups: { display: "grid", gap: "12", paddingTop: "8" },
		groupHeader: {
			display: "flex",
			justifyContent: "space-between",
			flexWrap: "wrap",
			alignItems: "baseline",
			gap: "3",
			paddingBottom: "4",
			borderBottom: "hairline",
			"& h2": {
				margin: "0",
				fontFamily: "academy-display",
				fontSize: "2xl",
				fontWeight: "bold",
			},
		},
		count: { fontSize: "sm", color: "academy.textMuted" },
		list: { margin: "0", padding: "0", listStyle: "none" },
		result: {
			display: "grid",
			gap: "2",
			paddingBlock: "5",
			borderBottom: "hairline",
			color: "academy.text",
			textDecoration: "none",
			_hover: { color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		resultTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "bold",
			lineHeight: "academy-card",
		},
		description: {
			margin: "0",
			maxWidth: "academy-copy",
			color: "academy.textSoft",
			fontSize: "md",
			lineHeight: "body",
		},
		date: {
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
		},
		more: {
			display: "inline-flex",
			alignItems: "center",
			minHeight: "11",
			marginTop: "3",
			color: "academy.accent",
			fontSize: "sm",
			fontWeight: "semibold",
			textUnderlineOffset: "0.2em",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		pager: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			justifyContent: "space-between",
			gap: "4",
			paddingTop: "6",
		},
		empty: {
			display: "grid",
			gap: "3",
			paddingBlock: "10",
			"& h2": {
				margin: "0",
				fontFamily: "academy-display",
				fontSize: "2xl",
				fontWeight: "bold",
			},
			"& p": { margin: "0", color: "academy.textSoft" },
			"& a": { color: "academy.accent", textDecoration: "underline" },
		},
	},
});
