import { sva } from "../../styled-system/css";

export const academyCourse = sva({
	slots: ["resources", "header", "heading", "category", "group", "resource", "icon", "iconBadge", "smallIcon", "copy", "title", "description", "meta", "arrow", "workbench", "toolbar", "actions", "status", "ready", "error", "spinner", "split", "pane", "filebar", "select", "editorFrame", "editor", "preview", "placeholder", "terminal", "terminalOutput", "terminalLine", "link", "button", "embed", "fill"],
	base: {
		resources: { display: "flex", flexDirection: "column", gap: "6" },
		header: { paddingBottom: "5", borderBottom: "hairline", borderColor: "academy.border" },
		heading: { display: "flex", alignItems: "center", gap: "3", fontFamily: "academy-display", fontSize: "2xl", fontWeight: "bold", color: "academy.text" },
		category: { display: "flex", alignItems: "center", gap: "2", marginBottom: "3", fontSize: "sm", fontFamily: "academy-mono", fontWeight: "semibold", color: "academy.accent", textTransform: "uppercase", letterSpacing: "wide" },
		group: { paddingBottom: "6", borderBottom: "hairline", borderColor: "academy.border", _last: { borderBottom: "none", paddingBottom: "0" } },
		resource: { display: "grid", gridTemplateColumns: "auto minmax(0, 1fr) auto", width: "full", gap: "3", paddingBlock: "4", textAlign: "left", borderBottom: "hairline", borderColor: "academy.border", color: "academy.text", textDecoration: "none", cursor: "pointer", _hover: { background: "academy.ground" }, _focusVisible: { outline: "focus", outlineColor: "academy.accent", outlineOffset: "focus" } },
		icon: { width: "5", height: "5", flexShrink: "0" },
		iconBadge: { display: "flex", alignItems: "center", justifyContent: "center", width: "10", height: "10", borderRadius: "full", background: "academy.ground", color: "academy.accent" },
		smallIcon: { width: "4", height: "4", flexShrink: "0" },
		copy: { minWidth: "0", overflowWrap: "anywhere" },
		title: { fontWeight: "semibold", color: "academy.text", fontSize: "lg" },
		description: { marginTop: "2", fontSize: "sm", color: "academy.textSoft", lineHeight: "relaxed" },
		meta: { marginTop: "3", fontFamily: "academy-mono", fontSize: "xs", color: "academy.textMuted" },
		arrow: { display: "flex", alignItems: "start", paddingTop: "1", color: "academy.accent" },
		workbench: { height: "full", minHeight: "0", display: "flex", flexDirection: "column", background: "academy.canvas", color: "academy.text", fontFamily: "academy-text" },
		toolbar: { display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: "3", padding: "4", background: "academy.panel", borderBottom: "hairline", borderColor: "academy.border" },
		actions: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: "3", minWidth: "0" },
		status: { display: "inline-flex", alignItems: "center", gap: "2", color: "academy.textMuted", fontSize: "sm" },
		ready: { color: "academy.statusSpruce", fontSize: "sm" },
		error: { color: "academy.statusRust", fontSize: "sm" },
		spinner: { width: "4", height: "4", border: "focus", borderColor: "academy.border", borderTopColor: "academy.accent", borderRadius: "full", animation: "academy-spinner", _motionReduce: { animation: "none" } },
		split: { flex: "1", minHeight: "0", display: "grid", gridTemplateColumns: "minmax(0, 1fr)", overflow: "auto", _lg: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" } },
		pane: { display: "flex", flexDirection: "column", minWidth: "0", minHeight: "64", border: "hairline", borderColor: "academy.border" },
		filebar: { padding: "2", background: "academy.panel", borderBottom: "hairline", borderColor: "academy.border" },
		select: { width: "full", minHeight: "11", paddingInline: "3", background: "academy.input", color: "academy.text", border: "hairline", borderColor: "academy.inputBorder", borderRadius: "academy-s", _focusVisible: { outline: "focus", outlineColor: "academy.accent", outlineOffset: "focus" } },
		editorFrame: { flex: "1", position: "relative", minHeight: "64" },
		editor: { position: "absolute", inset: "0", width: "full", height: "full", padding: "4", background: "academy.input", color: "academy.text", fontFamily: "academy-mono", fontSize: "sm", resize: "none", _focusVisible: { outline: "focus", outlineColor: "academy.accent", outlineOffset: "focus-inset" } },
		preview: { position: "absolute", inset: "0", width: "full", height: "full", border: "none" },
		placeholder: { display: "flex", alignItems: "center", justifyContent: "center", padding: "6", textAlign: "center", color: "academy.textMuted", height: "full" },
		terminal: { height: "48", flexShrink: "0", background: "academy.ground", borderTop: "hairline", borderColor: "academy.border", display: "flex", flexDirection: "column", overflow: "hidden" },
		terminalOutput: { flex: "1", minHeight: "0", overflowY: "auto", padding: "3", fontFamily: "academy-mono", fontSize: "xs", whiteSpace: "pre-wrap", overflowWrap: "anywhere" },
		terminalLine: { color: "academy.textSoft" },
		link: { color: "academy.accent", fontSize: "sm", textDecoration: "underline", overflowWrap: "anywhere", _focusVisible: { outline: "focus", outlineColor: "academy.accent", outlineOffset: "focus" } },
		button: { minHeight: "11", minWidth: "11", paddingInline: "3", color: "academy.textSoft", fontSize: "sm", borderRadius: "academy-s", cursor: "pointer", _hover: { background: "academy.ground", color: "academy.text" }, _disabled: { opacity: "0.5", cursor: "not-allowed" }, _focusVisible: { outline: "focus", outlineColor: "academy.accent", outlineOffset: "focus" } },
		embed: { position: "relative", background: "academy.ground", minHeight: "64", maxHeight: "academy-command" },
		fill: { width: "full", height: "full" },
	},
});
