import { sva } from "../../styled-system/css";

/** About-page composition; the shared layout owns the page width and gutters. */
export const academyAbout = sva({
	slots: [
		"hero",
		"introduction",
		"kicker",
		"title",
		"lede",
		"byline",
		"figure",
		"photo",
		"caption",
		"mission",
		"sectionHeading",
		"sectionTitle",
		"copy",
		"principles",
		"principle",
		"itemTitle",
		"story",
		"storyBody",
		"timeline",
		"milestone",
		"period",
		"milestoneBody",
		"origins",
		"archiveTitle",
		"archiveLinks",
		"archiveLink",
		"linkMeta",
		"formats",
		"formatGrid",
		"formatLink",
		"formatTitle",
		"arrow",
	],
	base: {
		hero: {
			display: "grid",
			gap: "8",
			alignItems: "center",
			paddingBlockEnd: "12",
			_lg: {
				gridTemplateColumns: "minmax(0, .9fr) minmax(0, 1.3fr)",
				gap: "12",
				paddingBlockEnd: "16",
			},
		},
		introduction: { display: "grid", gap: "5", minWidth: "0" },
		kicker: {
			margin: "0",
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "medium",
			letterSpacing: "wide",
		},
		title: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "academy-title",
			fontWeight: "extrabold",
			letterSpacing: "academy-display",
			lineHeight: "academy-display",
			textWrap: "balance",
			overflowWrap: "anywhere",
		},
		lede: {
			margin: "0",
			maxWidth: "academy-lede",
			color: "academy.textSoft",
			fontSize: "lg",
			lineHeight: "academy-reading",
			textWrap: "pretty",
		},
		byline: {
			margin: "0",
			color: "academy.textMuted",
			fontSize: "sm",
			lineHeight: "body",
		},
		figure: { display: "grid", gap: "3", minWidth: "0", margin: "0" },
		photo: {
			display: "block",
			width: "full",
			height: "auto",
			borderRadius: "academy-m",
		},
		caption: { color: "academy.textMuted", fontSize: "xs", lineHeight: "body" },
		mission: {
			display: "grid",
			gap: "8",
			paddingBlock: "10",
			borderTop: "hairline",
			_lg: {
				gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1.5fr)",
				gap: "16",
				paddingBlock: "14",
			},
		},
		sectionHeading: {
			display: "grid",
			alignContent: "start",
			gap: "4",
			minWidth: "0",
			maxWidth: "academy-copy",
		},
		sectionTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "academy-section",
			fontWeight: "bold",
			letterSpacing: "academy-display",
			lineHeight: "academy-title",
			textWrap: "balance",
			overflowWrap: "anywhere",
		},
		copy: {
			margin: "0",
			color: "academy.textSoft",
			fontSize: "md",
			lineHeight: "academy-reading",
			textWrap: "pretty",
			overflowWrap: "anywhere",
		},
		principles: {
			display: "grid",
			margin: "0",
			padding: "0",
			listStyle: "none",
			borderTop: "hairline",
		},
		principle: {
			display: "grid",
			gap: "2",
			paddingBlock: "5",
			borderBottom: "hairline",
			_last: { borderBottom: "none", paddingBlockEnd: "0" },
		},
		itemTitle: {
			margin: "0",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "bold",
			letterSpacing: "tight",
			lineHeight: "academy-card",
			overflowWrap: "anywhere",
		},
		story: {
			display: "grid",
			gap: "8",
			paddingBlock: "10",
			borderTop: "hairline",
			_lg: {
				gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1.5fr)",
				gap: "16",
				paddingBlock: "14",
			},
		},
		storyBody: { display: "grid", gap: "8", minWidth: "0" },
		timeline: {
			display: "grid",
			gap: "7",
			margin: "0",
			padding: "0",
			listStyle: "none",
		},
		milestone: {
			display: "grid",
			gap: "3",
			_sm: { gridTemplateColumns: "auto minmax(0, 1fr)", gap: "6" },
		},
		period: {
			margin: "0",
			minWidth: "24",
			paddingBlockStart: "1",
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "medium",
			lineHeight: "body",
			fontVariantNumeric: "tabular-nums",
		},
		milestoneBody: {
			display: "grid",
			gap: "2",
			paddingInlineStart: "5",
			borderInlineStart: "hairline",
			minWidth: "0",
		},
		origins: {
			display: "grid",
			gap: "3",
			paddingBlockStart: "6",
			borderTop: "hairline",
		},
		archiveTitle: {
			margin: "0",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "medium",
			letterSpacing: "wide",
		},
		archiveLinks: {
			display: "grid",
			gap: "1",
			margin: "0",
			padding: "0",
			listStyle: "none",
		},
		archiveLink: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "baseline",
			columnGap: "3",
			rowGap: "1",
			width: "fit-content",
			minHeight: "11",
			paddingBlock: "2",
			color: "academy.text",
			fontSize: "sm",
			fontWeight: "medium",
			textDecoration: "underline",
			_hover: { color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		linkMeta: {
			color: "academy.textMuted",
			fontSize: "xs",
			fontWeight: "normal",
		},
		formats: {
			display: "grid",
			gap: "7",
			paddingBlockStart: "10",
			borderTop: "hairline",
			_lg: { paddingBlockStart: "14" },
		},
		formatGrid: {
			display: "grid",
			gap: "6",
			_lg: { gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "8" },
		},
		formatLink: {
			display: "grid",
			alignContent: "start",
			gap: "3",
			minWidth: "0",
			paddingBlock: "5",
			borderTop: "hairline",
			color: "academy.text",
			textDecoration: "none",
			_hover: {
				"& h3": { color: "academy.accent", textDecoration: "underline" },
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		formatTitle: {
			display: "flex",
			alignItems: "baseline",
			justifyContent: "space-between",
			gap: "3",
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "2xl",
			fontWeight: "bold",
			lineHeight: "academy-card",
			letterSpacing: "tight",
			overflowWrap: "anywhere",
		},
		arrow: { flexShrink: "0", color: "academy.accent", fontSize: "lg" },
	},
});
