import { sva } from "../../styled-system/css";

/** Content primitives. The document wrapper owns header/main/footer landmarks. */
export const academyLayout = sva({
	slots: [
		"root",
		"hero",
		"heroInner",
		"heroCopy",
		"heroAside",
		"masthead",
		"mastheadInner",
		"mastheadCopy",
		"mastheadAside",
		"mastheadKicker",
		"mastheadTitle",
		"mastheadDescription",
		"mastheadFigure",
		"container",
		"kicker",
		"title",
		"description",
		"section",
		"sectionHeader",
		"sectionTitle",
		"grid",
		"card",
		"cardMedia",
		"cardBody",
		"cardTitle",
		"meta",
		"prose",
		"sidebar",
		"split",
		"toolbar",
		"input",
		"button",
		"buttonSecondary",
		"tag",
		"empty",
		"notice",
		"breadcrumbs",
		"list",
		"table",
		"tableWrap",
	],
	base: {
		root: {
			color: "academy.text",
			backgroundColor: "academy.canvas",
			fontFamily: "academy-text",
			lineHeight: "body",
			paddingBottom: "16",
			minWidth: "0",
		},
		hero: {
			paddingBlock: "8",
			paddingInline: "academy-gutter",
			backgroundColor: "academy.canvas",
			borderBottom: "hairline",
			borderColor: "academy.border",
			_lg: { paddingBlock: "10" },
		},
		heroInner: {
			display: "grid",
			gap: "5",
			alignItems: "end",
			_lg: {
				gridTemplateColumns: "minmax(0, 1.15fr) minmax(18rem, .85fr)",
				gap: "12",
			},
		},
		heroCopy: { display: "grid", gap: "4", minWidth: "0" },
		// Collection mastheads open in ink with the title at poster scale and
		// the collection's real size as a numeral. Reading pages keep the
		// canvas hero above.
		masthead: {
			position: "relative",
			overflow: "hidden",
			paddingBlock: "academy-hero-tight",
			paddingInline: "academy-gutter",
			backgroundColor: "academy.ink",
			color: "academy.inkText",
			borderBottom: "hairline",
			borderColor: "academy.inkBorder",
			_lg: { paddingBlock: "academy-hero" },
			"--academy-grid-line":
				"color-mix(in srgb, var(--colors-academy-ink-border) 70%, transparent)",
			_before: {
				content: '""',
				position: "absolute",
				inset: "0",
				pointerEvents: "none",
				backgroundImage:
					"[linear-gradient(var(--academy-grid-line) 1px, transparent 1px), linear-gradient(90deg, var(--academy-grid-line) 1px, transparent 1px)]",
				backgroundSize: "[4rem 4rem]",
				backgroundPosition: "[center top]",
				maskImage:
					"[radial-gradient(120% 100% at 50% 0%, black 20%, transparent 100%)]",
			},
			"& > *": { position: "relative" },
		},
		// The title takes the whole row so a long name never breaks mid-word;
		// the description and numeral share the row beneath it.
		mastheadInner: { display: "grid", gap: "8", _lg: { gap: "10" } },
		mastheadCopy: { display: "grid", gap: "5", minWidth: "0" },
		mastheadAside: {
			display: "grid",
			gap: "6",
			alignItems: "end",
			minWidth: "0",
			_lg: {
				gridTemplateColumns: "minmax(0, 1fr) auto",
				gap: "16",
				"& > :last-child": { textAlign: "end" },
			},
		},
		mastheadKicker: {
			margin: "0",
			color: "academy.inkAccent",
			fontFamily: "academy-mono",
			fontSize: "sm",
		},
		mastheadTitle: {
			margin: "0",
			color: "academy.inkText",
			fontFamily: "academy-display",
			fontSize: "academy-masthead",
			fontWeight: "extrabold",
			lineHeight: "academy-poster",
			letterSpacing: "academy-poster",
			textWrap: "balance",
			overflowWrap: "anywhere",
		},
		mastheadDescription: {
			margin: "0",
			maxWidth: "academy-lede",
			color: "academy.inkTextSoft",
			fontSize: "academy-lede",
			lineHeight: "academy-reading",
			textWrap: "pretty",
		},
		mastheadFigure: {
			display: "grid",
			gap: "1",
			margin: "0",
			color: "academy.inkTextMuted",
			fontFamily: "academy-mono",
			fontSize: "sm",
			"& strong": {
				display: "block",
				color: "academy.inkText",
				fontFamily: "academy-display",
				fontSize: "academy-numeral",
				fontWeight: "extrabold",
				letterSpacing: "academy-poster",
				lineHeight: "none",
				fontVariantNumeric: "tabular-nums",
			},
		},
		heroAside: {
			display: "grid",
			gap: "4",
			alignContent: "end",
			minWidth: "0",
			_lg: { paddingBlockEnd: "1" },
		},
		container: {
			maxWidth: "academy-content",
			marginInline: "auto",
			width: "full",
			minWidth: "0",
		},
		kicker: {
			margin: "0",
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "xs",
			letterSpacing: "wide",
		},
		title: {
			maxWidth: "academy-copy",
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "academy-title",
			fontWeight: "bold",
			lineHeight: "academy-title",
			letterSpacing: "academy-display",
			overflowWrap: "anywhere",
		},
		description: {
			maxWidth: "academy-copy",
			margin: "0",
			color: "academy.textSoft",
			fontSize: "lg",
			lineHeight: "relaxed",
			textWrap: "pretty",
		},
		section: {
			maxWidth: "academy-shell",
			marginInline: "auto",
			paddingInline: "academy-gutter",
			paddingTop: "10",
			minWidth: "0",
		},
		sectionHeader: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			justifyContent: "space-between",
			gap: "4",
			marginBottom: "6",
		},
		sectionTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "2xl",
			fontWeight: "bold",
			lineHeight: "tight",
		},
		grid: {
			display: "grid",
			gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 18rem), 1fr))",
			gap: "6",
		},
		card: {
			display: "flex",
			flexDirection: "column",
			minWidth: "0",
			overflow: "hidden",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			backgroundColor: "academy.panel",
			color: "academy.text",
			textDecoration: "none",
			transitionProperty: "colors",
			transitionDuration: "fast",
			_hover: { borderColor: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
			_motionReduce: { transitionDuration: "none" },
		},
		cardMedia: {
			width: "full",
			aspectRatio: "academy-video",
			objectFit: "cover",
			backgroundColor: "academy.ground",
		},
		cardBody: {
			padding: "6",
			display: "flex",
			flexDirection: "column",
			gap: "3",
		},
		cardTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "bold",
			lineHeight: "tight",
		},
		meta: {
			display: "flex",
			flexWrap: "wrap",
			gap: "3",
			color: "academy.textMuted",
			fontSize: "sm",
			margin: "0",
		},
		prose: {
			color: "academy.textSoft",
			fontSize: "lg",
			lineHeight: "relaxed",
			overflowWrap: "anywhere",
			"& > * + *": { marginTop: "6" },
			"& h2, & h3, & h4": {
				color: "academy.text",
				fontFamily: "academy-display",
				fontWeight: "bold",
				lineHeight: "tight",
			},
			"& h2": { fontSize: "3xl" },
			"& h3": { fontSize: "2xl" },
			"& a": {
				color: "academy.accent",
				textDecoration: "underline",
				textUnderlineOffset: "0.2em",
			},
			"& ul, & ol": {
				display: "grid",
				gap: "3",
				margin: "0",
				paddingInlineStart: "6",
			},
			"& ul": { listStyle: "disc" },
			"& ol": { listStyle: "decimal" },
			"& li": { paddingInlineStart: "1" },
			"& li::marker": {
				color: "academy.accent",
				fontFamily: "academy-mono",
				fontWeight: "bold",
			},
			"& img": { maxWidth: "full", height: "auto" },
			"& pre": {
				maxWidth: "full",
				overflowX: "auto",
				padding: "6",
				borderRadius: "academy-m",
				backgroundColor: "academy.ground",
			},
		},
		sidebar: {
			minWidth: "0",
			alignSelf: "start",
			padding: "6",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			backgroundColor: "academy.panel",
		},
		split: {
			display: "grid",
			gap: "8",
			minWidth: "0",
			_lg: { gridTemplateColumns: "minmax(0, 2fr) minmax(16rem, 1fr)" },
		},
		toolbar: {
			display: "grid",
			gridTemplateColumns: "1fr",
			alignItems: "end",
			columnGap: "4",
			rowGap: "2",
			marginBottom: "8",
			paddingBlock: "3",
			borderBottom: "hairline",
			borderColor: "academy.border",
			"& > label": {
				color: "academy.textMuted",
				fontFamily: "academy-mono",
				fontSize: "xs",
				fontWeight: "semibold",
				letterSpacing: "wide",
			},
			"& > p": {
				justifySelf: "start",
				margin: "0",
				color: "academy.textMuted",
				fontFamily: "academy-mono",
				fontSize: "xs",
				letterSpacing: "wide",
			},
			_sm: { gridTemplateColumns: "1fr minmax(16rem, 24rem)" },
			_lg: {
				gridTemplateColumns: "auto minmax(16rem, 24rem) 1fr",
				"& > p": { justifySelf: "end" },
			},
		},
		input: {
			width: "full",
			minWidth: "0",
			minHeight: "12",
			paddingInline: "4",
			paddingBlock: "2",
			border: "hairline",
			borderColor: "academy.inputBorder",
			borderRadius: "academy-s",
			backgroundColor: "academy.input",
			color: "academy.text",
			font: "inherit",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		button: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			gap: "2",
			minHeight: "11",
			paddingInline: "5",
			paddingBlock: "3",
			backgroundColor: "academy.accent",
			color: "academy.accentForeground",
			border: "academy-button",
			borderRadius: "academy-s",
			fontSize: "sm",
			fontWeight: "bold",
			textDecoration: "none",
			cursor: "pointer",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.text",
				outlineOffset: "focus",
			},
			_disabled: { opacity: "0.5", cursor: "not-allowed" },
		},
		buttonSecondary: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			gap: "2",
			minHeight: "11",
			paddingInline: "5",
			paddingBlock: "3",
			backgroundColor: "transparent",
			color: "academy.text",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			fontSize: "sm",
			fontWeight: "semibold",
			textDecoration: "none",
			cursor: "pointer",
			_hover: { backgroundColor: "academy.panel" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		tag: {
			display: "inline-flex",
			alignItems: "center",
			paddingInline: "3",
			paddingBlock: "1",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-pill",
			fontSize: "xs",
			color: "academy.textSoft",
			backgroundColor: "academy.panel",
			textDecoration: "none",
		},
		empty: {
			padding: "10",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			textAlign: "center",
			color: "academy.textSoft",
		},
		notice: {
			padding: "5",
			border: "hairline",
			borderColor: "academy.border",
			borderTop: "focus",
			borderTopColor: "academy.accent",
			borderRadius: "academy-s",
			backgroundColor: "academy.panel",
			color: "academy.textSoft",
			lineHeight: "relaxed",
			"& a": { color: "academy.accent", textUnderlineOffset: "0.2em" },
		},
		breadcrumbs: {
			display: "flex",
			flexWrap: "wrap",
			gap: "2",
			color: "academy.textMuted",
			fontSize: "sm",
			marginBottom: "6",
		},
		list: {
			display: "grid",
			gap: "4",
			margin: "0",
			padding: "0",
			listStyle: "none",
		},
		tableWrap: {
			width: "full",
			overflowX: "auto",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
		},
		table: {
			width: "full",
			borderCollapse: "collapse",
			fontSize: "sm",
			"& th, & td": {
				padding: "4",
				textAlign: "start",
				borderBottom: "hairline",
				borderColor: "academy.border",
			},
			"& th": {
				backgroundColor: "academy.ground",
				color: "academy.text",
				fontWeight: "semibold",
			},
			"& td": { color: "academy.textSoft" },
		},
	},
	variants: {
		width: {
			wide: {},
			reading: {
				container: { maxWidth: "academy-copy" },
				section: { maxWidth: "academy-copy" },
			},
		},
	},
	defaultVariants: { width: "wide" },
});
