import { sva } from "../../styled-system/css";

/**
 * Listing-specific pieces that sit on top of the shared Academy layout.
 * Keep these intentionally presentational: route data, filtering, and SEO
 * remain in Astro pages.
 */
export const academyCatalog = sva({
	slots: [
		"featured",
		"featuredMedia",
		"featuredImage",
		"featuredBody",
		"featuredKicker",
		"featuredTitle",
		"lead",
		"leadDate",
		"leadBody",
		"leadKicker",
		"leadTitle",
		"leadDescription",
		"featuredDescription",
		"filters",
		"feedLink",
		"filterForm",
		"filterField",
		"filterLink",
		"rows",
		"row",
		"rowIndex",
		"rowMain",
		"rowTitle",
		"rowDescription",
		"rowMeta",
		"avatar",
		"identityGrid",
		"identity",
		"identityMark",
		"identityPortrait",
		"identityAvatar",
		"identityInitials",
		"identityLogo",
		"identityBody",
		"identityTitle",
		"identityMeta",
		"identityDescription",
		"identityArrow",
		"resultCount",
		"empty",
		"statGrid",
		"stat",
		"statValue",
		"statLabel",
		"pager",
		"editorialList",
		"editorialRow",
		"editorialDate",
		"editorialMedia",
		"editorialImage",
		"editorialBody",
		"editorialKind",
		"editorialTitle",
		"editorialDescription",
		"indexGroup",
		"indexLetter",
		"indexList",
		"indexItem",
		"indexMark",
		"indexLogo",
		"indexInitials",
		"indexName",
		"indexMeta",
	],
	base: {
		editorialList: {
			display: "grid",
			borderTop: "hairline",
			borderColor: "academy.border",
		},
		editorialRow: {
			display: "grid",
			gridTemplateColumns: "5.5rem minmax(0, 1fr)",
			columnGap: "4",
			rowGap: "3",
			alignItems: "start",
			paddingBlock: "5",
			borderBottom: "hairline",
			borderColor: "academy.border",
			color: "academy.text",
			textDecoration: "none",
			"&[data-media='false']": {
				gridTemplateColumns: "minmax(0, 1fr)",
				_lg: { gridTemplateColumns: "6.5rem minmax(0, 1fr)" },
			},
			"&[data-media='false'] > :nth-child(2)": { _lg: { gridColumn: "2" } },
			_lg: {
				gridTemplateColumns: "6.5rem 11rem minmax(0, 1fr)",
				columnGap: "8",
				paddingBlock: "6",
			},
			"@supports (animation-timeline: view())": {
				animation: "academy-reveal",
				animationTimeline: "view()",
				animationRange: "entry 0% entry 35%",
			},
			_hover: {
				"& h2, & h3": { color: "academy.accent" },
				"& img": { transform: "scale(1.03)" },
				"& [data-body]": { transform: "translateX(0.35rem)" },
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
			_motionReduce: { animation: "none" },
		},
		// The day is the numeral; month and year sit beneath it in mono.
		editorialDate: {
			gridColumn: "1 / -1",
			display: "flex",
			alignItems: "baseline",
			gap: "2",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			lineHeight: "body",
			"& strong": {
				color: "academy.text",
				fontFamily: "academy-display",
				fontSize: "xl",
				fontWeight: "extrabold",
				letterSpacing: "academy-tight",
				lineHeight: "none",
				fontVariantNumeric: "tabular-nums",
			},
			_lg: {
				gridColumn: "1",
				display: "grid",
				gap: "1",
				paddingBlockStart: "0.5",
				"& strong": { fontSize: "academy-ledger-day" },
			},
		},
		editorialMedia: {
			display: "block",
			overflow: "hidden",
			aspectRatio: "academy-video",
			borderRadius: "academy-s",
			backgroundColor: "academy.ground",
		},
		editorialImage: {
			width: "full",
			height: "full",
			objectFit: "cover",
			transitionProperty: "[transform]",
			transitionDuration: "reveal",
			transitionTimingFunction: "academy-out",
			_motionReduce: { transitionDuration: "none" },
		},
		editorialBody: {
			display: "grid",
			gap: "2",
			minWidth: "0",
			transitionProperty: "[transform]",
			transitionDuration: "slow",
			transitionTimingFunction: "academy-out",
			_motionReduce: { transitionDuration: "none" },
		},
		editorialKind: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			columnGap: "2",
			margin: "0",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			lineHeight: "body",
		},
		editorialTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "lg",
			fontWeight: "bold",
			lineHeight: "tight",
			letterSpacing: "academy-tight",
			textWrap: "pretty",
			transitionProperty: "colors",
			transitionDuration: "base",
			_lg: { fontSize: "2xl" },
		},
		editorialDescription: {
			margin: "0",
			maxWidth: "academy-copy",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "academy-reading",
			textWrap: "pretty",
		},
		// A–Z directory for large reference collections. One letter per
		// group, compact rows inside, so hundreds of entries stay scannable.
		indexGroup: {
			display: "grid",
			gap: "3",
			paddingBlock: "6",
			borderTop: "hairline",
			borderColor: "academy.border",
			"&[hidden]": { display: "none" },
			_lg: { gridTemplateColumns: "6.5rem minmax(0, 1fr)", gap: "8" },
		},
		indexLetter: {
			margin: "0",
			color: "academy.accent",
			fontFamily: "academy-display",
			fontSize: "3xl",
			fontWeight: "extrabold",
			letterSpacing: "academy-tight",
			lineHeight: "none",
		},
		indexList: {
			display: "grid",
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
			columnGap: "4",
			rowGap: "1",
			margin: "0",
			padding: "0",
			listStyle: "none",
			_sm: { gridTemplateColumns: "repeat(3, minmax(0, 1fr))" },
			_lg: { gridTemplateColumns: "repeat(4, minmax(0, 1fr))" },
		},
		indexItem: {
			display: "grid",
			gridTemplateColumns: "auto minmax(0, 1fr)",
			alignItems: "center",
			columnGap: "3",
			minHeight: "11",
			paddingBlock: "1.5",
			paddingInline: "2",
			marginInline: "-2",
			borderRadius: "academy-s",
			color: "academy.text",
			textDecoration: "none",
			_hover: {
				backgroundColor: "academy.panel",
				"& [data-name]": { color: "academy.accent" },
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus-inset",
			},
			"&[hidden]": { display: "none" },
		},
		indexMark: {
			display: "grid",
			placeItems: "center",
			width: "8",
			height: "8",
			overflow: "hidden",
			borderRadius: "academy-s",
			backgroundColor: "academy.panel",
			border: "hairline",
			borderColor: "academy.border",
		},
		indexLogo: { width: "5", height: "5", objectFit: "contain" },
		indexInitials: {
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "academy-caption",
			fontWeight: "semibold",
			lineHeight: "none",
			"&[hidden]": { display: "none" },
		},
		indexName: {
			display: "block",
			overflow: "hidden",
			color: "academy.text",
			fontSize: "sm",
			fontWeight: "semibold",
			lineHeight: "tight",
			textOverflow: "ellipsis",
			whiteSpace: "nowrap",
			transitionProperty: "colors",
			transitionDuration: "fast",
		},
		indexMeta: {
			display: "block",
			overflow: "hidden",
			color: "academy.textMuted",
			fontSize: "xs",
			lineHeight: "tight",
			textOverflow: "ellipsis",
			whiteSpace: "nowrap",
		},
		featured: {
			display: "grid",
			gap: "6",
			alignItems: "center",
			_lg: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "10" },
		},
		// The lead story is typographic: an ink panel on the system grid with
		// the publication day as the numeral. No placeholder artwork.
		lead: {
			position: "relative",
			overflow: "hidden",
			display: "grid",
			gap: "6",
			padding: "8",
			border: "hairline",
			borderColor: "academy.inkBorder",
			borderRadius: "academy-l",
			backgroundColor: "academy.ink",
			color: "academy.inkText",
			_lg: {
				gridTemplateColumns: "auto minmax(0, 1fr)",
				gap: "12",
				padding: "12",
			},
			"--academy-grid-line":
				"color-mix(in srgb, var(--colors-academy-ink-border) 70%, transparent)",
			_before: {
				content: '""',
				position: "absolute",
				inset: "0",
				pointerEvents: "none",
				backgroundImage:
					"[linear-gradient(var(--academy-grid-line) 1px, transparent 1px), linear-gradient(90deg, var(--academy-grid-line) 1px, transparent 1px)]",
				backgroundSize: "[4rem 4rem]",
				backgroundPosition: "[center top]",
				maskImage:
					"[radial-gradient(120% 100% at 50% 0%, black 20%, transparent 100%)]",
			},
			"& > *": { position: "relative" },
		},
		leadDate: {
			display: "grid",
			gap: "1",
			margin: "0",
			color: "academy.inkTextMuted",
			fontFamily: "academy-mono",
			fontSize: "sm",
			"& strong": {
				display: "block",
				color: "academy.inkText",
				fontFamily: "academy-display",
				fontSize: "academy-masthead",
				fontWeight: "extrabold",
				letterSpacing: "academy-poster",
				lineHeight: "none",
				fontVariantNumeric: "tabular-nums",
			},
		},
		leadBody: {
			display: "grid",
			gap: "4",
			alignContent: "center",
			justifyItems: "start",
			minWidth: "0",
		},
		leadKicker: {
			margin: "0",
			color: "academy.inkAccent",
			fontFamily: "academy-mono",
			fontSize: "sm",
		},
		leadTitle: {
			margin: "0",
			color: "academy.inkText",
			fontFamily: "academy-display",
			fontSize: "academy-section",
			fontWeight: "extrabold",
			letterSpacing: "academy-display",
			lineHeight: "academy-title",
			textWrap: "balance",
		},
		leadDescription: {
			margin: "0",
			maxWidth: "academy-lede",
			color: "academy.inkTextSoft",
			fontSize: "academy-lede",
			lineHeight: "academy-reading",
			textWrap: "pretty",
		},
		featuredMedia: {
			display: "block",
			overflow: "hidden",
			borderRadius: "academy-m",
			background: "academy.ground",
			aspectRatio: "academy-video",
			order: "-1",
			_lg: { order: "0" },
		},
		featuredImage: { width: "full", height: "full", objectFit: "cover" },
		featuredBody: {
			display: "flex",
			flexDirection: "column",
			justifyContent: "center",
			alignItems: "flex-start",
			gap: "4",
		},
		featuredKicker: {
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "medium",
			letterSpacing: "wide",
		},
		featuredTitle: {
			margin: "0",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "3xl",
			fontWeight: "bold",
			letterSpacing: "tight",
			lineHeight: "tight",
			textWrap: "balance",
			_lg: { fontSize: "4xl" },
		},
		featuredDescription: {
			margin: "0",
			color: "academy.textSoft",
			fontSize: "md",
			lineHeight: "body",
		},
		filters: {
			display: "flex",
			flexWrap: "wrap",
			gap: "2",
			alignItems: "center",
		},
		feedLink: {
			color: "academy.text",
			fontSize: "sm",
			fontWeight: "semibold",
			textUnderlineOffset: "0.2em",
			_hover: { color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		filterForm: {
			display: "grid",
			gap: "4",
			alignItems: "end",
			paddingBlock: "6",
			marginBottom: "8",
			borderBlock: "hairline",
			borderColor: "academy.border",
			_sm: { gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr) auto" },
		},
		filterField: {
			display: "grid",
			gap: "2",
			color: "academy.textSoft",
			fontSize: "sm",
			fontWeight: "semibold",
		},
		filterLink: {
			display: "inline-flex",
			alignItems: "center",
			minHeight: "9",
			paddingInline: "3",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-pill",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			textDecoration: "none",
			_hover: { borderColor: "academy.accent", color: "academy.text" },
			"&[aria-current='page']": {
				borderColor: "academy.accent",
				background: "academy.accent",
				color: "academy.accentForeground",
			},
		},
		rows: { display: "grid", borderTop: "hairline" },
		row: {
			display: "grid",
			gap: "3",
			alignItems: "start",
			paddingBlock: "6",
			borderBottom: "hairline",
			color: "academy.text",
			textDecoration: "none",
			_sm: { gridTemplateColumns: "6rem minmax(0, 1fr)", gap: "4" },
			_hover: { color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		rowIndex: {
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "xs",
			paddingBlockStart: "1",
		},
		rowMain: { minWidth: "0" },
		rowTitle: {
			display: "block",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "semibold",
			lineHeight: "tight",
		},
		rowDescription: {
			display: "block",
			marginBlockStart: "2",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "body",
		},
		rowMeta: {
			display: "flex",
			flexWrap: "wrap",
			gap: "2",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			lineHeight: "body",
		},
		avatar: {
			width: "12",
			height: "12",
			borderRadius: "full",
			objectFit: "cover",
			background: "academy.ground",
			border: "hairline",
			borderColor: "academy.border",
		},
		identityGrid: {
			display: "grid",
			gridTemplateColumns: "repeat(auto-fill, minmax(min(100%, 20rem), 1fr))",
			gap: "3",
			alignItems: "stretch",
		},
		identity: {
			display: "grid",
			gridTemplateColumns: "auto minmax(0, 1fr) auto",
			alignItems: "center",
			gap: "3",
			minWidth: "0",
			minHeight: "20",
			padding: "4",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			background: "academy.panel",
			color: "academy.text",
			textDecoration: "none",
			transitionProperty: "colors",
			transitionDuration: "fast",
			"&[hidden]": { display: "none" },
			_hover: { borderColor: "academy.accent", background: "academy.ground" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
			_motionReduce: { transitionDuration: "none" },
		},
		identityMark: {
			display: "grid",
			placeItems: "center",
			alignSelf: "start",
			width: "12",
			height: "12",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			background: "academy.ground",
		},
		identityPortrait: {
			display: "grid",
			placeItems: "center",
			width: "12",
			height: "12",
			overflow: "hidden",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "full",
			background: "academy.ground",
		},
		identityAvatar: {
			display: "block",
			width: "full",
			height: "full",
			objectFit: "cover",
		},
		identityInitials: {
			color: "academy.textSoft",
			fontFamily: "academy-mono",
			fontSize: "sm",
			fontWeight: "semibold",
			lineHeight: "none",
			"&[hidden]": { display: "none" },
		},
		identityLogo: { width: "8", height: "8", objectFit: "contain" },
		identityBody: { display: "grid", gap: "1", minWidth: "0" },
		identityTitle: {
			minWidth: "0",
			overflowWrap: "anywhere",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "lg",
			fontWeight: "bold",
			lineHeight: "tight",
		},
		identityMeta: {
			color: "academy.textMuted",
			fontSize: "xs",
			lineHeight: "body",
			overflowWrap: "anywhere",
		},
		identityDescription: {
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "body",
			lineClamp: "2",
			overflowWrap: "anywhere",
		},
		identityArrow: {
			alignSelf: "start",
			paddingBlockStart: "1",
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "lg",
			lineHeight: "none",
		},
		resultCount: {
			margin: "0",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontVariantNumeric: "tabular-nums",
		},
		empty: {
			padding: "8",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			background: "academy.panel",
			textAlign: "center",
			color: "academy.textSoft",
			"&[hidden]": { display: "none" },
			"& h2": {
				margin: "0",
				color: "academy.text",
				fontFamily: "academy-display",
				fontSize: "xl",
				fontWeight: "bold",
				lineHeight: "tight",
			},
			"& p": { marginBlockStart: "2", marginBlockEnd: "0", fontSize: "sm" },
		},
		statGrid: {
			display: "grid",
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
			gap: "3",
			_lg: { gridTemplateColumns: "repeat(4, minmax(0, 1fr))" },
		},
		stat: {
			padding: "4",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			background: "academy.panel",
		},
		statValue: {
			display: "block",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "2xl",
			fontWeight: "bold",
			lineHeight: "tight",
		},
		statLabel: {
			display: "block",
			marginBlockStart: "1",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
		},
		pager: {
			display: "flex",
			justifyContent: "space-between",
			gap: "3",
			marginBlockStart: "8",
		},
	},
	variants: {
		identityLayout: {
			row: {},
			tile: {
				identityGrid: {
					gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
					gap: "2",
					_sm: {
						gridTemplateColumns:
							"repeat(auto-fill, minmax(min(100%, 11rem), 1fr))",
						gap: "3",
					},
				},
				identity: {
					gridTemplateColumns: "minmax(0, 1fr)",
					justifyItems: "start",
					alignContent: "start",
					gap: "3",
					minHeight: "0",
					padding: "3",
					_hover: { "& img": { transform: "scale(1.04)" } },
				},
				identityPortrait: { width: "14", height: "14" },
				identityAvatar: {
					transitionProperty: "[transform]",
					transitionDuration: "slow",
					transitionTimingFunction: "academy-out",
					_motionReduce: { transitionDuration: "none" },
				},
				identityTitle: { fontSize: "md" },
				identityArrow: { display: "none" },
			},
		},
	},
	defaultVariants: { identityLayout: "row" },
});
