import { sva } from "../../styled-system/css";

export const academyAccount = sva({
	slots: ["stack", "list", "panel", "header", "body", "row", "preference", "copy", "title", "label", "description", "heading", "avatar", "identity", "success", "error", "icon", "smallIcon", "emptyIcon", "actions", "divider", "empty", "link", "danger", "button", "spinner", "switchRoot", "switchControl", "switchThumb", "hidden"],
	base: {
		stack: { display: "flex", flexDirection: "column", gap: "8", minWidth: "0" },
		list: { display: "flex", flexDirection: "column", gap: "3" },
		panel: { border: "hairline", borderColor: "academy.border", borderRadius: "academy-m", background: "academy.panel", overflow: "hidden" },
		header: { padding: "6", borderBottom: "hairline", borderColor: "academy.border" },
		body: { padding: "6" },
		row: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: "4", minWidth: "0" },
		preference: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: "4", padding: "4", border: "hairline", borderColor: "academy.border", borderRadius: "academy-s", background: "academy.panel" },
		copy: { flex: "1", minWidth: "0" },
		title: { fontSize: "lg", fontWeight: "semibold", color: "academy.text", fontFamily: "academy-display" },
		label: { fontSize: "md", fontWeight: "medium", color: "academy.text" },
		description: { fontSize: "sm", color: "academy.textMuted", marginTop: "1", overflowWrap: "anywhere" },
		heading: { fontSize: "sm", fontWeight: "semibold", color: "academy.textSoft", textTransform: "uppercase", letterSpacing: "wide", marginBottom: "3" },
		avatar: { width: "16", height: "16", borderRadius: "full", flexShrink: "0", objectFit: "cover" },
		identity: { minWidth: "0", overflowWrap: "anywhere" },
		success: { display: "flex", alignItems: "center", gap: "2", padding: "3", borderRadius: "academy-s", color: "academy.statusSpruce", background: "academy.ground", fontSize: "sm" },
		error: { display: "flex", alignItems: "center", gap: "2", padding: "3", border: "hairline", borderColor: "academy.statusRust", borderRadius: "academy-s", color: "academy.statusRust", background: "academy.panel", fontSize: "sm" },
		icon: { width: "5", height: "5", flexShrink: "0" },
		smallIcon: { width: "4", height: "4", flexShrink: "0" },
		emptyIcon: { display: "inline-flex", alignItems: "center", justifyContent: "center", width: "16", height: "16", borderRadius: "full", background: "academy.ground", color: "academy.accent", marginBottom: "4", "& svg": { width: "8", height: "8" } },
		actions: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: "3" },
		divider: { paddingTop: "6", borderTop: "hairline", borderColor: "academy.border" },
		empty: { textAlign: "center", paddingBlock: "4", color: "academy.textMuted", fontSize: "sm" },
		link: { display: "inline-block", marginTop: "1", color: "academy.accent", fontSize: "sm", textDecoration: "underline", _focusVisible: { outline: "focus", outlineColor: "academy.accent", outlineOffset: "focus" } },
		danger: { minHeight: "11", paddingInline: "3", color: "academy.statusRust", fontSize: "sm", cursor: "pointer", _disabled: { opacity: "0.5", cursor: "wait" }, _focusVisible: { outline: "focus", outlineColor: "academy.accent", outlineOffset: "focus" } },
		button: { display: "inline-flex", alignItems: "center", justifyContent: "center", gap: "2", minHeight: "11", paddingInline: "4", paddingBlock: "2", borderRadius: "academy-s", background: "academy.accent", color: "academy.accentForeground", fontSize: "sm", fontWeight: "semibold", cursor: "pointer", _disabled: { opacity: "0.5", cursor: "wait" }, _focusVisible: { outline: "focus", outlineColor: "academy.accent", outlineOffset: "focus" } },
		spinner: { width: "4", height: "4", animation: "academy-spinner", _motionReduce: { animation: "none" } },
		switchRoot: { flexShrink: "0", display: "inline-flex", alignItems: "center", minHeight: "11", _focusWithin: { outline: "focus", outlineColor: "academy.accent", outlineOffset: "focus", borderRadius: "academy-s" } },
		switchControl: { display: "inline-flex", alignItems: "center", padding: "1", width: "12", height: "7", borderRadius: "full", background: "academy.inputBorder", cursor: "pointer", _checked: { background: "academy.accent" }, _disabled: { opacity: "0.5", cursor: "wait" } },
		switchThumb: { width: "5", height: "5", borderRadius: "full", background: "academy.panel", transform: "translateX(0)", transitionProperty: "common", transitionDuration: "fast", _checked: { transform: "translateX(1.25rem)" }, _motionReduce: { transitionDuration: "none" } },
		hidden: { srOnly: true },
	},
});
