import { sva } from "../../styled-system/css";

const focus = {
	outline: "focus",
	outlineColor: "academy.accent",
	outlineOffset: "focus",
} as const;
const tone = (
	color:
		| "academy.textMuted"
		| "academy.statusRust"
		| "academy.statusAmber"
		| "academy.statusSpruce"
		| "academy.statusViolet"
		| "academy.statusSky",
) => ({
	badge: { color, borderColor: color },
	accent: { color },
	panelTitle: { color },
	statValue: { color },
	dot: { backgroundColor: color },
	diagramNode: { color },
	diagramSwatch: { borderColor: color },
	year: { color },
	milestone: { "&[aria-expanded=true]": { borderColor: color } },
});

/** Instructional cgroup islands; all surfaces follow the Academy color scheme. */
export const academyCgroups = sva({
	slots: [
		"root",
		"toolbar",
		"button",
		"content",
		"heading",
		"copy",
		"muted",
		"row",
		"badges",
		"badge",
		"accent",
		"panel",
		"panelTitle",
		"treeGrid",
		"treeList",
		"treeChildren",
		"treeRow",
		"nodeButton",
		"chevron",
		"nodeName",
		"process",
		"detail",
		"notice",
		"statGrid",
		"stat",
		"statValue",
		"statLabel",
		"legend",
		"dot",
		"scroll",
		"timeline",
		"milestoneItem",
		"milestone",
		"year",
		"milestoneTitle",
		"milestoneDetail",
		"mapper",
		"pane",
		"paneHeader",
		"code",
		"codeText",
		"codeKey",
		"codeValue",
		"codeComment",
		"codeHighlight",
		"arrow",
		"horizontalArrow",
		"verticalArrow",
		"annotation",
		"hidden",
		"diagram",
		"diagramHeader",
		"diagramLegend",
		"diagramLegendItem",
		"diagramSwatch",
		"diagramFrame",
		"diagramSvg",
		"diagramConnectors",
		"diagramNode",
		"diagramBox",
		"diagramLabel",
	],
	base: {
		diagram: {
			// Scoped specificity isolates embedded diagram copy from article prose.
			"&& h3": {
				margin: "0",
				fontFamily: "academy-display",
				fontSize: "xl",
				fontWeight: "bold",
				lineHeight: "tight",
				color: "academy.text",
			},
			"&& p": {
				margin: "0",
				marginTop: "2",
				fontFamily: "academy-text",
				fontSize: "sm",
				lineHeight: "relaxed",
				color: "academy.textSoft",
			},
		},
		diagramHeader: {
			display: "flex",
			flexDirection: "column",
			gap: "4",
			padding: "4",
			md: {
				flexDirection: "row",
				justifyContent: "space-between",
				padding: "6",
			},
		},
		diagramLegend: { display: "grid", gap: "1.5", flexShrink: "0" },
		diagramLegendItem: {
			display: "flex",
			alignItems: "center",
			gap: "2",
			color: "academy.textMuted",
			fontFamily: "academy-text",
			fontSize: "xs",
			lineHeight: "body",
		},
		diagramSwatch: {
			display: "inline-block",
			width: "3",
			height: "2.5",
			flexShrink: "0",
			border: "hairline",
			borderRadius: "academy-s",
		},
		diagramFrame: {
			paddingInline: "4",
			paddingBottom: "4",
			md: { paddingInline: "6", paddingBottom: "6" },
		},
		diagramSvg: { display: "block", width: "full", height: "auto" },
		diagramConnectors: { stroke: "academy.inputBorder" },
		diagramNode: {},
		diagramBox: { fill: "academy.panel", stroke: "currentColor" },
		diagramLabel: {
			fill: "academy.text",
			fontFamily: "academy-mono",
			fontSize: "sm",
		},
		root: {
			marginBlock: "8",
			minWidth: "0",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			backgroundColor: "academy.canvas",
			color: "academy.text",
			fontFamily: "academy-text",
			lineHeight: "body",
		},
		toolbar: {
			display: "flex",
			flexWrap: "wrap",
			gap: "2",
			padding: "4",
			borderBottom: "hairline",
			borderColor: "academy.border",
		},
		button: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			minHeight: "11",
			paddingInline: "4",
			paddingBlock: "2",
			border: "hairline",
			borderColor: "academy.inputBorder",
			borderRadius: "academy-s",
			backgroundColor: "academy.panel",
			color: "academy.textSoft",
			fontSize: "sm",
			fontWeight: "semibold",
			cursor: "pointer",
			_hover: { backgroundColor: "academy.ground", color: "academy.text" },
			_focusVisible: focus,
			"&[aria-pressed=true]": {
				backgroundColor: "academy.accent",
				borderColor: "academy.accent",
				color: "academy.accentForeground",
			},
		},
		content: {
			display: "grid",
			gap: "5",
			padding: "4",
			minWidth: "0",
			md: { padding: "6" },
		},
		heading: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "bold",
			lineHeight: "tight",
			color: "academy.text",
		},
		copy: {
			margin: "0",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "relaxed",
		},
		muted: { margin: "0", color: "academy.textMuted", fontSize: "sm" },
		row: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			gap: "2",
			minWidth: "0",
		},
		badges: {
			display: "inline-flex",
			flexWrap: "wrap",
			gap: "1",
			alignItems: "center",
		},
		badge: {
			display: "inline-flex",
			alignItems: "center",
			paddingInline: "2",
			paddingBlock: "0.5",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			backgroundColor: "academy.panel",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "semibold",
		},
		accent: { color: "academy.textMuted", fontWeight: "semibold" },
		panel: {
			minWidth: "0",
			padding: "3",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			backgroundColor: "academy.panel",
		},
		panelTitle: {
			margin: "0",
			paddingBottom: "2",
			marginBottom: "2",
			borderBottom: "hairline",
			borderColor: "academy.border",
			fontFamily: "academy-mono",
			fontSize: "sm",
			fontWeight: "semibold",
			overflowWrap: "anywhere",
		},
		treeGrid: {
			display: "grid",
			gap: "3",
			minWidth: "0",
			_lg: { gridTemplateColumns: "repeat(3, minmax(0, 1fr))" },
		},
		treeList: { listStyle: "none", padding: "0", margin: "0", minWidth: "0" },
		treeChildren: {
			listStyle: "none",
			margin: "0",
			marginInlineStart: "3",
			paddingInlineStart: "3",
			borderInlineStart: "hairline",
			borderColor: "academy.border",
			minWidth: "0",
		},
		treeRow: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			columnGap: "2",
			rowGap: "1",
			minHeight: "9",
			paddingBlock: "1",
			minWidth: "0",
		},
		nodeButton: {
			display: "inline-flex",
			alignItems: "center",
			gap: "2",
			maxWidth: "full",
			minHeight: "11",
			paddingInline: "1",
			paddingBlock: "1",
			border: "academy-button",
			borderRadius: "academy-s",
			backgroundColor: "transparent",
			color: "academy.text",
			textAlign: "start",
			fontFamily: "academy-mono",
			fontSize: "sm",
			cursor: "pointer",
			overflowWrap: "anywhere",
			_hover: { color: "academy.accent", backgroundColor: "academy.ground" },
			_focusVisible: focus,
		},
		chevron: {
			width: "3",
			height: "3",
			flexShrink: "0",
			"&[data-expanded=true]": { transform: "rotate(90deg)" },
		},
		nodeName: {
			color: "academy.textSoft",
			fontFamily: "academy-mono",
			fontSize: "sm",
			overflowWrap: "anywhere",
		},
		process: {
			color: "academy.statusAmber",
			fontFamily: "academy-mono",
			fontSize: "sm",
			fontWeight: "semibold",
		},
		detail: {
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			overflowWrap: "anywhere",
		},
		notice: {
			padding: "4",
			backgroundColor: "academy.ground",
			borderInlineStart: "focus",
			borderColor: "academy.inputBorder",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "relaxed",
		},
		statGrid: {
			display: "grid",
			gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
			gap: "3",
			margin: "0",
		},
		stat: { display: "grid", gap: "1", alignContent: "start", minWidth: "0" },
		statValue: {
			margin: "0",
			fontFamily: "academy-mono",
			fontSize: "md",
			fontWeight: "bold",
			overflowWrap: "anywhere",
		},
		statLabel: { color: "academy.textMuted", fontSize: "xs" },
		legend: { display: "flex", flexWrap: "wrap", gap: "3" },
		dot: {
			display: "inline-block",
			width: "2.5",
			height: "2.5",
			flexShrink: "0",
			borderRadius: "full",
			backgroundColor: "academy.textMuted",
		},
		scroll: {
			overflowX: "auto",
			minWidth: "0",
			padding: "4",
			_focusVisible: focus,
		},
		timeline: {
			display: "flex",
			alignItems: "start",
			gap: "4",
			listStyle: "none",
			margin: "0",
			padding: "1",
			width: "max-content",
		},
		milestoneItem: { width: "64", minWidth: "0" },
		milestone: {
			display: "grid",
			gap: "2",
			width: "full",
			minHeight: "11",
			padding: "3",
			textAlign: "start",
			border: "hairline",
			borderColor: "academy.inputBorder",
			borderRadius: "academy-s",
			backgroundColor: "academy.panel",
			color: "academy.text",
			cursor: "pointer",
			_hover: { backgroundColor: "academy.ground" },
			_focusVisible: focus,
			"&[aria-expanded=true]": { backgroundColor: "academy.ground" },
		},
		year: {
			fontFamily: "academy-mono",
			fontVariantNumeric: "tabular-nums",
			fontSize: "sm",
			fontWeight: "bold",
		},
		milestoneTitle: {
			color: "academy.text",
			fontSize: "sm",
			fontWeight: "semibold",
			lineHeight: "relaxed",
		},
		milestoneDetail: {
			marginTop: "3",
			paddingInline: "1",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "relaxed",
			"& p": { margin: "0" },
		},
		mapper: {
			display: "flex",
			flexDirection: "column",
			padding: "4",
			minWidth: "0",
			md: { flexDirection: "row" },
		},
		pane: { flex: "1", minWidth: "0" },
		paneHeader: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			gap: "2",
			marginBottom: "3",
		},
		code: {
			margin: "0",
			padding: "4",
			minWidth: "0",
			maxWidth: "full",
			overflowX: "auto",
			whiteSpace: "pre",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			backgroundColor: "academy.panel",
			color: "academy.text",
			fontFamily: "academy-mono",
			fontSize: "sm",
			lineHeight: "relaxed",
			_focusVisible: focus,
		},
		codeKey: { color: "academy.statusViolet" },
		codeText: {
			fontFamily: "inherit",
			fontSize: "inherit",
			color: "inherit",
			lineHeight: "inherit",
		},
		codeValue: { color: "academy.statusSpruce" },
		codeComment: { color: "academy.textMuted" },
		codeHighlight: { color: "academy.accent", fontWeight: "semibold" },
		arrow: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			flexShrink: "0",
			paddingBlock: "2",
			paddingInline: "0",
			color: "academy.textMuted",
			md: { paddingBlock: "0", paddingInline: "2" },
		},
		horizontalArrow: { display: "none", md: { display: "block" } },
		verticalArrow: { display: "block", md: { display: "none" } },
		annotation: {
			margin: "0",
			padding: "4",
			borderTop: "hairline",
			borderColor: "academy.border",
			backgroundColor: "academy.ground",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "relaxed",
		},
		hidden: { srOnly: true },
	},
	variants: {
		tone: {
			neutral: tone("academy.textMuted"),
			rust: tone("academy.statusRust"),
			amber: tone("academy.statusAmber"),
			spruce: tone("academy.statusSpruce"),
			violet: tone("academy.statusViolet"),
			sky: tone("academy.statusSky"),
		},
	},
	defaultVariants: { tone: "neutral" },
});
