import { sva } from "../../styled-system/css";

/** Shared document sections used by marketing, utility, and legal pages. */
export const academyEditorial = sva({
	slots: ["root"],
	base: {
		root: {
			"&[data-reading=true] .editorial-section--split": {
				gridTemplateColumns: "1fr",
			},
			"& .editorial-section": {
				paddingInline: "academy-gutter",
				paddingBlock: "10",
				borderBottom: "hairline",
				borderColor: "academy.border",
				_last: { paddingBottom: "12", borderBottom: "none" },
				_lg: { paddingInline: "0", paddingBlock: "14" },
			},
			"& .editorial-section--split": {
				display: "grid",
				gap: "8",
				_lg: {
					gridTemplateColumns: "minmax(14rem, 0.55fr) minmax(0, 1fr)",
					gap: "12",
				},
			},
			"& .editorial-section__header": {
				display: "grid",
				gap: "3",
				alignContent: "start",
			},
			"& .editorial-section__title": {
				margin: "0",
				color: "academy.text",
				fontFamily: "academy-display",
				fontSize: "3xl",
				lineHeight: "tight",
			},
			"& .editorial-section__lede, & .editorial-card__body": {
				color: "academy.textSoft",
				lineHeight: "relaxed",
			},
			"& .editorial-grid": { display: "grid", gap: "5" },
			"& .editorial-grid--2": {
				_sm: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
			},
			"& .editorial-grid--3": {
				md: { gridTemplateColumns: "repeat(3, minmax(0, 1fr))" },
			},
			"& .editorial-grid--4": {
				_sm: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
				_lg: { gridTemplateColumns: "repeat(4, minmax(0, 1fr))" },
			},
			"& .editorial-section:not(.editorial-section--split) > .editorial-section__header + *":
				{ marginTop: "6" },
			"& .editorial-card": {
				minWidth: "0",
				padding: "6",
				border: "hairline",
				borderColor: "academy.border",
				borderRadius: "academy-m",
				background: "academy.panel",
			},
			"& .editorial-card--paper": { background: "academy.ground" },
			"& .editorial-card__title": {
				margin: "0",
				color: "academy.text",
				fontFamily: "academy-display",
				fontSize: "xl",
				fontWeight: "bold",
				lineHeight: "tight",
			},
			"& .editorial-card__body": { marginTop: "3" },
			"& .editorial-kicker, & .editorial-meta": {
				color: "academy.textMuted",
				fontFamily: "academy-mono",
				fontSize: "xs",
				letterSpacing: "wide",
				textTransform: "uppercase",
			},
			"& .editorial-kicker": { color: "academy.accent", margin: "0" },
			"& .editorial-actions, & .editorial-button-row, & .editorial-pill-row": {
				display: "flex",
				flexWrap: "wrap",
				gap: "3",
				alignItems: "center",
			},
			"& .editorial-button": {
				display: "inline-flex",
				alignItems: "center",
				justifyContent: "center",
				minHeight: "11",
				paddingInline: "5",
				paddingBlock: "3",
				border: "academy-button",
				borderRadius: "academy-s",
				background: "academy.accent",
				color: "academy.accentForeground",
				fontWeight: "bold",
				textDecoration: "none",
				_focusVisible: {
					outline: "focus",
					outlineColor: "academy.accent",
					outlineOffset: "focus",
				},
			},
			"& .editorial-button--secondary": {
				borderColor: "academy.border",
				background: "transparent",
				color: "academy.text",
			},
			"& .editorial-pill": {
				display: "inline-flex",
				paddingInline: "3",
				paddingBlock: "1",
				border: "hairline",
				borderColor: "academy.border",
				borderRadius: "academy-pill",
				color: "academy.textSoft",
				fontSize: "xs",
			},
			"& .editorial-list": {
				display: "grid",
				gap: "3",
				margin: "0",
				paddingInlineStart: "5",
				color: "academy.textSoft",
				lineHeight: "relaxed",
				listStyle: "disc",
			},
			"& .editorial-prose": {
				color: "academy.textSoft",
				fontSize: "lg",
				lineHeight: "academy-reading",
				"& > * + *": { marginTop: "5" },
			},
			"& .editorial-prose h2, & .editorial-prose h3": {
				color: "academy.text",
				fontFamily: "academy-display",
				fontWeight: "bold",
				lineHeight: "academy-title",
				marginTop: "10",
			},
			"& .editorial-prose h2": { fontSize: "2xl" },
			"& .editorial-prose h3": { fontSize: "xl" },
			"& .editorial-prose a": {
				color: "academy.accent",
				textDecoration: "underline",
				textUnderlineOffset: "0.2em",
			},
			"& .editorial-prose ul, & .editorial-prose ol": {
				paddingInlineStart: "6",
				display: "grid",
				gap: "2",
			},
			"& .editorial-prose ul": { listStyle: "disc" },
			"& .editorial-prose ol": { listStyle: "decimal" },
			"& .editorial-faq": { display: "grid", gap: "3" },
			"& .editorial-faq details": {
				padding: "5",
				border: "hairline",
				borderColor: "academy.border",
				borderRadius: "academy-m",
				background: "academy.panel",
			},
			"& .editorial-faq summary": {
				cursor: "pointer",
				color: "academy.text",
				fontWeight: "bold",
				_focusVisible: {
					outline: "focus",
					outlineColor: "academy.accent",
					outlineOffset: "focus",
				},
			},
			"& .editorial-faq p": {
				color: "academy.textSoft",
				lineHeight: "relaxed",
			},
			"& .editorial-stat-grid": {
				display: "grid",
				gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 10rem), 1fr))",
				gap: "4",
			},
			"& .editorial-stat": {
				padding: "5",
				borderInlineStart: "focus",
				borderColor: "academy.accent",
				background: "academy.panel",
			},
			"& .editorial-stat__value": {
				display: "block",
				color: "academy.text",
				fontFamily: "academy-display",
				fontSize: "3xl",
				fontWeight: "bold",
			},
			"& .editorial-stat__label": {
				display: "block",
				marginTop: "1",
				color: "academy.textMuted",
				fontSize: "sm",
			},
		},
	},
});
