import { sva } from "../../styled-system/css";

/** Dense reference pages: readable code, mobile cards, and wide-screen tables. */
export const academyReference = sva({
	slots: ["panel", "notice", "grid", "stack", "list", "row", "actions", "center", "heading", "subheading", "label", "text", "muted", "accent", "success", "warning", "danger", "code", "inlineCode", "tag", "iconBadge", "icon", "checkbox", "mobile", "desktop", "dot", "dotWrap", "pulse", "cell", "monoCell", "context"],
	base: {
		panel: { padding: "6", marginBottom: "8", border: "hairline", borderColor: "academy.border", borderRadius: "academy-m", background: "academy.panel", minWidth: "0", _lg: { padding: "10" } },
		notice: { padding: "6", border: "hairline", borderColor: "academy.border", borderRadius: "academy-s", background: "academy.ground", display: "flex", flexDirection: "column", gap: "5", minWidth: "0" },
		grid: { display: "grid", gridTemplateColumns: "minmax(0, 1fr)", gap: "6", color: "academy.textSoft", _sm: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" } },
		stack: { display: "flex", flexDirection: "column", gap: "8" },
		list: { display: "flex", flexDirection: "column", gap: "3" },
		row: { display: "flex", alignItems: "start", flexWrap: "wrap", gap: "3", minWidth: "0" },
		actions: { display: "flex", flexWrap: "wrap", justifyContent: "center", alignItems: "center", gap: "4" },
		center: { textAlign: "center", marginBottom: "8", "& p": { marginInline: "auto" } },
		heading: { fontFamily: "academy-display", fontSize: "2xl", fontWeight: "bold", color: "academy.text", marginBottom: "6" },
		subheading: { display: "flex", alignItems: "center", gap: "2", fontFamily: "academy-display", fontSize: "xl", fontWeight: "semibold", color: "academy.text", marginBottom: "3" },
		label: { fontWeight: "semibold", color: "academy.text", fontSize: "md", marginBottom: "2" },
		text: { fontSize: "sm", color: "academy.textSoft", lineHeight: "relaxed", overflowWrap: "anywhere" },
		muted: { fontSize: "sm", color: "academy.textMuted", lineHeight: "relaxed", overflowWrap: "anywhere" },
		accent: { color: "academy.accent" },
		success: { color: "academy.statusSpruce", overflowWrap: "anywhere" },
		warning: { color: "academy.statusAmber" },
		danger: { color: "academy.statusRust" },
		code: { background: "academy.ground", color: "academy.text", padding: "4", marginTop: "3", borderRadius: "academy-s", fontFamily: "academy-mono", fontSize: "sm", overflowX: "auto", maxWidth: "full", minWidth: "0", "& > * + *": { marginTop: "2" } },
		inlineCode: { background: "academy.ground", paddingInline: "1", borderRadius: "academy-s", fontFamily: "academy-mono", fontSize: "xs", overflowWrap: "anywhere" },
		tag: { display: "inline-flex", alignItems: "center", gap: "2", paddingInline: "3", paddingBlock: "1", borderRadius: "academy-pill", border: "hairline", borderColor: "academy.border", background: "academy.ground", color: "academy.accent", fontSize: "xs", fontWeight: "medium" },
		iconBadge: { display: "inline-flex", alignItems: "center", justifyContent: "center", width: "16", height: "16", borderRadius: "full", background: "academy.ground", color: "academy.statusSpruce", marginBottom: "4" },
		icon: { width: "8", height: "8", color: "academy.statusSpruce" },
		checkbox: { width: "5", height: "5", flexShrink: "0", accentColor: "academy.accent", marginTop: "1", _focusVisible: { outline: "focus", outlineColor: "academy.accent", outlineOffset: "focus" } },
		mobile: { display: "flex", flexDirection: "column", gap: "3", _sm: { display: "none" } },
		desktop: { display: "none", _sm: { display: "block" } },
		dot: { width: "2", height: "2", borderRadius: "full", background: "academy.accent" },
		dotWrap: { position: "relative", display: "inline-flex", width: "2", height: "2" },
		pulse: { display: "none" },
		cell: { padding: "4", borderBottom: "hairline", borderColor: "academy.border", textAlign: "left" },
		monoCell: { padding: "4", borderBottom: "hairline", borderColor: "academy.border", fontFamily: "academy-mono", fontSize: "xs" },
		context: { marginTop: "12" },
	},
});
