import { sva } from "../../styled-system/css";

export const academyBracket = sva({
	slots: [
		"root",
		"bracket",
		"header",
		"title",
		"metadata",
		"hint",
		"board",
		"round",
		"roundTitle",
		"matches",
		"match",
		"side",
		"name",
		"seed",
		"versus",
		"status",
		"winner",
		"empty",
	],
	base: {
		root: {
			display: "grid",
			gap: "12",
			width: "full",
			minWidth: "0",
			fontFamily: "academy-text",
			color: "academy.text",
		},
		bracket: { display: "grid", gap: "4", minWidth: "0" },
		header: { display: "grid", gap: "2", minWidth: "0" },
		title: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: { base: "xl", md: "2xl" },
			fontWeight: "bold",
			lineHeight: "tight",
			overflowWrap: "anywhere",
		},
		metadata: {
			display: "flex",
			flexWrap: "wrap",
			gap: "3",
			color: "academy.textMuted",
			fontSize: "sm",
			lineHeight: "normal",
		},
		hint: {
			margin: "0",
			color: "academy.textMuted",
			fontSize: "sm",
			lineHeight: "normal",
		},
		board: {
			display: "flex",
			alignItems: "flex-start",
			gap: "6",
			width: "full",
			maxWidth: "full",
			minWidth: "0",
			overflowX: "auto",
			padding: "1",
			paddingBottom: "4",
			overscrollBehaviorX: "contain",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		round: { width: "64", minWidth: "64", flexShrink: "0" },
		roundTitle: {
			margin: "0",
			marginBottom: "4",
			paddingBottom: "3",
			borderBottom: "hairline",
			borderColor: "academy.border",
			fontFamily: "academy-display",
			fontSize: "md",
			fontWeight: "bold",
		},
		matches: {
			display: "grid",
			gap: "4",
			padding: "0",
			margin: "0",
			listStyle: "none",
		},
		match: {
			display: "grid",
			gap: "2",
			minWidth: "0",
			padding: "4",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			background: "academy.panel",
			fontSize: "sm",
			lineHeight: "normal",
		},
		side: {
			display: "flex",
			alignItems: "baseline",
			justifyContent: "space-between",
			gap: "3",
			minWidth: "0",
			color: "academy.textSoft",
			"&[data-winner=true]": { color: "academy.text", fontWeight: "bold" },
		},
		name: { minWidth: "0", overflowWrap: "anywhere" },
		seed: {
			flexShrink: "0",
			fontFamily: "academy-mono",
			fontSize: "xs",
			color: "academy.textMuted",
		},
		versus: { color: "academy.textMuted", fontSize: "xs" },
		status: {
			margin: "0",
			color: "academy.textMuted",
			"&[data-live=true]": { color: "academy.accent", fontWeight: "bold" },
		},
		winner: {
			margin: "0",
			paddingTop: "2",
			borderTop: "hairline",
			borderColor: "academy.border",
			color: "academy.text",
			fontWeight: "bold",
			overflowWrap: "anywhere",
		},
		empty: {
			margin: "0",
			paddingBlock: "8",
			color: "academy.textSoft",
			lineHeight: "relaxed",
		},
	},
});
