import { sva } from "../../styled-system/css";

export const academyCourse = sva({
	slots: [
		"resources",
		"header",
		"heading",
		"category",
		"group",
		"resource",
		"icon",
		"iconBadge",
		"smallIcon",
		"copy",
		"title",
		"description",
		"meta",
		"arrow",
		"workbench",
		"toolbar",
		"actions",
		"status",
		"ready",
		"error",
		"spinner",
		"split",
		"pane",
		"filebar",
		"select",
		"editorFrame",
		"editor",
		"preview",
		"placeholder",
		"terminal",
		"terminalOutput",
		"terminalLine",
		"link",
		"button",
		"embed",
		"fill",
		"detailHero",
		"detailContainer",
		"heroGrid",
		"heroCopy",
		"heroTitle",
		"heroDescription",
		"heroCover",
		"kicker",
		"metadata",
		"byline",
		"author",
		"avatar",
		"curriculumAction",
		"detailBody",
		"detailGrid",
		"detailStack",
		"sectionHeading",
		"objectiveList",
		"supplementary",
		"signup",
		"curriculum",
		"lessonGroups",
		"lessonGroup",
		"lessonHeader",
		"lessonList",
		"lessonRow",
		"lessonLink",
		"lessonIndex",
		"lessonCopy",
		"lessonTitle",
		"lessonDescription",
		"lessonMeta",
		"unpublished",
		"emptyCurriculum",
		"referenceLink",
	],
	base: {
		referenceLink: {
			display: "inline-flex",
			alignItems: "center",
			width: "fit-content",
			minHeight: "11",
			paddingBlock: "2",
		},
		detailHero: {
			paddingBlock: "6",
			paddingInline: "academy-gutter",
			background: "academy.ground",
			color: "academy.text",
			fontFamily: "academy-text",
			borderBottom: "hairline",
			borderColor: "academy.border",
			_lg: { paddingBlock: "8", paddingInline: "academy-gutter-wide" },
		},
		detailContainer: {
			width: "full",
			maxWidth: "academy-content",
			marginInline: "auto",
			minWidth: "0",
		},
		heroGrid: {
			display: "grid",
			alignItems: "center",
			gap: "5",
			minWidth: "0",
			_sm: { gridTemplateColumns: "minmax(0, 1fr) minmax(0, .65fr)", gap: "8" },
		},
		heroCopy: {
			display: "grid",
			justifyItems: "start",
			gap: "3",
			minWidth: "0",
		},
		heroTitle: {
			margin: "0",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "academy-title",
			fontWeight: "bold",
			lineHeight: "academy-title",
			letterSpacing: "academy-display",
			textWrap: "balance",
			overflowWrap: "anywhere",
		},
		heroDescription: {
			margin: "0",
			maxWidth: "academy-copy",
			color: "academy.textSoft",
			fontSize: "md",
			lineHeight: "body",
			textWrap: "pretty",
		},
		heroCover: {
			display: "block",
			width: "full",
			maxWidth: "full",
			height: "auto",
			aspectRatio: "academy-video",
			objectFit: "contain",
			borderRadius: "academy-m",
			background: "academy.ground",
		},
		kicker: {
			margin: "0",
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "semibold",
			letterSpacing: "wide",
			textTransform: "uppercase",
		},
		metadata: {
			display: "flex",
			flexWrap: "wrap",
			columnGap: "4",
			rowGap: "1",
			listStyle: "none",
			margin: "0",
			padding: "0",
			color: "academy.textMuted",
			fontSize: "sm",
			lineHeight: "body",
		},
		byline: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			columnGap: "3",
			rowGap: "2",
			color: "academy.textSoft",
			fontSize: "sm",
		},
		author: {
			display: "inline-flex",
			alignItems: "center",
			gap: "2",
			color: "academy.text",
			textDecoration: "none",
			_hover: { textDecoration: "underline" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		avatar: {
			width: "7",
			height: "7",
			flexShrink: "0",
			borderRadius: "full",
			objectFit: "cover",
			background: "academy.panel",
		},
		curriculumAction: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			minHeight: "11",
			paddingInline: "4",
			paddingBlock: "2",
			marginBlockStart: "1",
			border: "academy-button",
			borderRadius: "academy-s",
			background: "academy.accent",
			color: "academy.accentForeground",
			fontSize: "sm",
			fontWeight: "bold",
			textDecoration: "none",
			_hover: { opacity: "0.9" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		detailBody: {
			display: "grid",
			gap: "10",
			width: "full",
			maxWidth: "academy-shell",
			marginInline: "auto",
			paddingBlock: "8",
			paddingInline: "academy-gutter",
			minWidth: "0",
			color: "academy.text",
			fontFamily: "academy-text",
			_lg: { paddingInline: "academy-gutter-wide" },
		},
		detailGrid: {
			display: "grid",
			alignItems: "start",
			gap: "8",
			minWidth: "0",
			_lg: { gridTemplateColumns: "minmax(0, 2fr) minmax(0, 1fr)" },
		},
		detailStack: { display: "grid", gap: "6", minWidth: "0" },
		sectionHeading: {
			margin: "0",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "2xl",
			fontWeight: "bold",
			lineHeight: "tight",
		},
		objectiveList: {
			display: "grid",
			gap: "2",
			margin: "0",
			paddingInlineStart: "5",
			listStyleType: "disc",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "body",
			"& li::marker": { color: "academy.accent" },
		},
		supplementary: {
			display: "grid",
			gap: "6",
			alignSelf: "start",
			minWidth: "0",
		},
		signup: {
			display: "grid",
			gap: "4",
			minWidth: "0",
			padding: "5",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			background: "academy.panel",
		},
		curriculum: {
			display: "grid",
			gap: "5",
			minWidth: "0",
			scrollMarginBlockStart: "24",
		},
		lessonGroups: { display: "grid", gap: "6", minWidth: "0" },
		lessonGroup: { display: "grid", gap: "2", minWidth: "0" },
		lessonHeader: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "baseline",
			justifyContent: "space-between",
			gap: "2",
		},
		lessonList: {
			margin: "0",
			padding: "0",
			listStyle: "none",
			borderTop: "hairline",
			borderColor: "academy.border",
		},
		lessonRow: {
			display: "grid",
			gridTemplateColumns: "auto minmax(0, 1fr)",
			alignItems: "start",
			gap: "3",
			minWidth: "0",
			paddingBlock: "4",
			paddingInline: "2",
			borderBottom: "hairline",
			borderColor: "academy.border",
			color: "academy.text",
			textDecoration: "none",
			_sm: { gridTemplateColumns: "auto minmax(0, 1fr) auto", gap: "4" },
		},
		lessonLink: {
			_hover: { background: "academy.ground" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus-inset",
			},
		},
		lessonIndex: {
			paddingBlockStart: "0.5",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
		},
		lessonCopy: { display: "grid", gap: "1", minWidth: "0" },
		lessonTitle: {
			margin: "0",
			color: "academy.text",
			fontFamily: "academy-text",
			fontSize: "md",
			fontWeight: "semibold",
			lineHeight: "body",
		},
		lessonDescription: {
			margin: "0",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "body",
			overflowWrap: "anywhere",
		},
		lessonMeta: {
			display: "flex",
			alignItems: "center",
			gap: "2",
			gridColumn: "2",
			color: "academy.textMuted",
			fontSize: "xs",
			lineHeight: "body",
			_sm: { gridColumn: "auto" },
		},
		unpublished: { color: "academy.textMuted" },
		emptyCurriculum: {
			margin: "0",
			paddingBlock: "4",
			color: "academy.textMuted",
			fontSize: "sm",
		},
		resources: { display: "flex", flexDirection: "column", gap: "6" },
		header: {
			paddingBottom: "5",
			borderBottom: "hairline",
			borderColor: "academy.border",
		},
		heading: {
			display: "flex",
			alignItems: "center",
			gap: "3",
			fontFamily: "academy-display",
			fontSize: "2xl",
			fontWeight: "bold",
			color: "academy.text",
		},
		category: {
			display: "flex",
			alignItems: "center",
			gap: "2",
			marginBottom: "3",
			fontSize: "sm",
			fontFamily: "academy-mono",
			fontWeight: "semibold",
			color: "academy.accent",
			textTransform: "uppercase",
			letterSpacing: "wide",
		},
		group: {
			paddingBottom: "6",
			borderBottom: "hairline",
			borderColor: "academy.border",
			_last: { borderBottom: "none", paddingBottom: "0" },
		},
		resource: {
			display: "grid",
			gridTemplateColumns: "auto minmax(0, 1fr) auto",
			width: "full",
			gap: "3",
			paddingBlock: "4",
			textAlign: "left",
			borderBottom: "hairline",
			borderColor: "academy.border",
			color: "academy.text",
			textDecoration: "none",
			cursor: "pointer",
			_hover: { background: "academy.ground" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		icon: { width: "5", height: "5", flexShrink: "0" },
		iconBadge: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			width: "10",
			height: "10",
			borderRadius: "full",
			background: "academy.ground",
			color: "academy.accent",
		},
		smallIcon: { width: "4", height: "4", flexShrink: "0" },
		copy: { minWidth: "0", overflowWrap: "anywhere" },
		title: { fontWeight: "semibold", color: "academy.text", fontSize: "lg" },
		description: {
			marginTop: "2",
			fontSize: "sm",
			color: "academy.textSoft",
			lineHeight: "relaxed",
		},
		meta: {
			marginTop: "3",
			fontFamily: "academy-mono",
			fontSize: "xs",
			color: "academy.textMuted",
		},
		arrow: {
			display: "flex",
			alignItems: "start",
			paddingTop: "1",
			color: "academy.accent",
		},
		workbench: {
			height: "full",
			minHeight: "0",
			display: "flex",
			flexDirection: "column",
			background: "academy.canvas",
			color: "academy.text",
			fontFamily: "academy-text",
		},
		toolbar: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			justifyContent: "space-between",
			gap: "3",
			padding: "4",
			background: "academy.panel",
			borderBottom: "hairline",
			borderColor: "academy.border",
		},
		actions: {
			display: "flex",
			alignItems: "center",
			flexWrap: "wrap",
			gap: "3",
			minWidth: "0",
		},
		status: {
			display: "inline-flex",
			alignItems: "center",
			gap: "2",
			color: "academy.textMuted",
			fontSize: "sm",
		},
		ready: { color: "academy.statusSpruce", fontSize: "sm" },
		error: { color: "academy.statusRust", fontSize: "sm" },
		spinner: {
			width: "4",
			height: "4",
			border: "focus",
			borderColor: "academy.border",
			borderTopColor: "academy.accent",
			borderRadius: "full",
			animation: "academy-spinner",
			_motionReduce: { animation: "none" },
		},
		split: {
			flex: "1",
			minHeight: "0",
			display: "grid",
			gridTemplateColumns: "minmax(0, 1fr)",
			overflow: "auto",
			_lg: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
		},
		pane: {
			display: "flex",
			flexDirection: "column",
			minWidth: "0",
			minHeight: "64",
			border: "hairline",
			borderColor: "academy.border",
		},
		filebar: {
			padding: "2",
			background: "academy.panel",
			borderBottom: "hairline",
			borderColor: "academy.border",
		},
		select: {
			width: "full",
			minHeight: "11",
			paddingInline: "3",
			background: "academy.input",
			color: "academy.text",
			border: "hairline",
			borderColor: "academy.inputBorder",
			borderRadius: "academy-s",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		editorFrame: { flex: "1", position: "relative", minHeight: "64" },
		editor: {
			position: "absolute",
			inset: "0",
			width: "full",
			height: "full",
			padding: "4",
			background: "academy.input",
			color: "academy.text",
			fontFamily: "academy-mono",
			fontSize: "sm",
			resize: "none",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus-inset",
			},
		},
		preview: {
			position: "absolute",
			inset: "0",
			width: "full",
			height: "full",
			border: "none",
		},
		placeholder: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			padding: "6",
			textAlign: "center",
			color: "academy.textMuted",
			height: "full",
		},
		terminal: {
			height: "48",
			flexShrink: "0",
			background: "academy.ground",
			borderTop: "hairline",
			borderColor: "academy.border",
			display: "flex",
			flexDirection: "column",
			overflow: "hidden",
		},
		terminalOutput: {
			flex: "1",
			minHeight: "0",
			overflowY: "auto",
			padding: "3",
			fontFamily: "academy-mono",
			fontSize: "xs",
			whiteSpace: "pre-wrap",
			overflowWrap: "anywhere",
		},
		terminalLine: { color: "academy.textSoft" },
		link: {
			color: "academy.accent",
			fontSize: "sm",
			textDecoration: "underline",
			overflowWrap: "anywhere",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		button: {
			minHeight: "11",
			minWidth: "11",
			paddingInline: "3",
			color: "academy.textSoft",
			fontSize: "sm",
			borderRadius: "academy-s",
			cursor: "pointer",
			_hover: { background: "academy.ground", color: "academy.text" },
			_disabled: { opacity: "0.5", cursor: "not-allowed" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		embed: {
			position: "relative",
			background: "academy.ground",
			minHeight: "64",
			maxHeight: "academy-command",
		},
		fill: { width: "full", height: "full" },
	},
});
