import { sva } from "../../styled-system/css";

export const academyPage = sva({
	slots: [
		"root",
		"header",
		"nav",
		"brand",
		"navLinks",
		"navActions",
		"iconButton",
		"headerButton",
		"hero",
		"heroInner",
		"feature",
		"featureCopy",
		"featureArt",
		"featureImage",
		"kicker",
		"title",
		"lede",
		"meta",
		"actions",
		"buttonPrimary",
		"buttonGhost",
		"section",
		"sectionInner",
		"railHeader",
		"railTitle",
		"railLink",
		"railTrack",
		"card",
		"cardArt",
		"cardImage",
		"cardMeta",
		"cardTitle",
		"cardLink",
		"join",
		"joinCopy",
		"joinTitle",
		"joinBody",
		"joinForm",
		"joinLabel",
		"joinRow",
		"input",
		"checkboxLabel",
		"finePrint",
		"footer",
		"footerNav",
		"pageHero",
		"pageShell",
		"pageKicker",
		"pageTitle",
		"pageLede",
		"pageSection",
		"pageSectionHead",
		"pathList",
		"pathCard",
		"pathIndex",
		"pathBody",
		"pathTitle",
		"pathDescription",
		"pathFact",
		"pathArrow",
		"callout",
		"calloutTitle",
		"calloutBody",
		"tagRow",
		"tag",
		"watchLayout",
		"videoFrame",
		"videoImage",
		"videoOverlay",
		"play",
		"watchCopy",
		"watchTitle",
		"watchBody",
		"watchAside",
		"watchFact",
		"resourceLinks",
	],
	base: {
		root: {
			minHeight: "screen",
			backgroundColor: "academy.canvas",
			color: "academy.text",
			fontFamily: "academy-text",
			fontSize: "md",
			lineHeight: "body",
		},
		header: {
			position: "relative",
			backgroundColor: "academy.ground",
			backgroundImage:
				"linear-gradient(var(--colors-academy-grid) 1px, transparent 1px), linear-gradient(90deg, var(--colors-academy-grid) 1px, transparent 1px)",
			backgroundSize: "48px 48px",
			borderBottom: "hairline",
			borderColor: "academy.border",
			paddingInline: "academy-gutter",
			_lg: {
				paddingInline: "academy-gutter-wide",
			},
		},
		nav: {
			display: "flex",
			alignItems: "center",
			justifyContent: "space-between",
			gap: "4",
			minHeight: "16",
			_lg: {
				minHeight: "24",
			},
		},
		brand: {
			paddingBlock: "2",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "lg",
			fontWeight: "extrabold",
			letterSpacing: "tight",
			whiteSpace: "nowrap",
			_lg: {
				fontSize: "xl",
			},
		},
		navLinks: {
			display: "none",
			alignItems: "center",
			gap: "9",
			marginInlineEnd: "auto",
			marginInlineStart: "12",
			color: "academy.textMuted",
			fontSize: "sm",
			fontWeight: "medium",
			_lg: {
				display: "flex",
			},
		},
		navActions: {
			display: "flex",
			alignItems: "center",
			gap: "1",
		},
		iconButton: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			width: "11",
			height: "11",
			border: "academy-button",
			borderRadius: "academy-s",
			background: "transparent",
			color: "academy.text",
			fontFamily: "inherit",
			fontSize: "lg",
			cursor: "pointer",
			_hover: {
				background: "academy.panel",
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
			_motionReduce: {
				transitionDuration: "none",
				_hover: {
					transform: "none",
				},
			},
		},
		headerButton: {
			display: "none",
			_lg: {
				display: "inline-flex",
			},
		},
		hero: {
			backgroundColor: "academy.ground",
			backgroundImage:
				"linear-gradient(var(--colors-academy-grid) 1px, transparent 1px), linear-gradient(90deg, var(--colors-academy-grid) 1px, transparent 1px)",
			backgroundSize: "40px 40px",
			paddingInline: "academy-gutter",
			paddingBottom: "8",
			_lg: {
				backgroundSize: "48px 48px",
				paddingInline: "academy-gutter-wide",
				paddingBottom: "0",
			},
		},
		heroInner: {
			maxWidth: "academy-shell",
			marginInline: "auto",
			width: "full",
		},
		feature: {
			display: "flex",
			flexDirection: "column",
			gap: "6",
			paddingBlock: "8",
			_lg: {
				flexDirection: "row",
				alignItems: "center",
				gap: "16",
				paddingBlock: "12",
			},
		},
		featureCopy: {
			display: "flex",
			flexGrow: 1,
			flexShrink: 1,
			flexDirection: "column",
			gap: "5",
			_lg: {
				gap: "7",
			},
		},
		featureArt: {
			display: "block",
			order: "-1",
			aspectRatio: "academy-video",
			width: "full",
			overflow: "hidden",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			background: "academy.panel",
			_lg: {
				order: "0",
				flexGrow: 0,
				flexShrink: 0,
				flexBasis: "academy-feature",
			},
		},
		featureImage: {
			display: "block",
			width: "full",
			height: "full",
			objectFit: "cover",
		},
		kicker: {
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "medium",
			letterSpacing: "widest",
			textTransform: "uppercase",
		},
		title: {
			maxWidth: "academy-copy",
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "4xl",
			fontWeight: "extrabold",
			letterSpacing: "tight",
			lineHeight: "tight",
			textWrap: "balance",
			_lg: {
				fontSize: "6xl",
			},
		},
		lede: {
			maxWidth: "academy-copy",
			margin: "0",
			color: "academy.textSoft",
			fontSize: "lg",
			lineHeight: "body",
			_lg: {
				fontSize: "xl",
			},
		},
		meta: {
			display: "flex",
			flexWrap: "wrap",
			gap: "4",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			letterSpacing: "wide",
		},
		actions: {
			display: "flex",
			flexWrap: "wrap",
			gap: "3",
			marginTop: "2",
		},
		buttonPrimary: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			minHeight: "14",
			paddingInline: "7",
			border: "academy-button",
			borderRadius: "academy-s",
			background: "academy.accent",
			color: "academy.accentForeground",
			fontFamily: "academy-text",
			fontSize: "md",
			fontWeight: "semibold",
			textDecoration: "none",
			cursor: "pointer",
			transitionProperty: "colors",
			transitionDuration: "fast",
			_hover: {
				transform: "translateY(-1px)",
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		buttonGhost: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			minHeight: "14",
			paddingInline: "6",
			border: "hairline",
			borderColor: "academy.inputBorder",
			borderRadius: "academy-s",
			background: "transparent",
			color: "academy.text",
			fontFamily: "academy-text",
			fontSize: "md",
			fontWeight: "medium",
			textDecoration: "none",
			cursor: "pointer",
			_hover: {
				background: "academy.panel",
				borderColor: "academy.accent",
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		section: {
			paddingBlockStart: "academy-section",
			_lg: {
				paddingBlockStart: "academy-section-wide",
			},
		},
		sectionInner: {
			maxWidth: "academy-shell",
			marginInline: "auto",
			paddingInline: "academy-gutter",
			_lg: {
				paddingInline: "academy-gutter-wide",
			},
		},
		railHeader: {
			display: "flex",
			alignItems: "baseline",
			justifyContent: "space-between",
			gap: "6",
			marginBottom: "5",
		},
		railTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "2xl",
			fontWeight: "bold",
			letterSpacing: "tight",
			lineHeight: "tight",
			_lg: {
				fontSize: "3xl",
			},
		},
		railLink: {
			paddingBlock: "2",
			color: "academy.textMuted",
			fontSize: "sm",
			textDecoration: "none",
			whiteSpace: "nowrap",
			_hover: {
				color: "academy.text",
			},
		},
		railTrack: {
			display: "flex",
			gap: "6",
			overflowX: "auto",
			paddingBlock: "1",
			paddingInlineEnd: "academy-gutter",
			scrollbarWidth: "none",
			_lg: {
				gap: "8",
				paddingInlineEnd: "academy-gutter-wide",
			},
			"&::-webkit-scrollbar": {
				display: "none",
			},
		},
		card: {
			display: "flex",
			flexGrow: 0,
			flexShrink: 0,
			flexBasis: "academy-card-mobile",
			flexDirection: "column",
			gap: "3",
			scrollSnapAlign: "start",
			_lg: {
				flexBasis: "academy-card",
			},
		},
		cardArt: {
			aspectRatio: "academy-video",
			width: "full",
			overflow: "hidden",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			background: "academy.panel",
		},
		cardImage: {
			width: "full",
			height: "full",
			objectFit: "cover",
		},
		cardMeta: {
			display: "flex",
			justifyContent: "space-between",
			gap: "3",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			letterSpacing: "wide",
			textTransform: "uppercase",
		},
		cardTitle: {
			margin: "0",
			overflow: "hidden",
			color: "academy.text",
			fontSize: "lg",
			fontWeight: "medium",
			lineHeight: "tight",
			textDecoration: "none",
			textOverflow: "ellipsis",
			_hover: {
				textDecoration: "underline",
				textUnderlineOffset: "3px",
			},
		},
		cardLink: {
			textDecoration: "none",
		},
		join: {
			display: "grid",
			gap: "6",
			maxWidth: "academy-shell",
			marginInline: "auto",
			marginBlockStart: "academy-section",
			padding: "8",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-l",
			background: "academy.ground",
			_lg: {
				gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
				gap: "academy-join",
				marginBlockStart: "academy-section-wide",
				padding: "academy-join",
				marginInline: "academy-gutter-wide",
			},
		},
		joinCopy: {
			maxWidth: "academy-copy",
		},
		joinTitle: {
			margin: "0",
			marginBottom: "3",
			fontFamily: "academy-display",
			fontSize: "4xl",
			fontWeight: "extrabold",
			letterSpacing: "tight",
			lineHeight: "tight",
		},
		joinBody: {
			margin: "0",
			color: "academy.textSoft",
			fontSize: "md",
		},
		joinForm: {
			display: "flex",
			flexDirection: "column",
			gap: "3",
		},
		joinLabel: {
			fontSize: "sm",
			fontWeight: "semibold",
		},
		joinRow: {
			display: "flex",
			flexDirection: "column",
			gap: "3",
			_lg: {
				flexDirection: "row",
			},
		},
		input: {
			minWidth: "0",
			minHeight: "14",
			flex: "1",
			paddingInline: "4",
			border: "hairline",
			borderColor: "academy.inputBorder",
			borderRadius: "academy-s",
			background: "academy.input",
			color: "academy.text",
			fontFamily: "academy-text",
			fontSize: "md",
			_focus: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		checkboxLabel: {
			display: "flex",
			alignItems: "center",
			gap: "3",
			minHeight: "11",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "body",
		},
		finePrint: {
			margin: "0",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
		},
		footer: {
			display: "flex",
			flexDirection: "column",
			gap: "1",
			marginBlockStart: "academy-section",
			paddingBlock: "6",
			paddingInline: "academy-gutter",
			borderTop: "hairline",
			borderColor: "academy.border",
			color: "academy.textMuted",
			fontSize: "sm",
			_lg: {
				flexDirection: "row",
				alignItems: "center",
				justifyContent: "space-between",
				paddingInline: "academy-gutter-wide",
			},
		},
		footerNav: {
			display: "flex",
			flexWrap: "wrap",
			gap: "6",
		},
		pageHero: {
			background: "academy.ground",
			backgroundImage:
				"linear-gradient(var(--colors-academy-grid) 1px, transparent 1px), linear-gradient(90deg, var(--colors-academy-grid) 1px, transparent 1px)",
			backgroundSize: "48px 48px",
			borderBottom: "hairline",
			borderColor: "academy.border",
			paddingBlock: "12",
			paddingInline: "academy-gutter",
			_lg: {
				paddingBlock: "academy-join",
				paddingInline: "academy-gutter-wide",
			},
		},
		pageShell: {
			maxWidth: "academy-shell",
			marginInline: "auto",
		},
		pageKicker: {
			marginBottom: "3",
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "medium",
			letterSpacing: "widest",
			textTransform: "uppercase",
		},
		pageTitle: {
			maxWidth: "academy-copy",
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "4xl",
			fontWeight: "extrabold",
			letterSpacing: "tight",
			lineHeight: "tight",
			textWrap: "balance",
			_lg: {
				fontSize: "6xl",
			},
		},
		pageLede: {
			maxWidth: "academy-copy",
			margin: "0",
			marginTop: "5",
			color: "academy.textSoft",
			fontSize: "lg",
			_lg: {
				fontSize: "xl",
			},
		},
		pageSection: {
			maxWidth: "academy-shell",
			marginInline: "auto",
			paddingBlock: "academy-section",
			paddingInline: "academy-gutter",
			_lg: {
				paddingBlock: "academy-section-wide",
				paddingInline: "academy-gutter-wide",
			},
		},
		pageSectionHead: {
			display: "flex",
			alignItems: "baseline",
			justifyContent: "space-between",
			gap: "6",
			marginBottom: "6",
		},
		pathList: {
			display: "grid",
			gap: "3",
		},
		pathCard: {
			display: "grid",
			gridTemplateColumns: "48px minmax(0, 1fr) auto",
			alignItems: "center",
			gap: "3",
			padding: "5",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			background: "academy.panel",
			transitionProperty: "colors",
			transitionDuration: "fast",
			_hover: {
				borderColor: "academy.accent",
				background: "academy.ground",
				transform: "translateY(-1px)",
			},
			_lg: {
				gridTemplateColumns: "72px minmax(0, 1fr) 190px auto",
				gap: "6",
				padding: "6",
			},
			_motionReduce: {
				transitionDuration: "none",
				_hover: {
					transform: "none",
				},
			},
		},
		pathIndex: {
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "sm",
		},
		pathBody: {
			minWidth: "0",
		},
		pathTitle: {
			margin: "0",
			marginBottom: "1",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "semibold",
			lineHeight: "tight",
		},
		pathDescription: {
			margin: "0",
			color: "academy.textSoft",
			fontSize: "sm",
		},
		pathFact: {
			display: "none",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			textTransform: "uppercase",
			_lg: {
				display: "block",
			},
		},
		pathArrow: {
			color: "academy.accent",
			fontSize: "2xl",
		},
		callout: {
			display: "grid",
			gap: "6",
			alignItems: "center",
			padding: "6",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-l",
			background: "academy.ground",
			_lg: {
				gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
				gap: "9",
				padding: "8",
			},
		},
		calloutTitle: {
			margin: "0",
			marginBottom: "3",
			fontFamily: "academy-display",
			fontSize: "3xl",
			fontWeight: "extrabold",
			letterSpacing: "tight",
			lineHeight: "tight",
		},
		calloutBody: {
			maxWidth: "academy-copy",
			margin: "0",
			color: "academy.textSoft",
		},
		tagRow: {
			display: "flex",
			flexWrap: "wrap",
			gap: "2",
		},
		tag: {
			display: "inline-flex",
			alignItems: "center",
			minHeight: "8",
			paddingInline: "3",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-pill",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
		},
		watchLayout: {
			display: "grid",
			gap: "8",
			alignItems: "start",
			_lg: {
				gridTemplateColumns: "minmax(0, 1fr) 300px",
				gap: "10",
			},
		},
		videoFrame: {
			position: "relative",
			aspectRatio: "academy-video",
			overflow: "hidden",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			background: "academy.panel",
		},
		videoImage: {
			width: "full",
			height: "full",
			objectFit: "cover",
		},
		videoOverlay: {
			position: "absolute",
			inset: "0",
			display: "grid",
			placeItems: "center",
			backgroundColor: "academy.ground",
			backgroundImage:
				"linear-gradient(135deg, rgb(5 12 24 / 0.25), rgb(5 12 24 / 0.78))",
		},
		play: {
			display: "grid",
			placeItems: "center",
			width: "academy-play",
			height: "academy-play",
			border: "hairline",
			borderColor: "academy.accent",
			borderRadius: "full",
			background: "academy.accent",
			color: "academy.accentForeground",
			fontSize: "2xl",
		},
		watchCopy: {
			maxWidth: "academy-copy",
			marginBlockStart: "6",
		},
		watchTitle: {
			margin: "0",
			marginBottom: "3",
			fontFamily: "academy-display",
			fontSize: "3xl",
			fontWeight: "bold",
			lineHeight: "tight",
		},
		watchBody: {
			color: "academy.textSoft",
			fontSize: "md",
			"& p": {
				margin: "0",
				marginBottom: "4",
			},
			"& ul": {
				margin: "0",
				paddingInlineStart: "5",
			},
		},
		watchAside: {
			position: "static",
			padding: "5",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			background: "academy.panel",
			_lg: {
				position: "sticky",
				top: "6",
			},
		},
		watchFact: {
			paddingBlock: "3",
			borderTop: "hairline",
			borderColor: "academy.border",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			textTransform: "uppercase",
			"& strong": {
				display: "block",
				marginBlockStart: "1",
				color: "academy.text",
				fontFamily: "academy-text",
				fontSize: "md",
				fontWeight: "medium",
				textTransform: "none",
			},
		},
		resourceLinks: {
			display: "grid",
			marginBlockStart: "4",
			"& a": {
				display: "flex",
				justifyContent: "space-between",
				paddingBlock: "3",
				borderTop: "hairline",
				borderColor: "academy.border",
				color: "academy.text",
				fontWeight: "semibold",
				textDecoration: "none",
			},
			"& a:hover": {
				color: "academy.accent",
			},
		},
	},
});
