import { sva } from "../../styled-system/css";

/** Production chrome, shared by every Academy document. */
export const academyShell = sva({
	slots: [
		"root",
		"header",
		"nav",
		"brand",
		"brandArt",
		"links",
		"link",
		"actions",
		"search",
		"searchLabel",
		"searchKey",
		"account",
		"authButton",
		"profileTrigger",
		"profileAvatar",
		"profilePositioner",
		"profileMenu",
		"profileIdentity",
		"profileName",
		"profileEmail",
		"profileMenuItems",
		"profileMenuItem",
		"profileMenuButton",
		"main",
		"skip",
		"footer",
		"footerInner",
		"footerLead",
		"footerTagline",
		"footerGroups",
		"footerGroup",
		"footerTitle",
		"footerLink",
		"copyright",
		"mobile",
		"menuTrigger",
		"backdrop",
		"positioner",
		"panel",
		"panelHeader",
		"panelTitle",
		"close",
		"menuGroups",
		"menuGroup",
		"menuHeading",
		"menuLink",
	],
	base: {
		root: {
			minHeight: "screen",
			display: "flex",
			flexDirection: "column",
			backgroundColor: "academy.canvas",
			color: "academy.text",
			fontFamily: "academy-text",
			lineHeight: "body",
		},
		header: {
			backgroundColor: "academy.canvas",
			borderBottom: "hairline",
			borderColor: "academy.border",
			position: "relative",
		},
		nav: {
			maxWidth: "academy-shell",
			marginInline: "auto",
			paddingInline: "academy-gutter",
			minHeight: "20",
			display: "flex",
			alignItems: "center",
			gap: "2",
			_lg: { gap: "6", minHeight: "24" },
		},
		brand: {
			display: "inline-flex",
			alignItems: "center",
			// Inherits so the same mark reads navy in the header and paper on
			// the ink footer.
			color: "inherit",
			flexShrink: "0",
			minHeight: "11",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		brandArt: {
			display: "block",
			width: "36",
			_lg: { width: "48" },
			"& svg": { display: "block", width: "full", height: "auto" },
			"& path": { fill: "currentColor" },
		},
		links: {
			display: "none",
			gap: "6",
			alignItems: "center",
			marginInlineEnd: "auto",
			_lg: { display: "flex" },
		},
		link: {
			position: "relative",
			color: "academy.textSoft",
			fontSize: "sm",
			fontWeight: "semibold",
			textDecoration: "none",
			paddingBlock: "3",
			transitionProperty: "colors",
			transitionDuration: "fast",
			_hover: { color: "academy.text" },
			"&[aria-current=page]": {
				color: "academy.text",
				textDecoration: "underline",
				textDecorationThickness: "2px",
				textDecorationColor: "academy.accent",
				textUnderlineOffset: "0.45em",
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		actions: {
			display: "flex",
			alignItems: "center",
			gap: "1",
			marginInlineStart: "auto",
		},
		search: {
			display: "none",
			alignItems: "center",
			gap: "2",
			minWidth: "11",
			minHeight: "11",
			paddingInline: "3",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			backgroundColor: "academy.panel",
			color: "academy.textSoft",
			fontSize: "sm",
			textDecoration: "none",
			transitionProperty: "colors",
			transitionDuration: "fast",
			_lg: { display: "inline-flex", marginInlineEnd: "2" },
			_hover: { borderColor: "academy.inputBorder", color: "academy.text" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		searchLabel: { display: "none", _lg: { display: "inline" } },
		searchKey: {
			display: "none",
			paddingInline: "1.5",
			paddingBlock: "0.5",
			borderRadius: "xs",
			border: "hairline",
			borderColor: "academy.border",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "academy-caption",
			lineHeight: "none",
			_lg: { display: "inline-block" },
		},
		account: { display: "none", _lg: { display: "block" } },
		authButton: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			minHeight: "9",
			paddingInline: "4",
			paddingBlock: "2",
			border: "academy-button",
			borderRadius: "academy-s",
			backgroundColor: "academy.accent",
			color: "academy.accentForeground",
			fontFamily: "academy-text",
			fontSize: "sm",
			fontWeight: "bold",
			lineHeight: "none",
			textDecoration: "none",
			transitionProperty: "[transform]",
			transitionDuration: "fast",
			_hover: { opacity: "0.92" },
			_active: { transform: "translateY(1px)" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		profileTrigger: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			width: "9",
			height: "9",
			borderRadius: "full",
			color: "academy.text",
			cursor: "pointer",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		profileAvatar: {
			width: "8",
			height: "8",
			borderRadius: "full",
			objectFit: "cover",
			border: "hairline",
			borderColor: "academy.border",
		},
		profilePositioner: { zIndex: "overlay" },
		profileMenu: {
			width: "56",
			overflow: "hidden",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			backgroundColor: "academy.panel",
			color: "academy.text",
			boxShadow: "dialog",
			outline: "none",
		},
		profileIdentity: {
			display: "flex",
			flexDirection: "column",
			gap: "1",
			padding: "4",
			borderBottom: "hairline",
			borderColor: "academy.border",
		},
		profileName: {
			overflow: "hidden",
			color: "academy.text",
			fontSize: "sm",
			fontWeight: "semibold",
			textOverflow: "ellipsis",
			whiteSpace: "nowrap",
		},
		profileEmail: {
			overflow: "hidden",
			color: "academy.textMuted",
			fontSize: "xs",
			textOverflow: "ellipsis",
			whiteSpace: "nowrap",
		},
		profileMenuItems: { display: "grid", gap: "1", padding: "1" },
		profileMenuItem: {
			display: "flex",
			alignItems: "center",
			minHeight: "9",
			paddingInline: "3",
			borderRadius: "academy-s",
			color: "academy.textSoft",
			fontSize: "sm",
			textDecoration: "none",
			cursor: "pointer",
			_hover: { backgroundColor: "academy.ground", color: "academy.text" },
			"&[data-highlighted]": {
				backgroundColor: "academy.ground",
				color: "academy.text",
				outline: "none",
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		profileMenuButton: {
			width: "full",
			textAlign: "start",
			border: "academy-button",
			backgroundColor: "transparent",
		},
		main: { flex: "1", width: "full", minWidth: "0", outline: "none" },
		skip: {
			position: "fixed",
			top: "2",
			left: "2",
			zIndex: "overlay",
			transform: "translateY(-200%)",
			padding: "3",
			backgroundColor: "academy.accent",
			color: "academy.accentForeground",
			fontWeight: "bold",
			_focus: {
				transform: "none",
				outline: "focus",
				outlineColor: "academy.text",
			},
		},
		footer: {
			borderTop: "hairline",
			borderColor: "academy.inkBorder",
			backgroundColor: "academy.ink",
			color: "academy.inkText",
			paddingInline: "academy-gutter",
			paddingBlock: "14",
			_lg: { paddingBlock: "20" },
		},
		footerInner: {
			maxWidth: "academy-content",
			marginInline: "auto",
			display: "grid",
			gap: "12",
			_lg: { gridTemplateColumns: "minmax(0, 1fr) minmax(0, 2fr)", gap: "16" },
		},
		footerLead: {
			display: "grid",
			gap: "5",
			justifyItems: "start",
			alignContent: "start",
			color: "academy.inkText",
		},
		footerTagline: {
			margin: "0",
			maxWidth: "academy-lede",
			color: "academy.inkTextSoft",
			fontSize: "md",
			lineHeight: "academy-reading",
			textWrap: "pretty",
		},
		footerGroups: {
			display: "grid",
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
			gap: "8",
			_lg: { gridTemplateColumns: "repeat(4, minmax(0, 1fr))" },
		},
		footerGroup: {
			display: "flex",
			flexDirection: "column",
			alignItems: "flex-start",
			gap: "2",
		},
		footerTitle: {
			margin: "0",
			marginBottom: "1",
			color: "academy.inkText",
			fontFamily: "academy-display",
			fontSize: "sm",
			fontWeight: "bold",
		},
		footerLink: {
			color: "academy.inkTextSoft",
			fontSize: "sm",
			textDecoration: "none",
			paddingBlock: "2",
			_hover: { color: "academy.inkText", textDecoration: "underline", textUnderlineOffset: "0.25em" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.inkAccent",
				outlineOffset: "focus",
			},
		},
		copyright: {
			margin: "0",
			paddingTop: "8",
			borderTop: "hairline",
			borderColor: "academy.inkBorder",
			color: "academy.inkTextMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			lineHeight: "body",
			_lg: { gridColumn: "1 / -1" },
		},
		mobile: { display: "block", _lg: { display: "none" } },
		menuTrigger: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			width: "11",
			height: "11",
			border: "academy-button",
			borderRadius: "academy-s",
			backgroundColor: "transparent",
			color: "academy.text",
			cursor: "pointer",
			_hover: { backgroundColor: "academy.panel" },
			_focusVisible: { outline: "focus", outlineColor: "academy.accent" },
		},
		backdrop: {
			position: "fixed",
			inset: "0",
			zIndex: "overlay",
			backgroundColor: "editorial.overlay",
			_open: { animation: "academy-fade" },
			_motionReduce: { animation: "none" },
		},
		positioner: {
			position: "fixed",
			inset: "0",
			zIndex: "overlay",
			display: "flex",
			justifyContent: "flex-end",
		},
		panel: {
			width: "full",
			maxWidth: "lg",
			height: "full",
			overflowY: "auto",
			overscrollBehavior: "contain",
			backgroundColor: "academy.canvas",
			color: "academy.text",
			padding: "6",
			fontFamily: "academy-text",
			borderInlineStart: "hairline",
			borderColor: "academy.border",
			_open: { animation: "academy-slide-in" },
			_motionReduce: { animation: "none", transitionDuration: "none" },
		},
		panelHeader: {
			display: "flex",
			alignItems: "center",
			justifyContent: "space-between",
			gap: "4",
			marginBottom: "6",
		},
		panelTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "2xl",
			fontWeight: "extrabold",
			letterSpacing: "academy-tight",
		},
		close: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			minWidth: "11",
			minHeight: "11",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			backgroundColor: "academy.panel",
			color: "academy.text",
			cursor: "pointer",
			_focusVisible: { outline: "focus", outlineColor: "academy.accent" },
		},
		menuGroups: {
			display: "grid",
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
			columnGap: "4",
			rowGap: "6",
		},
		menuGroup: {
			margin: "0",
			padding: "0",
			listStyle: "none",
			display: "grid",
			gap: "1",
		},
		menuHeading: {
			margin: "0",
			marginBottom: "2",
			color: "academy.textMuted",
			fontSize: "xs",
			letterSpacing: "wide",
		},
		menuLink: {
			display: "flex",
			alignItems: "center",
			minHeight: "11",
			paddingInline: "3",
			color: "academy.text",
			borderRadius: "academy-s",
			textDecoration: "none",
			_hover: { backgroundColor: "academy.panel" },
			"&[aria-current=page]": {
				backgroundColor: "academy.panel",
				color: "academy.accent",
			},
			_focusVisible: { outline: "focus", outlineColor: "academy.accent" },
		},
	},
});
