import { sva } from "../../styled-system/css";

/** Linked editorial content: readable titles, genuine imagery, and ruled news. */
export const academyRelatedContent = sva({
	slots: [
		"root",
		"section",
		"related",
		"heading",
		"grid",
		"pathGrid",
		"card",
		"path",
		"media",
		"image",
		"duration",
		"body",
		"title",
		"copy",
		"metadata",
		"newsList",
		"newsItem",
		"link",
		"empty",
	],
	base: {
		root: {
			display: "grid",
			gap: "12",
			minWidth: "0",
			fontFamily: "academy-text",
			color: "academy.text",
		},
		section: {
			display: "grid",
			gap: "6",
			minWidth: "0",
			fontFamily: "academy-text",
			color: "academy.text",
		},
		related: {
			marginTop: "12",
			paddingTop: "8",
			borderTop: "hairline",
			borderColor: "academy.border",
		},
		heading: {
			margin: "0",
			fontFamily: "academy-display",
			fontWeight: "bold",
			fontSize: { base: "xl", md: "2xl" },
			lineHeight: "tight",
			overflowWrap: "anywhere",
		},
		grid: {
			display: "grid",
			gap: "6",
			gridTemplateColumns: {
				base: "minmax(0, 1fr)",
				md: "repeat(2, minmax(0, 1fr))",
				lg: "repeat(3, minmax(0, 1fr))",
			},
		},
		pathGrid: {
			display: "grid",
			gap: "6",
			gridTemplateColumns: {
				base: "minmax(0, 1fr)",
				md: "repeat(2, minmax(0, 1fr))",
			},
		},
		card: {
			display: "block",
			minWidth: "0",
			color: "academy.text",
			textDecoration: "none",
			borderBottom: "hairline",
			borderColor: "academy.border",
			_hover: { color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		path: {
			display: "grid",
			alignContent: "start",
			gap: "3",
			padding: "5",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			background: "academy.panel",
			_hover: { background: "academy.ground", borderColor: "academy.accent" },
		},
		media: {
			position: "relative",
			aspectRatio: "video",
			overflow: "hidden",
			background: "academy.ground",
		},
		image: {
			display: "block",
			width: "full",
			height: "full",
			objectFit: "cover",
		},
		duration: {
			position: "absolute",
			bottom: "2",
			right: "2",
			paddingInline: "2",
			paddingBlock: "1",
			borderRadius: "academy-s",
			background: "academy.canvas",
			color: "academy.text",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontVariantNumeric: "tabular-nums",
			lineHeight: "normal",
		},
		body: { paddingBlock: "4" },
		title: {
			margin: "0",
			fontFamily: "academy-display",
			fontWeight: "bold",
			fontSize: "lg",
			lineHeight: "snug",
			overflowWrap: "anywhere",
			color: "inherit",
		},
		copy: {
			margin: "0",
			maxWidth: "academy-copy",
			fontSize: "md",
			lineHeight: "relaxed",
			color: "academy.textSoft",
			overflowWrap: "anywhere",
		},
		metadata: {
			display: "flex",
			flexWrap: "wrap",
			gap: "3",
			color: "academy.textMuted",
			fontSize: "sm",
			lineHeight: "normal",
		},
		newsList: {
			margin: "0",
			padding: "0",
			listStyle: "none",
			borderBlock: "hairline",
			borderColor: "academy.border",
			"& > li + li": { borderTop: "hairline", borderColor: "academy.border" },
		},
		newsItem: {
			paddingBlock: "6",
			"& > article": { display: "grid", gap: "2" },
		},
		link: {
			color: "inherit",
			textDecoration: "none",
			_hover: {
				color: "academy.accent",
				textDecoration: "underline",
				textUnderlineOffset: "3px",
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		empty: {
			paddingBlock: "8",
			color: "academy.textMuted",
			lineHeight: "relaxed",
			margin: "0",
		},
	},
});
