import { sva } from "../../styled-system/css";

/** The Academy front door, video library, and learning-path directory. */
export const academyPage = sva({
	slots: [
		"root",
		"container",
		"hero",
		"kicker",
		"feature",
		"featureCopy",
		"title",
		"titleAccent",
		"lede",
		"actions",
		"buttonPrimary",
		"buttonSecondary",
		"textLink",
		"featureCard",
		"featureArt",
		"featureImage",
		"featureCaption",
		"featureTitle",
		"play",
		"archiveNote",
		"formatNav",
		"formatLink",
		"formatHeading",
		"section",
		"sectionHead",
		"sectionTitle",
		"feedGrid",
		"card",
		"cardArt",
		"cardImage",
		"cardBody",
		"cardMeta",
		"cardTitle",
		"cardDescription",
		"pageHero",
		"pageHeroGrid",
		"pageTitle",
		"resultCount",
		"pathList",
		"pathCard",
		"pathIndex",
		"pathBody",
		"pathTitle",
		"pathMeta",
		"pathArrow",
		"watchFeature",
		"watchTitle",
		"searchBar",
		"input",
		"empty",
		"more",
		"newsletter",
		"newsletterForm",
		"newsletterRow",
		"finePrint",
	],
	base: {
		root: {
			backgroundColor: "academy.canvas",
			color: "academy.text",
			fontFamily: "academy-text",
			paddingBottom: "16",
			minWidth: "0",
		},
		container: {
			maxWidth: "academy-shell",
			marginInline: "auto",
			paddingInline: "academy-gutter",
			width: "full",
		},
		hero: {
			paddingBlockStart: "10",
			backgroundColor: "academy.canvas",
			_lg: { paddingBlockStart: "16" },
		},
		kicker: {
			margin: "0",
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "medium",
			letterSpacing: "wide",
			textTransform: "uppercase",
		},
		feature: {
			display: "grid",
			gap: "10",
			paddingBlock: "6",
			alignItems: "center",
			_lg: { gridTemplateColumns: "1.05fr 1fr", gap: "12", paddingBlock: "10" },
		},
		featureCopy: {
			display: "grid",
			gap: "5",
			minWidth: "0",
			alignContent: "center",
		},
		title: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "academy-display",
			fontWeight: "extrabold",
			letterSpacing: "academy-display",
			lineHeight: "academy-display",
		},
		titleAccent: { color: "academy.accent" },
		lede: {
			margin: "0",
			maxWidth: "academy-lede",
			color: "academy.textSoft",
			fontSize: "lg",
			lineHeight: "academy-reading",
			textWrap: "pretty",
		},
		actions: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			gap: "5",
			marginTop: "3",
		},
		buttonPrimary: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			gap: "3",
			minHeight: "12",
			paddingInline: "5",
			paddingBlock: "3",
			border: "academy-button",
			borderRadius: "academy-s",
			backgroundColor: "academy.accent",
			color: "academy.accentForeground",
			fontFamily: "academy-text",
			fontSize: "sm",
			fontWeight: "bold",
			lineHeight: "academy-card",
			textDecoration: "none",
			cursor: "pointer",
			_hover: { opacity: "0.9" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		buttonSecondary: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			gap: "3",
			minHeight: "12",
			paddingInline: "5",
			paddingBlock: "3",
			border: "hairline",
			borderColor: "academy.inputBorder",
			borderRadius: "academy-s",
			backgroundColor: "academy.panel",
			color: "academy.text",
			fontWeight: "semibold",
			cursor: "pointer",
			_hover: { borderColor: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		textLink: {
			display: "inline-flex",
			alignItems: "center",
			gap: "2",
			width: "fit-content",
			minHeight: "11",
			color: "academy.text",
			fontSize: "sm",
			fontWeight: "semibold",
			textDecoration: "none",
			_hover: {
				color: "academy.accent",
				textDecoration: "underline",
				textUnderlineOffset: "0.2em",
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		featureCard: {
			display: "block",
			minWidth: "0",
			color: "academy.text",
			textDecoration: "none",
			_hover: { "& h2": { color: "academy.accent" } },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		featureArt: {
			position: "relative",
			display: "block",
			aspectRatio: "academy-video",
			overflow: "hidden",
			backgroundColor: "academy.ground",
			borderRadius: "academy-m",
		},
		featureImage: {
			display: "block",
			width: "full",
			height: "full",
			objectFit: "cover",
		},
		featureCaption: { display: "grid", gap: "2", paddingTop: "4" },
		featureTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "bold",
			lineHeight: "tight",
			letterSpacing: "tight",
		},
		play: {
			position: "absolute",
			top: "4",
			right: "4",
			display: "grid",
			placeItems: "center",
			width: "11",
			height: "11",
			borderRadius: "full",
			backgroundColor: "academy.accent",
			color: "academy.accentForeground",
			fontSize: "sm",
		},
		archiveNote: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			columnGap: "6",
			rowGap: "2",
			paddingBlock: "6",
			marginTop: "4",
			borderTop: "hairline",
			borderColor: "academy.border",
			color: "academy.textMuted",
			fontSize: "sm",
			"& strong": { color: "academy.text", fontWeight: "semibold" },
			"& > :last-child": { _lg: { marginInlineStart: "auto" } },
		},
		formatNav: {
			display: "grid",
			maxWidth: "academy-shell",
			marginInline: "auto",
			paddingInline: "academy-gutter",
			_sm: { gridTemplateColumns: "repeat(3, minmax(0, 1fr))" },
		},
		formatLink: {
			display: "grid",
			gap: "2",
			paddingBlock: "6",
			paddingInlineEnd: "5",
			borderTop: "hairline",
			borderColor: "academy.border",
			textDecoration: "none",
			color: "academy.text",
			_hover: { "& > :first-child": { color: "academy.accent" } },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
			_sm: {
				"& + &": {
					paddingInlineStart: "6",
					borderInlineStart: "hairline",
					borderColor: "academy.border",
				},
			},
		},
		formatHeading: {
			display: "flex",
			justifyContent: "space-between",
			alignItems: "center",
			fontFamily: "academy-display",
			fontSize: "2xl",
			fontWeight: "bold",
			letterSpacing: "tight",
			"& span": { fontSize: "lg", color: "academy.accent" },
		},
		section: {
			maxWidth: "academy-shell",
			marginInline: "auto",
			paddingInline: "academy-gutter",
			paddingTop: "16",
			_lg: { paddingTop: "20" },
		},
		sectionHead: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "end",
			justifyContent: "space-between",
			columnGap: "6",
			rowGap: "3",
			marginBottom: "7",
			"& > div": { display: "grid", gap: "3" },
		},
		sectionTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "academy-section",
			fontWeight: "bold",
			letterSpacing: "academy-display",
			lineHeight: "academy-title",
		},
		feedGrid: {
			display: "grid",
			gap: "8",
			_sm: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
			_lg: {
				gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
				columnGap: "7",
				rowGap: "10",
			},
		},
		card: {
			display: "flex",
			flexDirection: "column",
			minWidth: "0",
			gap: "4",
			color: "academy.text",
			textDecoration: "none",
			_hover: {
				"& h3": {
					color: "academy.accent",
					textDecoration: "underline",
					textUnderlineOffset: "0.15em",
				},
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		cardArt: {
			aspectRatio: "academy-video",
			overflow: "hidden",
			borderRadius: "academy-m",
			backgroundColor: "academy.ground",
		},
		cardImage: { width: "full", height: "full", objectFit: "cover" },
		cardBody: { display: "grid", gap: "3", alignContent: "start" },
		cardMeta: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "baseline",
			justifyContent: "space-between",
			columnGap: "3",
			rowGap: "1",
			margin: "0",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "academy-caption",
			letterSpacing: "wide",
			textTransform: "uppercase",
			"& > :first-child": { color: "academy.accent" },
		},
		cardTitle: {
			margin: "0",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "bold",
			lineHeight: "academy-card",
			letterSpacing: "tight",
			textWrap: "pretty",
		},
		cardDescription: {
			margin: "0",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "academy-reading",
			textWrap: "pretty",
		},
		pageHero: {
			paddingBlock: "10",
			borderBottom: "hairline",
			borderColor: "academy.border",
			_lg: { paddingBlock: "14" },
		},
		pageHeroGrid: {
			display: "grid",
			gap: "5",
			marginTop: "4",
			alignItems: "end",
			_lg: { gridTemplateColumns: "1fr 1fr", gap: "16" },
		},
		pageTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "academy-title",
			fontWeight: "bold",
			letterSpacing: "academy-display",
			lineHeight: "academy-display",
		},
		resultCount: { margin: "0", color: "academy.textMuted", fontSize: "sm" },
		pathList: {
			display: "grid",
			borderTop: "hairline",
			borderColor: "academy.border",
		},
		pathCard: {
			display: "grid",
			gridTemplateColumns: "2rem minmax(0, 1fr) auto",
			gap: "4",
			alignItems: "start",
			paddingBlock: "6",
			borderBottom: "hairline",
			borderColor: "academy.border",
			color: "academy.text",
			textDecoration: "none",
			_lg: {
				gridTemplateColumns: "4rem minmax(0, 1fr) auto",
				gap: "8",
				paddingBlock: "8",
			},
			_hover: { "& h3": { color: "academy.accent" } },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		pathIndex: {
			paddingTop: "1",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "sm",
		},
		pathBody: {
			display: "grid",
			gap: "2",
			maxWidth: "academy-copy",
			minWidth: "0",
		},
		pathTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "bold",
			lineHeight: "academy-card",
			letterSpacing: "tight",
			_lg: { fontSize: "2xl" },
		},
		pathMeta: {
			margin: "0",
			marginTop: "2",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
		},
		pathArrow: { color: "academy.accent", fontSize: "2xl", lineHeight: "none" },
		watchFeature: {
			display: "grid",
			gap: "6",
			alignItems: "center",
			color: "academy.text",
			textDecoration: "none",
			_lg: { gridTemplateColumns: "1.1fr 1fr", gap: "10" },
			_hover: { "& h2": { color: "academy.accent" } },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		watchTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "3xl",
			fontWeight: "bold",
			letterSpacing: "tight",
			lineHeight: "academy-title",
		},
		searchBar: {
			display: "grid",
			alignItems: "center",
			gap: "3",
			marginBottom: "8",
			"& label": { fontSize: "sm", fontWeight: "semibold" },
			_sm: { gridTemplateColumns: "auto minmax(0, 1fr) auto", gap: "5" },
		},
		input: {
			width: "full",
			minWidth: "0",
			minHeight: "12",
			paddingInline: "4",
			paddingBlock: "3",
			border: "hairline",
			borderColor: "academy.inputBorder",
			borderRadius: "academy-s",
			backgroundColor: "academy.input",
			color: "academy.text",
			fontFamily: "academy-text",
			fontSize: "md",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		empty: { paddingBlock: "10", color: "academy.textSoft" },
		more: {
			display: "grid",
			justifyItems: "center",
			gap: "3",
			marginTop: "10",
		},
		newsletter: {
			display: "grid",
			gap: "8",
			maxWidth: "academy-shell",
			marginInline: "auto",
			marginTop: "20",
			paddingInline: "academy-gutter",
			paddingBlock: "10",
			borderBlock: "hairline",
			borderColor: "academy.border",
			_lg: {
				gridTemplateColumns: "1fr 1fr",
				gap: "16",
				alignItems: "center",
				paddingBlock: "12",
			},
			"& h2": { marginBlock: "4" },
		},
		newsletterForm: {
			display: "grid",
			gap: "3",
			"& label": {
				color: "academy.text",
				fontSize: "sm",
				fontWeight: "semibold",
			},
		},
		newsletterRow: {
			display: "grid",
			gap: "3",
			_sm: { gridTemplateColumns: "minmax(0, 1fr) auto" },
		},
		finePrint: {
			margin: "0",
			color: "academy.textMuted",
			fontSize: "xs",
			lineHeight: "body",
			"& a": { color: "inherit", textUnderlineOffset: "0.2em" },
		},
	},
});
