import { sva } from "../../styled-system/css";

/** Compact supporting resources; modal and WebContainer behavior stays in Vue. */
export const academyCourseResources = sva({
	slots: [
		"root",
		"heading",
		"group",
		"category",
		"list",
		"item",
		"action",
		"details",
		"description",
		"kind",
	],
	base: {
		root: {
			display: "grid",
			gap: "5",
			minWidth: "0",
			color: "academy.text",
			fontFamily: "academy-text",
			lineHeight: "body",
		},
		heading: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "bold",
			lineHeight: "tight",
		},
		group: { display: "grid", gap: "1", minWidth: "0" },
		category: {
			margin: "0",
			color: "academy.textSoft",
			fontSize: "sm",
			fontWeight: "semibold",
		},
		list: { margin: "0", padding: "0", listStyle: "none", minWidth: "0" },
		item: {
			paddingBlock: "2",
			borderBottom: "hairline",
			borderColor: "academy.border",
			minWidth: "0",
		},
		action: {
			display: "inline-flex",
			alignItems: "center",
			minHeight: "11",
			maxWidth: "full",
			padding: "0",
			border: "academy-button",
			backgroundColor: "transparent",
			color: "academy.accent",
			fontFamily: "academy-text",
			fontSize: "sm",
			fontWeight: "semibold",
			lineHeight: "body",
			textAlign: "start",
			textDecoration: "underline",
			textUnderlineOffset: "0.2em",
			overflowWrap: "anywhere",
			cursor: "pointer",
			_hover: { color: "academy.text" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		details: { display: "grid", gap: "1", minWidth: "0" },
		description: {
			margin: "0",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "relaxed",
			overflowWrap: "anywhere",
		},
		kind: {
			margin: "0",
			color: "academy.textMuted",
			fontSize: "xs",
			lineHeight: "body",
		},
	},
});
