import { sva } from "../../styled-system/css";

/**
 * Video-detail composition for the Academy watch route.
 *
 * Playback, deferred islands, and route data remain owned by the website. This
 * recipe only supplies the responsive visual frame that keeps the player and
 * its supporting learning material on the Academy canvas.
 */
export const academyWatch = sva({
	slots: [
		"root",
		"breadcrumb",
		"crumb",
		"breadcrumbStatus",
		"hero",
		"summary",
		"summaryCopy",
		"title",
		"dek",
		"facts",
		"fact",
		"factLabel",
		"factValue",
		"factLink",
		"copyButton",
		"upcoming",
		"noticeTitle",
		"noticeCopy",
		"playerWrap",
		"playerFrame",
		"poster",
		"noscript",
		"noscriptLinks",
		"upcomingThumbnail",
		"body",
		"section",
		"sectionTitle",
		"description",
		"learn",
		"learnTitle",
		"learnList",
		"chapterList",
		"chapterLink",
		"chapterTime",
		"chapterName",
		"transcriptNote",
		"transcriptDetails",
		"transcriptSummary",
		"transcriptBody",
		"transcriptChapter",
		"transcriptChapterLink",
		"transcriptParagraph",
		"transcriptTimestamp",
		"transcriptTimestampLink",
		"transcriptRow",
		"techGrid",
		"techChip",
		"techIcon",
		"techName",
		"techArrow",
		"player",
		"playerSurface",
		"livePlayer",
		"livePlayerVideo",
		"livePlayerStatus",
		"reactions",
		"reactionList",
		"reactionButton",
		"reactionEmoji",
		"reactionCount",
		"reactionPicker",
		"emojiOption",
		"tabsRoot",
		"resourceGroups",
		"resourceGroup",
		"resourceHeading",
		"resourceList",
		"resourceLink",
		"resourceIcon",
		"resourceBody",
		"resourceTitle",
		"resourceDescription",
		"resourceExternal",
		"comments",
		"commentsTitle",
		"commentList",
		"comment",
		"commentRow",
		"commentAvatar",
		"commentAvatarFallback",
		"commentContent",
		"commentMeta",
		"commentAuthor",
		"commentDate",
		"commentBody",
		"commentCta",
		"cast",
		"castGrid",
		"castCard",
		"castAvatarWrap",
		"castAvatar",
		"castInitials",
		"castBadge",
		"castName",
		"castMeta",
		"rail",
		"railHeader",
		"railTitle",
		"railLink",
		"railGrid",
		"railCard",
		"railMedia",
		"railImage",
		"railRuntime",
		"railCardBody",
		"railCardTitle",
		"railIcon",
		"search",
		"searchInput",
		"searchIcon",
		"searchSummary",
		"transcriptContainer",
		"transcriptText",
		"transcriptSegment",
		"transcriptHighlight",
		"progress",
		"progressTrack",
		"progressFill",
		"progressLabel",
	],
	base: {
		root: {
			backgroundColor: "academy.canvas",
			color: "academy.text",
			fontFamily: "academy-text",
			"& [data-watch-player-frame]:has(media-player, video, iframe, [data-watch-upcoming-thumbnail]) [data-watch-player-poster]":
				{
					display: "none",
				},
		},
		breadcrumb: {
			maxWidth: "academy-shell",
			width: "full",
			marginInline: "auto",
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			gap: "2",
			paddingBlock: "3",
			paddingInline: "academy-gutter",
			borderBottom: "hairline",
			borderColor: "academy.border",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			letterSpacing: "wide",
		},
		crumb: {
			display: "inline-flex",
			alignItems: "center",
			minHeight: "11",
			color: "academy.textSoft",
			textDecoration: "none",
			_hover: { color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		breadcrumbStatus: { color: "academy.textMuted", marginInlineStart: "auto" },
		hero: {
			display: "grid",
			gridTemplateAreas: '"player" "summary"',
			gap: "6",
			width: "full",
			maxWidth: "academy-shell",
			marginInline: "auto",
			paddingBlock: "6",
			paddingInline: "academy-gutter",
			alignItems: "start",
			_lg: {
				gap: "8",
			},
		},
		summary: {
			gridArea: "summary",
			display: "grid",
			gap: "6",
			minWidth: "0",
			alignSelf: "start",
			_lg: { gridTemplateColumns: "minmax(0, 1fr) auto", gap: "10" },
		},
		summaryCopy: { display: "flex", flexDirection: "column", gap: "4" },
		title: {
			margin: "0",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "3xl",
			fontWeight: "extrabold",
			letterSpacing: "academy-display",
			lineHeight: "academy-title",
			textWrap: "balance",
			_lg: { fontSize: "academy-section" },
		},
		dek: {
			maxWidth: "academy-copy",
			margin: "0",
			color: "academy.textSoft",
			fontSize: "md",
			lineHeight: "body",
		},
		facts: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "start",
			gap: "6",
			margin: "0",
		},
		fact: {
			display: "grid",
			gap: "2",
		},
		factLabel: {
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "semibold",
			letterSpacing: "wide",
			lineHeight: "body",
		},
		factValue: {
			minWidth: "0",
			color: "academy.text",
			fontSize: "sm",
			lineHeight: "body",
		},
		factLink: {
			color: "academy.text",
			textDecoration: "underline",
			textUnderlineOffset: "2px",
			_hover: { color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		copyButton: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			minHeight: "11",
			paddingInline: "3",
			border: "hairline",
			borderColor: "academy.inputBorder",
			borderRadius: "academy-s",
			backgroundColor: "transparent",
			color: "academy.text",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "semibold",
			letterSpacing: "wide",
			cursor: "pointer",
			_hover: { borderColor: "academy.accent", color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		upcoming: {
			display: "flex",
			flexDirection: "column",
			gap: "3",
			paddingTop: "5",
			borderTop: "hairline",
			borderColor: "academy.border",
		},
		noticeTitle: {
			margin: "0",
			color: "academy.text",
			fontSize: "md",
			fontWeight: "bold",
			lineHeight: "tight",
		},
		noticeCopy: {
			margin: "0",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "body",
		},
		playerWrap: {
			gridArea: "player",
			isolation: "isolate",
			position: "relative",
			width: "full",
			overflow: "hidden",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			backgroundColor: "academyBase.ground",
		},
		playerFrame: {
			position: "relative",
			width: "full",
			aspectRatio: "academy-video",
			overflow: "hidden",
			backgroundColor: "academyBase.ground",
			"& > *": { position: "absolute", inset: "0" },
		},
		poster: { width: "full", height: "full", objectFit: "cover" },
		noscript: {
			display: "flex",
			flexDirection: "column",
			alignItems: "center",
			justifyContent: "center",
			gap: "2",
			padding: "6",
			backgroundColor: "academyBase.ground",
			color: "academyBase.text",
			fontSize: "sm",
			textAlign: "center",
			"& p": { margin: "0" },
			"& a": {
				color: "academyBase.text",
				textDecoration: "underline",
				textUnderlineOffset: "2px",
			},
		},
		noscriptLinks: {
			display: "flex",
			flexWrap: "wrap",
			justifyContent: "center",
			gap: "3",
		},
		upcomingThumbnail: {
			position: "absolute",
			inset: "0",
			width: "full",
			height: "full",
			objectFit: "cover",
		},
		body: {
			display: "flex",
			flexDirection: "column",
			gap: "12",
			width: "full",
			maxWidth: "academy-shell",
			marginInline: "auto",
			paddingBlock: "12",
			paddingInline: "academy-gutter",
			_lg: { gap: "16", paddingBlock: "academy-section" },
		},
		section: {
			display: "flex",
			flexDirection: "column",
			gap: "4",
			minWidth: "0",
			paddingTop: "10",
			borderTop: "hairline",
			borderColor: "academy.border",
			"&:first-of-type": { paddingTop: "0", borderTop: "none" },
		},
		sectionTitle: {
			margin: "0",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "2xl",
			fontWeight: "bold",
			letterSpacing: "tight",
			lineHeight: "tight",
			textWrap: "balance",
		},
		description: { maxWidth: "academy-copy", minWidth: "0" },
		learn: {
			display: "flex",
			flexDirection: "column",
			gap: "3",
			maxWidth: "academy-copy",
		},
		learnTitle: {
			margin: "0",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "semibold",
			letterSpacing: "wide",
		},
		learnList: {
			display: "grid",
			gap: "3",
			margin: "0",
			paddingInlineStart: "6",
			listStyle: "decimal",
			color: "academy.textSoft",
			lineHeight: "relaxed",
			"& ::marker": {
				color: "academy.accent",
				fontFamily: "academy-mono",
				fontWeight: "bold",
			},
		},
		chapterList: {
			display: "grid",
			maxWidth: "academy-copy",
			margin: "0",
			padding: "0",
			listStyle: "none",
			borderTop: "hairline",
			borderColor: "academy.border",
		},
		chapterLink: {
			display: "grid",
			gridTemplateColumns: "5rem minmax(0, 1fr)",
			gap: "3",
			alignItems: "baseline",
			paddingBlock: "3",
			borderBottom: "hairline",
			borderColor: "academy.border",
			color: "academy.text",
			textDecoration: "none",
			_hover: { color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		chapterTime: {
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "semibold",
		},
		chapterName: { color: "currentColor", fontSize: "sm", lineHeight: "body" },
		transcriptNote: {
			maxWidth: "academy-copy",
			margin: "0",
			color: "academy.textMuted",
			fontSize: "sm",
			lineHeight: "body",
		},
		transcriptDetails: {
			maxWidth: "academy-copy",
			borderTop: "hairline",
			borderColor: "academy.border",
		},
		transcriptSummary: {
			paddingBlock: "3",
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "semibold",
			letterSpacing: "wide",
			cursor: "pointer",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		transcriptBody: { paddingBlockEnd: "3" },
		transcriptChapter: {
			marginBlockStart: "6",
			marginBlockEnd: "3",
			color: "academy.text",
			fontSize: "md",
			fontWeight: "bold",
			lineHeight: "tight",
		},
		transcriptChapterLink: {
			display: "inline-flex",
			alignItems: "baseline",
			gap: "2",
			color: "academy.text",
			textDecoration: "none",
			_hover: { color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		transcriptParagraph: {
			maxWidth: "academy-copy",
			marginBlockEnd: "4",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "relaxed",
		},
		transcriptTimestamp: {
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "semibold",
		},
		transcriptTimestampLink: {
			display: "inline-flex",
			marginInlineEnd: "2",
			textDecoration: "none",
			_hover: { textDecoration: "underline", textUnderlineOffset: "2px" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		transcriptRow: {
			display: "grid",
			gridTemplateColumns: "5rem minmax(0, 1fr)",
			gap: "3",
			alignItems: "start",
			marginBlockEnd: "6",
		},
		techGrid: { display: "flex", flexWrap: "wrap", gap: "2" },
		techChip: {
			display: "inline-flex",
			alignItems: "center",
			gap: "2",
			minHeight: "11",
			paddingInline: "3",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-pill",
			backgroundColor: "academy.panel",
			color: "academy.text",
			fontSize: "sm",
			textDecoration: "none",
			_hover: { borderColor: "academy.accent", color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		techIcon: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			width: "5",
			height: "5",
			overflow: "hidden",
			"& img": { width: "full", height: "full", objectFit: "contain" },
		},
		techName: { color: "currentColor" },
		techArrow: {
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "sm",
		},
		player: { width: "full", height: "full", aspectRatio: "academy-video" },
		playerSurface: { position: "relative", width: "full", height: "full" },
		livePlayer: {
			position: "relative",
			width: "full",
			height: "full",
			backgroundColor: "academyBase.ground",
		},
		livePlayerVideo: {
			display: "block",
			width: "full",
			height: "full",
			objectFit: "contain",
			backgroundColor: "academyBase.ground",
		},
		livePlayerStatus: {
			position: "absolute",
			insetInline: "4",
			insetBlockEnd: "4",
			paddingInline: "3",
			paddingBlock: "2",
			borderRadius: "academy-s",
			backgroundColor: "academyBase.ground",
			color: "academyBase.text",
			fontSize: "sm",
			fontWeight: "bold",
		},
		reactions: {
			minWidth: "0",
		},
		reactionList: {
			position: "relative",
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			gap: "2",
		},
		reactionButton: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			gap: "2",
			minWidth: "11",
			minHeight: "11",
			paddingInline: "3",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-pill",
			backgroundColor: "academy.ground",
			color: "academy.text",
			fontFamily: "academy-text",
			fontSize: "sm",
			cursor: "pointer",
			_hover: { borderColor: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		reactionEmoji: { fontSize: "lg", lineHeight: "none" },
		reactionCount: {
			color: "currentColor",
			fontSize: "xs",
			fontWeight: "semibold",
		},
		reactionPicker: {
			display: "grid",
			gridTemplateColumns: "repeat(auto-fit, minmax(2.75rem, 1fr))",
			gap: "1",
			width: "80",
			maxWidth: "[calc(100vw - 2rem)]",
			padding: "3",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			backgroundColor: "academy.panel",
			boxShadow: "dialog",
		},
		emojiOption: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			minWidth: "0",
			minHeight: "11",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			backgroundColor: "academy.ground",
			fontSize: "lg",
			cursor: "pointer",
			_hover: {
				borderColor: "academy.accent",
				backgroundColor: "academy.canvas",
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		tabsRoot: {
			minWidth: "0",
			maxWidth: "academy-copy",
		},
		resourceGroups: { display: "grid", gap: "6" },
		resourceGroup: { display: "grid", gap: "3" },
		resourceHeading: {
			margin: "0",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "semibold",
			letterSpacing: "wide",
		},
		resourceList: { display: "grid", gap: "2" },
		resourceLink: {
			display: "grid",
			gridTemplateColumns: "auto minmax(0, 1fr) auto",
			gap: "3",
			alignItems: "start",
			padding: "3",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			backgroundColor: "academy.ground",
			color: "academy.text",
			textDecoration: "none",
			_hover: { borderColor: "academy.accent", color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		resourceIcon: {
			width: "5",
			height: "5",
			marginBlockStart: "1",
			color: "academy.textMuted",
		},
		resourceBody: { minWidth: "0" },
		resourceTitle: {
			color: "currentColor",
			fontSize: "sm",
			fontWeight: "semibold",
		},
		resourceDescription: {
			marginBlockStart: "1",
			color: "academy.textMuted",
			fontSize: "xs",
			lineHeight: "body",
		},
		resourceExternal: {
			width: "4",
			height: "4",
			marginBlockStart: "1",
			color: "academy.textMuted",
		},
		comments: { display: "flex", flexDirection: "column", gap: "4" },
		commentsTitle: {
			margin: "0",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "bold",
			lineHeight: "tight",
		},
		commentList: { display: "grid", gap: "3" },
		comment: {
			padding: "4",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			backgroundColor: "academy.panel",
		},
		commentRow: { display: "flex", alignItems: "flex-start", gap: "3" },
		commentAvatar: {
			width: "8",
			height: "8",
			borderRadius: "full",
			objectFit: "cover",
			flexShrink: "0",
			border: "hairline",
			borderColor: "academy.border",
		},
		commentAvatarFallback: {
			display: "grid",
			placeItems: "center",
			width: "8",
			height: "8",
			flexShrink: "0",
			borderRadius: "full",
			backgroundColor: "academy.accent",
			color: "academy.accentForeground",
			fontFamily: "academy-display",
			fontSize: "sm",
			fontWeight: "bold",
		},
		commentContent: { minWidth: "0", flex: "1" },
		commentMeta: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			gap: "2",
			marginBlockEnd: "1",
		},
		commentAuthor: {
			margin: "0",
			color: "academy.text",
			fontSize: "sm",
			fontWeight: "semibold",
		},
		commentDate: {
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
		},
		commentBody: {
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "relaxed",
			"& a": { color: "academy.accent", textDecoration: "underline" },
			"& code": {
				paddingInline: "1",
				borderRadius: "academy-s",
				backgroundColor: "academy.ground",
				color: "academy.text",
			},
		},
		commentCta: {
			display: "inline-flex",
			alignItems: "center",
			gap: "1",
			alignSelf: "center",
			color: "academy.accent",
			fontSize: "sm",
			fontWeight: "semibold",
			textDecoration: "none",
			"& svg": { width: "4", height: "4" },
			_hover: { textDecoration: "underline" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		cast: {
			display: "flex",
			flexDirection: "column",
			gap: "4",
			paddingTop: "10",
			borderTop: "hairline",
			borderColor: "academy.border",
		},
		castGrid: {
			display: "grid",
			gridTemplateColumns: "minmax(0, 1fr)",
			gap: "3",
			_sm: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
			_lg: { gridTemplateColumns: "repeat(4, minmax(0, 1fr))" },
		},
		castCard: {
			display: "flex",
			alignItems: "center",
			gap: "3",
			minWidth: "0",
			padding: "3",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			backgroundColor: "academy.panel",
			color: "academy.text",
			textDecoration: "none",
			_hover: { borderColor: "academy.accent", color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		castAvatarWrap: { position: "relative", flexShrink: "0" },
		castAvatar: {
			width: "12",
			height: "12",
			flexShrink: "0",
			borderRadius: "full",
			objectFit: "cover",
			border: "hairline",
			borderColor: "academy.border",
		},
		castInitials: {
			display: "grid",
			placeItems: "center",
			background: "academy.ground",
			color: "academy.textSoft",
			fontFamily: "academy-text",
			fontSize: "sm",
			fontWeight: "semibold",
			"&[hidden]": { display: "none" },
		},
		castBadge: {
			position: "absolute",
			insetBlockEnd: "-1",
			insetInlineEnd: "-1",
			paddingInline: "1",
			paddingBlock: "1",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-pill",
			backgroundColor: "academy.accent",
			color: "academy.accentForeground",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "bold",
			letterSpacing: "wide",
		},
		castName: {
			margin: "0",
			color: "currentColor",
			fontSize: "sm",
			fontWeight: "semibold",
			overflowWrap: "anywhere",
			lineHeight: "body",
		},
		castMeta: {
			margin: "0",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			overflowWrap: "anywhere",
			lineHeight: "body",
		},
		rail: {
			display: "flex",
			flexDirection: "column",
			gap: "4",
			paddingTop: "10",
			borderTop: "hairline",
			borderColor: "academy.border",
		},
		railHeader: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "baseline",
			justifyContent: "space-between",
			gap: "3",
		},
		railTitle: {
			margin: "0",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "bold",
			lineHeight: "tight",
		},
		railLink: {
			display: "inline-flex",
			alignItems: "center",
			gap: "1",
			color: "academy.accent",
			fontSize: "sm",
			fontWeight: "semibold",
			textDecoration: "none",
			_hover: { textDecoration: "underline" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		railGrid: {
			display: "grid",
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
			gap: "3",
			_lg: { gridTemplateColumns: "repeat(3, minmax(0, 1fr))" },
		},
		railCard: {
			display: "flex",
			flexDirection: "column",
			minWidth: "0",
			overflow: "hidden",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			backgroundColor: "academy.panel",
			color: "academy.text",
			textDecoration: "none",
			_hover: { borderColor: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		railMedia: {
			position: "relative",
			aspectRatio: "academy-video",
			overflow: "hidden",
			backgroundColor: "academy.ground",
		},
		railImage: { width: "full", height: "full", objectFit: "cover" },
		railRuntime: {
			position: "absolute",
			insetBlockEnd: "2",
			insetInlineEnd: "2",
			paddingInline: "2",
			paddingBlock: "1",
			borderRadius: "academy-s",
			backgroundColor: "academyBase.ground",
			color: "academyBase.text",
			fontFamily: "academy-mono",
			fontSize: "xs",
		},
		railCardBody: { padding: "3" },
		railCardTitle: {
			margin: "0",
			color: "academy.text",
			fontSize: "sm",
			fontWeight: "semibold",
			lineHeight: "body",
			"&:hover": { color: "academy.accent" },
		},
		railIcon: { width: "4", height: "4" },
		search: { position: "relative" },
		searchInput: {
			width: "full",
			minHeight: "11",
			paddingInlineStart: "10",
			paddingInlineEnd: "3",
			paddingBlock: "2",
			border: "hairline",
			borderColor: "academy.inputBorder",
			borderRadius: "academy-s",
			backgroundColor: "academy.input",
			color: "academy.text",
			fontFamily: "academy-text",
			fontSize: "sm",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		searchIcon: {
			position: "absolute",
			insetInlineStart: "3",
			insetBlockStart: "3",
			width: "5",
			height: "5",
			color: "academy.textMuted",
			pointerEvents: "none",
		},
		searchSummary: {
			marginBlockStart: "2",
			color: "academy.textMuted",
			fontSize: "sm",
		},
		transcriptContainer: {
			maxHeight: "academy-transcript",
			overflowY: "auto",
			paddingInlineEnd: "2",
		},
		transcriptText: { color: "academy.text", lineHeight: "relaxed" },
		transcriptSegment: { color: "currentColor" },
		transcriptHighlight: {
			paddingInline: "0.5",
			borderRadius: "academy-s",
			backgroundColor: "academy.accent",
			color: "academy.accentForeground",
		},
		progress: {
			position: "relative",
			display: "grid",
			gap: "1",
			width: "full",
			minWidth: "0",
		},
		progressTrack: {
			height: "1",
			width: "full",
			overflow: "hidden",
			borderRadius: "academy-pill",
			backgroundColor: "academy.segmentOff",
		},
		progressFill: {
			height: "full",
			backgroundColor: "academy.statusSky",
			transitionProperty: "[width]",
			transitionDuration: "fast",
			_motionReduce: { transitionDuration: "none" },
		},
		progressLabel: {
			gridRow: "1",
			justifySelf: "end",
			paddingInline: "2",
			paddingBlock: "1",
			borderRadius: "academy-s",
			backgroundColor: "academy.panel",
			color: "academy.textSoft",
			fontFamily: "academy-mono",
			fontSize: "xs",
			lineHeight: "body",
			fontVariantNumeric: "tabular-nums",
		},
	},
	variants: {
		progressVariant: {
			default: {},
			subtle: { progressFill: { backgroundColor: "academy.textMuted" } },
			accent: { progressFill: { backgroundColor: "academy.accent" } },
		},
		progressHeight: {
			sm: {},
			md: { progressTrack: { height: "1.5" } },
			lg: { progressTrack: { height: "2" } },
		},
		progressOverlay: {
			true: {
				progress: {
					position: "absolute",
					insetBlockEnd: "0",
					insetInline: "0",
					overflow: "hidden",
					borderEndStartRadius: "inherit",
					borderEndEndRadius: "inherit",
				},
				progressTrack: {
					borderRadius: "[0]",
					backgroundColor: "academyBase.border",
				},
				progressLabel: {
					backgroundColor: "academyBase.ground",
					color: "academyBase.text",
				},
			},
			false: {},
		},
		progressComplete: {
			true: { progressFill: { backgroundColor: "academy.statusSpruce" } },
			false: {},
		},
		pressed: {
			true: {
				reactionButton: {
					borderColor: "academy.accent",
					backgroundColor: "academy.accent",
					color: "academy.accentForeground",
				},
			},
			false: {},
		},
	},
	defaultVariants: {
		pressed: false,
	},
});
