import { sva } from "../../styled-system/css";

/** Shared acquisition fields, feedback, badges, and native simulator controls. */
export const academyForms = sva({
	slots: [
		"root",
		"section",
		"split",
		"panel",
		"stack",
		"form",
		"field",
		"row",
		"title",
		"heading",
		"copy",
		"kicker",
		"label",
		"input",
		"textarea",
		"button",
		"consent",
		"courseConsent",
		"checkbox",
		"notice",
		"error",
		"fieldError",
		"status",
		"hidden",
		"badge",
		"simulator",
		"toolbar",
		"toggle",
		"simulatorGrid",
		"controls",
		"sliderGroup",
		"sliderMeta",
		"range",
		"mono",
		"muted",
		"terminal",
		"terminalBlock",
		"terminalLine",
		"command",
	],
	base: {
		root: {
			minWidth: "0",
			color: "academy.text",
			fontFamily: "academy-text",
			lineHeight: "body",
		},
		section: {
			marginBlockStart: "12",
			padding: "6",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			backgroundColor: "academy.ground",
			_lg: { padding: "8" },
		},
		split: {
			display: "grid",
			gap: "8",
			minWidth: "0",
			_lg: {
				gridTemplateColumns: "minmax(0, .9fr) minmax(0, 1fr)",
				alignItems: "start",
			},
		},
		panel: {
			display: "grid",
			gap: "4",
			minWidth: "0",
			padding: "6",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			backgroundColor: "academy.panel",
		},
		stack: { display: "grid", gap: "4", minWidth: "0" },
		form: { display: "grid", gap: "4", minWidth: "0", width: "full" },
		field: { display: "grid", gap: "2", minWidth: "0", width: "full" },
		row: {
			display: "grid",
			gap: "4",
			minWidth: "0",
			_sm: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
		},
		title: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "3xl",
			fontWeight: "bold",
			lineHeight: "tight",
			textWrap: "balance",
		},
		heading: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "bold",
			lineHeight: "tight",
		},
		copy: {
			margin: "0",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "relaxed",
			overflowWrap: "anywhere",
		},
		kicker: {
			margin: "0",
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "semibold",
			letterSpacing: "wide",
		},
		label: {
			color: "academy.textSoft",
			fontSize: "sm",
			fontWeight: "semibold",
			"& em": {
				fontStyle: "normal",
				fontWeight: "normal",
				color: "academy.textMuted",
			},
		},
		input: {
			width: "full",
			minWidth: "0",
			minHeight: "11",
			paddingInline: "3",
			paddingBlock: "3",
			border: "hairline",
			borderColor: "academy.inputBorder",
			borderRadius: "academy-s",
			backgroundColor: "academy.input",
			color: "academy.text",
			fontFamily: "academy-text",
			fontSize: "md",
			lineHeight: "body",
			_placeholder: { color: "academy.textMuted", opacity: "1" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
			_disabled: { opacity: "0.6", cursor: "not-allowed" },
			"&:is([aria-invalid='true'], :user-invalid)": {
				borderColor: "academy.statusRust",
			},
		},
		textarea: { resize: "vertical", minHeight: "24" },
		button: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			gap: "2",
			width: "full",
			minHeight: "11",
			paddingInline: "4",
			paddingBlock: "3",
			border: "academy-button",
			borderRadius: "academy-s",
			backgroundColor: "academy.accent",
			color: "academy.accentForeground",
			fontFamily: "academy-text",
			fontSize: "sm",
			fontWeight: "bold",
			cursor: "pointer",
			_hover: { opacity: "0.9" },
			_disabled: { opacity: "0.6", cursor: "not-allowed" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		courseConsent: {
			display: "flex",
			alignItems: "start",
			gap: "3",
			"& > label": {
				minHeight: "11",
				minWidth: "0",
				flex: "1",
				cursor: "pointer",
			},
		},
		consent: {
			display: "flex",
			alignItems: "start",
			gap: "3",
			padding: "3",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			backgroundColor: "academy.ground",
		},
		checkbox: {
			width: "5",
			height: "5",
			flexShrink: "0",
			marginBlockStart: "0.5",
			accentColor: "academy.accent",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
			_disabled: { cursor: "not-allowed" },
		},
		notice: {
			margin: "0",
			padding: "3",
			borderRadius: "academy-s",
			backgroundColor: "academy.ground",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "body",
		},
		error: {
			margin: "0",
			padding: "3",
			border: "hairline",
			borderColor: "academy.statusRust",
			borderRadius: "academy-s",
			backgroundColor: "academy.panel",
			color: "academy.statusRust",
			fontSize: "sm",
			lineHeight: "body",
		},
		fieldError: {
			margin: "0",
			color: "academy.statusRust",
			fontSize: "sm",
			lineHeight: "body",
		},
		status: {
			display: "grid",
			gap: "3",
			paddingBlock: "4",
			color: "academy.text",
		},
		hidden: { srOnly: true },
		badge: {
			display: "inline-flex",
			alignItems: "center",
			maxWidth: "full",
			border: "hairline",
			borderColor: "currentColor",
			backgroundColor: "academy.ground",
			color: "academy.textSoft",
			fontFamily: "academy-text",
			fontWeight: "semibold",
			lineHeight: "body",
		},
		simulator: {
			marginBlock: "8",
			overflow: "hidden",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			backgroundColor: "academy.panel",
		},
		toolbar: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			gap: "2",
			padding: "4",
			borderBottom: "hairline",
			borderColor: "academy.border",
			backgroundColor: "academy.ground",
		},
		toggle: {
			minHeight: "11",
			paddingInline: "4",
			border: "hairline",
			borderColor: "academy.inputBorder",
			borderRadius: "academy-s",
			backgroundColor: "academy.panel",
			color: "academy.text",
			fontFamily: "academy-text",
			fontSize: "sm",
			cursor: "pointer",
			"&[aria-pressed=true]": {
				backgroundColor: "academy.accent",
				color: "academy.accentForeground",
				borderColor: "academy.accent",
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		simulatorGrid: {
			display: "grid",
			minWidth: "0",
			_lg: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
		},
		controls: { display: "grid", gap: "5", minWidth: "0", padding: "5" },
		sliderGroup: { display: "grid", gap: "2", minWidth: "0" },
		sliderMeta: {
			display: "flex",
			flexWrap: "wrap",
			justifyContent: "space-between",
			alignItems: "baseline",
			gap: "2",
			minWidth: "0",
		},
		range: {
			width: "full",
			minWidth: "0",
			height: "11",
			margin: "0",
			cursor: "pointer",
			accentColor: "academy.accent",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		mono: {
			color: "academy.text",
			fontFamily: "academy-mono",
			fontSize: "xs",
			overflowWrap: "anywhere",
		},
		muted: {
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			overflowWrap: "anywhere",
		},
		terminal: {
			minWidth: "0",
			padding: "5",
			borderTop: "hairline",
			borderColor: "academy.border",
			backgroundColor: "academy.ground",
			color: "academy.text",
			fontFamily: "academy-mono",
			fontSize: "sm",
			lineHeight: "relaxed",
			overflowWrap: "anywhere",
			_lg: {
				borderTopWidth: "0",
				borderInlineStart: "hairline",
				borderColor: "academy.border",
			},
		},
		terminalBlock: { marginBlockEnd: "3", _last: { marginBlockEnd: "0" } },
		terminalLine: { lineHeight: "relaxed" },
		command: { color: "academy.accent" },
	},
	variants: {
		resourceTone: {
			default: {},
			cpu: {
				mono: { color: "academy.statusRust" },
				range: { accentColor: "academy.statusRust" },
				terminalLine: { color: "academy.statusRust" },
			},
			memory: {
				mono: { color: "academy.statusAmber" },
				range: { accentColor: "academy.statusAmber" },
				terminalLine: { color: "academy.statusAmber" },
			},
			io: {
				mono: { color: "academy.statusSpruce" },
				range: { accentColor: "academy.statusSpruce" },
				terminalLine: { color: "academy.statusSpruce" },
			},
		},
		badgeTone: {
			default: {},
			primary: { badge: { color: "academy.accent" } },
			secondary: { badge: { color: "academy.statusViolet" } },
			success: { badge: { color: "academy.statusSpruce" } },
			warning: { badge: { color: "academy.statusAmber" } },
			danger: { badge: { color: "academy.statusRust" } },
			info: { badge: { color: "academy.statusSky" } },
		},
		badgeSize: {
			xs: {
				badge: { paddingInline: "2", paddingBlock: "0.5", fontSize: "xs" },
			},
			sm: {
				badge: { paddingInline: "2.5", paddingBlock: "0.5", fontSize: "sm" },
			},
			md: { badge: { paddingInline: "3", paddingBlock: "1", fontSize: "sm" } },
			lg: {
				badge: { paddingInline: "4", paddingBlock: "1.5", fontSize: "md" },
			},
		},
		badgeRounded: {
			none: { badge: { borderRadius: "initial" } },
			sm: { badge: { borderRadius: "academy-s" } },
			md: { badge: { borderRadius: "academy-m" } },
			lg: { badge: { borderRadius: "academy-l" } },
			full: { badge: { borderRadius: "academy-pill" } },
		},
		outline: { true: { badge: { backgroundColor: "transparent" } }, false: {} },
	},
	defaultVariants: {
		badgeTone: "default",
		badgeSize: "md",
		badgeRounded: "full",
		outline: false,
	},
});
