import { sva } from "../../styled-system/css";

/**
 * The Academy front door, video library, and learning-path directory.
 *
 * The homepage opens on an ink surface (navy in light mode, a raised panel in
 * dark mode) that holds the latest session, then hands over to the canvas for
 * the chronological ledger and the learning paths. Motion is a single
 * entrance sequence on the hero; everything else moves only on interaction.
 */
export const academyPage = sva({
	slots: [
		"root",
		"container",
		"hero",
		"heroGrid",
		"heroCopy",
		"featureCopy",
		"kicker",
		"title",
		"titleLine",
		"titleAccent",
		"lede",
		"heroLede",
		"actions",
		"buttonPrimary",
		"buttonSecondary",
		"buttonGhost",
		"textLink",
		"featureCard",
		"featureArt",
		"featureImage",
		"featureRuntime",
		"featureCaption",
		"featureKicker",
		"featureTitle",
		"play",
		"archive",
		"archiveLink",
		"archiveNote",
		"section",
		"sectionHead",
		"sectionTitle",
		"sectionLede",
		"ledger",
		"ledgerRow",
		"ledgerDate",
		"ledgerMedia",
		"ledgerImage",
		"ledgerBody",
		"ledgerKind",
		"ledgerTitle",
		"ledgerDescription",
		"feedGrid",
		"card",
		"cardArt",
		"cardImage",
		"cardRuntime",
		"cardBody",
		"cardMeta",
		"cardTitle",
		"cardDescription",
		"pageHero",
		"pageHeroGrid",
		"pageTitle",
		"resultCount",
		"pathList",
		"pathCard",
		"pathIndex",
		"pathBody",
		"pathTitle",
		"pathMeta",
		"pathLevel",
		"pathLevelBar",
		"pathArrow",
		"watchFeature",
		"watchTitle",
		"searchBar",
		"input",
		"empty",
		"more",
		"newsletter",
		"newsletterCopy",
		"newsletterForm",
		"newsletterRow",
		"finePrint",
	],
	base: {
		root: {
			backgroundColor: "academy.canvas",
			color: "academy.text",
			fontFamily: "academy-text",
			paddingBottom: "16",
			minWidth: "0",
		},
		container: {
			maxWidth: "academy-shell",
			marginInline: "auto",
			paddingInline: "academy-gutter",
			width: "full",
		},
		hero: {
			position: "relative",
			overflow: "hidden",
			backgroundColor: "academy.ink",
			color: "academy.inkText",
			paddingBlockStart: "academy-hero-tight",
			paddingBlockEnd: "0",
			borderBottom: "hairline",
			borderColor: "academy.inkBorder",
			_lg: { paddingBlockStart: "academy-hero" },
		},
		heroGrid: {
			display: "grid",
			gap: "10",
			alignItems: "center",
			_lg: {
				gridTemplateColumns: "minmax(0, 1.05fr) minmax(0, 1fr)",
				gap: "16",
			},
		},
		heroCopy: {
			display: "grid",
			gap: "6",
			minWidth: "0",
			maxWidth: "academy-hero-copy",
			alignContent: "center",
		},
		featureCopy: {
			display: "grid",
			gap: "4",
			minWidth: "0",
			alignContent: "center",
		},
		kicker: {
			margin: "0",
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "sm",
			fontWeight: "medium",
		},
		title: {
			margin: "0",
			color: "academy.inkText",
			fontFamily: "academy-display",
			fontSize: "academy-display",
			fontWeight: "extrabold",
			letterSpacing: "academy-display",
			lineHeight: "academy-display",
			textWrap: "balance",
		},
		titleLine: {
			display: "block",
			animation: "academy-rise",
			"&:nth-child(2)": { animationDelay: "stagger-1" },
			_motionReduce: { animation: "none" },
		},
		titleAccent: { color: "academy.inkAccent" },
		lede: {
			margin: "0",
			maxWidth: "academy-lede",
			color: "academy.textSoft",
			fontSize: "academy-lede",
			lineHeight: "academy-reading",
			textWrap: "pretty",
		},
		heroLede: {
			margin: "0",
			maxWidth: "academy-lede",
			color: "academy.inkTextSoft",
			fontSize: "academy-lede",
			lineHeight: "academy-reading",
			textWrap: "pretty",
			animation: "academy-rise",
			animationDelay: "stagger-2",
			_motionReduce: { animation: "none" },
		},
		actions: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			gap: "4",
			marginTop: "2",
			animation: "academy-rise",
			animationDelay: "stagger-3",
			_motionReduce: { animation: "none" },
		},
		buttonPrimary: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			gap: "3",
			minHeight: "12",
			paddingInline: "5",
			paddingBlock: "3",
			border: "academy-button",
			borderRadius: "academy-s",
			backgroundColor: "academy.accent",
			color: "academy.accentForeground",
			fontFamily: "academy-text",
			fontSize: "sm",
			fontWeight: "bold",
			lineHeight: "academy-card",
			textDecoration: "none",
			cursor: "pointer",
			transitionProperty: "common",
			transitionDuration: "base",
			transitionTimingFunction: "academy-out",
			"& > span": {
				transitionProperty: "[transform]",
				transitionDuration: "base",
				transitionTimingFunction: "academy-out",
			},
			_hover: { "& > span": { transform: "translateX(0.2em)" } },
			_active: { transform: "translateY(1px)" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
			_motionReduce: {
				transitionDuration: "none",
				"& > span": { transitionDuration: "none" },
			},
		},
		buttonSecondary: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			gap: "3",
			minHeight: "12",
			paddingInline: "5",
			paddingBlock: "3",
			border: "hairline",
			borderColor: "academy.inputBorder",
			borderRadius: "academy-s",
			backgroundColor: "academy.panel",
			color: "academy.text",
			fontWeight: "semibold",
			textDecoration: "none",
			cursor: "pointer",
			transitionProperty: "colors",
			transitionDuration: "base",
			_hover: { borderColor: "academy.accent", color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
			_motionReduce: { transitionDuration: "none" },
		},
		buttonGhost: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			gap: "3",
			minHeight: "12",
			paddingInline: "5",
			paddingBlock: "3",
			border: "hairline",
			borderColor: "academy.inkBorder",
			borderRadius: "academy-s",
			backgroundColor: "transparent",
			color: "academy.inkText",
			fontSize: "sm",
			fontWeight: "semibold",
			textDecoration: "none",
			transitionProperty: "colors",
			transitionDuration: "base",
			_hover: {
				borderColor: "academy.inkText",
				backgroundColor: "academy.inkRaised",
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.inkAccent",
				outlineOffset: "focus",
			},
			_motionReduce: { transitionDuration: "none" },
		},
		textLink: {
			display: "inline-flex",
			alignItems: "center",
			gap: "2",
			width: "fit-content",
			minHeight: "11",
			color: "academy.text",
			fontSize: "sm",
			fontWeight: "semibold",
			textDecoration: "none",
			"& > span": {
				transitionProperty: "[transform]",
				transitionDuration: "base",
				transitionTimingFunction: "academy-out",
			},
			_hover: {
				color: "academy.accent",
				textDecoration: "underline",
				textUnderlineOffset: "0.2em",
				"& > span": { transform: "translateX(0.2em)" },
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
			_motionReduce: { "& > span": { transitionDuration: "none" } },
		},
		featureCard: {
			display: "grid",
			gap: "4",
			minWidth: "0",
			color: "academy.inkText",
			textDecoration: "none",
			animation: "academy-fade",
			animationDelay: "stagger-2",
			_hover: {
				"& img": { transform: "scale(1.03)" },
				"& [data-play]": { transform: "scale(1.08)" },
				"& h2": { color: "academy.inkAccent" },
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.inkAccent",
				outlineOffset: "focus",
			},
			_motionReduce: { animation: "none" },
		},
		featureArt: {
			position: "relative",
			display: "block",
			aspectRatio: "academy-video",
			overflow: "hidden",
			backgroundColor: "academy.inkRaised",
			borderRadius: "academy-m",
			border: "hairline",
			borderColor: "academy.inkBorder",
		},
		featureImage: {
			display: "block",
			width: "full",
			height: "full",
			objectFit: "cover",
			transitionProperty: "[transform]",
			transitionDuration: "reveal",
			transitionTimingFunction: "academy-out",
			_motionReduce: { transitionDuration: "none" },
		},
		featureRuntime: {
			position: "absolute",
			insetBlockEnd: "3",
			insetInlineEnd: "3",
			paddingInline: "2",
			paddingBlock: "1",
			borderRadius: "academy-s",
			backgroundColor: "academy.ink",
			color: "academy.inkText",
			fontFamily: "academy-mono",
			fontSize: "xs",
			lineHeight: "body",
		},
		featureCaption: { display: "grid", gap: "1" },
		featureKicker: {
			margin: "0",
			color: "academy.inkTextMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
		},
		featureTitle: {
			margin: "0",
			color: "academy.inkText",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "bold",
			lineHeight: "tight",
			letterSpacing: "academy-tight",
			transitionProperty: "colors",
			transitionDuration: "base",
			textWrap: "balance",
		},
		play: {
			position: "absolute",
			insetBlockStart: "[50%]",
			insetInlineStart: "[50%]",
			display: "grid",
			placeItems: "center",
			width: "16",
			height: "16",
			marginBlockStart: "-8",
			marginInlineStart: "-8",
			borderRadius: "full",
			backgroundColor: "academy.inkAccent",
			color: "academy.inkAccentForeground",
			transitionProperty: "[transform]",
			transitionDuration: "slow",
			transitionTimingFunction: "academy-out",
			"& svg": { width: "6", height: "6", marginInlineStart: "0.5" },
			_motionReduce: { transitionDuration: "none" },
		},
		archive: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			columnGap: "8",
			rowGap: "3",
			marginTop: "12",
			paddingBlock: "5",
			borderTop: "hairline",
			borderColor: "academy.inkBorder",
			color: "academy.inkTextSoft",
			fontSize: "sm",
			animation: "academy-fade",
			animationDelay: "stagger-4",
			_lg: { marginTop: "16" },
			"& > :last-child": { _lg: { marginInlineStart: "auto" } },
			_motionReduce: { animation: "none" },
		},
		archiveLink: {
			display: "inline-flex",
			alignItems: "baseline",
			gap: "2",
			minHeight: "11",
			color: "academy.inkTextSoft",
			textDecoration: "none",
			"& strong": {
				color: "academy.inkText",
				fontFamily: "academy-mono",
				fontSize: "md",
				fontWeight: "semibold",
			},
			_hover: {
				color: "academy.inkText",
				textDecoration: "underline",
				textUnderlineOffset: "0.25em",
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.inkAccent",
				outlineOffset: "focus",
			},
		},
		archiveNote: { color: "academy.inkTextMuted" },
		section: {
			maxWidth: "academy-shell",
			marginInline: "auto",
			paddingInline: "academy-gutter",
			paddingTop: "16",
			_lg: { paddingTop: "24" },
		},
		sectionHead: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "end",
			justifyContent: "space-between",
			columnGap: "6",
			rowGap: "3",
			marginBottom: "8",
			"& > div": { display: "grid", gap: "3" },
		},
		sectionTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "academy-section",
			fontWeight: "bold",
			letterSpacing: "academy-display",
			lineHeight: "academy-title",
			textWrap: "balance",
		},
		sectionLede: {
			margin: "0",
			maxWidth: "academy-lede",
			color: "academy.textSoft",
			fontSize: "md",
			lineHeight: "academy-reading",
		},
		ledger: {
			display: "grid",
			borderTop: "hairline",
			borderColor: "academy.border",
		},
		ledgerRow: {
			display: "grid",
			gridTemplateColumns: "5.5rem minmax(0, 1fr)",
			columnGap: "4",
			rowGap: "3",
			alignItems: "start",
			paddingBlock: "5",
			borderBottom: "hairline",
			borderColor: "academy.border",
			color: "academy.text",
			textDecoration: "none",
			"&[data-media='false']": {
				gridTemplateColumns: "minmax(0, 1fr)",
				_lg: { gridTemplateColumns: "6.5rem minmax(0, 1fr)" },
			},
			"&[data-media='false'] > :nth-child(2)": { _lg: { gridColumn: "2" } },
			_lg: {
				gridTemplateColumns: "6.5rem 11rem minmax(0, 1fr)",
				columnGap: "8",
				paddingBlock: "6",
			},
			_hover: {
				"& h3": { color: "academy.accent" },
				"& img": { transform: "scale(1.03)" },
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		ledgerDate: {
			gridColumn: "1 / -1",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			lineHeight: "body",
			paddingBlockStart: "1",
			_lg: { gridColumn: "1", fontSize: "sm" },
		},
		ledgerMedia: {
			display: "block",
			overflow: "hidden",
			aspectRatio: "academy-video",
			borderRadius: "academy-s",
			backgroundColor: "academy.ground",
		},
		ledgerImage: {
			width: "full",
			height: "full",
			objectFit: "cover",
			transitionProperty: "[transform]",
			transitionDuration: "reveal",
			transitionTimingFunction: "academy-out",
			_motionReduce: { transitionDuration: "none" },
		},
		ledgerBody: { display: "grid", gap: "2", minWidth: "0" },
		ledgerKind: {
			display: "inline-flex",
			alignItems: "center",
			gap: "2",
			margin: "0",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			lineHeight: "body",
			"&::before": {
				content: '""',
				display: "inline-block",
				width: "2",
				height: "2",
				borderRadius: "full",
				backgroundColor: "academy.textMuted",
			},
			"&[data-kind='Video']::before": { backgroundColor: "academy.accent" },
			"&[data-kind='Article']::before": {
				backgroundColor: "academy.statusSky",
			},
			"&[data-kind='News']::before": { backgroundColor: "academy.statusAmber" },
			"&[data-kind='Course']::before": {
				backgroundColor: "academy.statusSpruce",
			},
			"&[data-kind='Learning path']::before": {
				backgroundColor: "academy.statusViolet",
			},
		},
		ledgerTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "lg",
			fontWeight: "bold",
			lineHeight: "tight",
			letterSpacing: "academy-tight",
			textWrap: "pretty",
			transitionProperty: "colors",
			transitionDuration: "base",
			_lg: { fontSize: "2xl" },
		},
		ledgerDescription: {
			margin: "0",
			maxWidth: "academy-copy",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "academy-reading",
			textWrap: "pretty",
		},
		feedGrid: {
			display: "grid",
			gap: "8",
			_sm: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
			_lg: {
				gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
				columnGap: "7",
				rowGap: "10",
			},
		},
		card: {
			display: "flex",
			flexDirection: "column",
			minWidth: "0",
			gap: "3",
			color: "academy.text",
			textDecoration: "none",
			_hover: {
				"& h3": { color: "academy.accent" },
				"& img": { transform: "scale(1.03)" },
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		cardArt: {
			position: "relative",
			aspectRatio: "academy-video",
			overflow: "hidden",
			borderRadius: "academy-m",
			backgroundColor: "academy.ground",
		},
		cardImage: {
			width: "full",
			height: "full",
			objectFit: "cover",
			transitionProperty: "[transform]",
			transitionDuration: "reveal",
			transitionTimingFunction: "academy-out",
			_motionReduce: { transitionDuration: "none" },
		},
		cardRuntime: {
			position: "absolute",
			insetBlockEnd: "2",
			insetInlineEnd: "2",
			paddingInline: "2",
			paddingBlock: "0.5",
			borderRadius: "academy-s",
			backgroundColor: "academy.ink",
			color: "academy.inkText",
			fontFamily: "academy-mono",
			fontSize: "xs",
			lineHeight: "body",
		},
		cardBody: { display: "grid", gap: "2", alignContent: "start" },
		cardMeta: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "baseline",
			justifyContent: "space-between",
			columnGap: "3",
			rowGap: "1",
			margin: "0",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			lineHeight: "body",
		},
		cardTitle: {
			margin: "0",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "lg",
			fontWeight: "bold",
			lineHeight: "academy-card",
			letterSpacing: "academy-tight",
			textWrap: "pretty",
			transitionProperty: "colors",
			transitionDuration: "base",
		},
		cardDescription: {
			margin: "0",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "academy-reading",
			textWrap: "pretty",
		},
		pageHero: {
			paddingBlock: "10",
			borderBottom: "hairline",
			borderColor: "academy.border",
			_lg: { paddingBlock: "14" },
		},
		pageHeroGrid: {
			display: "grid",
			gap: "5",
			alignItems: "end",
			_lg: { gridTemplateColumns: "1fr 1fr", gap: "16" },
		},
		pageTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "academy-title",
			fontWeight: "extrabold",
			letterSpacing: "academy-display",
			lineHeight: "academy-display",
		},
		resultCount: { margin: "0", color: "academy.textMuted", fontSize: "sm" },
		pathList: {
			display: "grid",
			borderTop: "hairline",
			borderColor: "academy.border",
		},
		pathCard: {
			display: "grid",
			gridTemplateColumns: "minmax(0, 1fr) auto",
			gap: "4",
			alignItems: "start",
			paddingBlock: "6",
			borderBottom: "hairline",
			borderColor: "academy.border",
			color: "academy.text",
			textDecoration: "none",
			_lg: {
				gridTemplateColumns: "6.5rem minmax(0, 1fr) auto",
				gap: "8",
				paddingBlock: "8",
			},
			_hover: {
				"& :is(h2, h3)": { color: "academy.accent" },
				"& [data-arrow]": { transform: "translate(0.15em, -0.15em)" },
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		pathIndex: {
			display: "none",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "sm",
			lineHeight: "body",
			paddingBlockStart: "1.5",
			_lg: { display: "block" },
		},
		pathBody: {
			display: "grid",
			gap: "2",
			maxWidth: "academy-copy",
			minWidth: "0",
		},
		pathTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "bold",
			lineHeight: "academy-card",
			letterSpacing: "academy-tight",
			transitionProperty: "colors",
			transitionDuration: "base",
			_lg: { fontSize: "2xl" },
		},
		pathMeta: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			gap: "3",
			margin: "0",
			marginTop: "2",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			lineHeight: "body",
		},
		pathLevel: {
			display: "inline-flex",
			alignItems: "flex-end",
			gap: "0.5",
			height: "3",
			marginInlineEnd: "1",
		},
		pathLevelBar: {
			display: "block",
			width: "1",
			height: "full",
			borderRadius: "xs",
			backgroundColor: "academy.segmentOff",
			"&:nth-child(1)": { height: "1.5" },
			"&:nth-child(2)": { height: "2.5" },
			"&[data-on='true']": { backgroundColor: "academy.accent" },
		},
		pathArrow: {
			display: "inline-block",
			color: "academy.accent",
			fontSize: "2xl",
			lineHeight: "none",
			transitionProperty: "[transform]",
			transitionDuration: "base",
			transitionTimingFunction: "academy-out",
			_motionReduce: { transitionDuration: "none" },
		},
		watchFeature: {
			display: "grid",
			gap: "6",
			alignItems: "center",
			color: "academy.text",
			textDecoration: "none",
			_lg: { gridTemplateColumns: "1.1fr 1fr", gap: "10" },
			_hover: {
				"& h2": { color: "academy.accent" },
				"& img": { transform: "scale(1.03)" },
				"& [data-play]": { transform: "scale(1.08)" },
			},
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		watchTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "3xl",
			fontWeight: "bold",
			letterSpacing: "academy-tight",
			lineHeight: "academy-title",
			textWrap: "balance",
			transitionProperty: "colors",
			transitionDuration: "base",
		},
		searchBar: {
			display: "grid",
			alignItems: "center",
			gap: "3",
			marginBottom: "8",
			"& label": { fontSize: "sm", fontWeight: "semibold" },
			_sm: { gridTemplateColumns: "auto minmax(0, 1fr) auto", gap: "5" },
		},
		input: {
			width: "full",
			minWidth: "0",
			minHeight: "12",
			paddingInline: "4",
			paddingBlock: "3",
			border: "hairline",
			borderColor: "academy.inputBorder",
			borderRadius: "academy-s",
			backgroundColor: "academy.input",
			color: "academy.text",
			fontFamily: "academy-text",
			fontSize: "md",
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		empty: { paddingBlock: "10", color: "academy.textSoft" },
		more: {
			display: "grid",
			justifyItems: "center",
			gap: "3",
			marginTop: "10",
		},
		newsletter: {
			display: "grid",
			gap: "8",
			maxWidth: "academy-shell",
			marginInline: "auto",
			marginTop: "20",
			paddingInline: "academy-gutter",
			paddingBlock: "12",
			borderTop: "hairline",
			borderColor: "academy.border",
			_lg: {
				gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
				gap: "16",
				alignItems: "center",
				paddingBlock: "16",
			},
		},
		newsletterCopy: { display: "grid", gap: "3" },
		newsletterForm: {
			display: "grid",
			gap: "3",
			"& label": {
				color: "academy.text",
				fontSize: "sm",
				fontWeight: "semibold",
			},
		},
		newsletterRow: {
			display: "grid",
			gap: "3",
			_sm: { gridTemplateColumns: "minmax(0, 1fr) auto" },
		},
		finePrint: {
			margin: "0",
			color: "academy.textMuted",
			fontSize: "xs",
			lineHeight: "body",
			"& a": { color: "inherit", textUnderlineOffset: "0.2em" },
		},
	},
});
