import { sva } from "../../styled-system/css";

export const academyAuthorGroup = sva({
	slots: [
		"root",
		"stack",
		"item",
		"avatar",
		"initials",
		"overflow",
		"indicator",
		"names",
	],
	base: {
		root: {
			display: "flex",
			flexWrap: "wrap",
			alignItems: "center",
			gap: "3",
			minWidth: "0",
			fontFamily: "academy-text",
			color: "academy.text",
		},
		stack: {
			display: "flex",
			isolation: "isolate",
			flexShrink: "0",
			"& > * + *": { marginInlineStart: "-3" },
		},
		item: { position: "relative", flexShrink: "0" },
		avatar: {
			display: "block",
			width: "10",
			height: "10",
			objectFit: "cover",
			borderRadius: "full",
			border: "hairline",
			borderColor: "academy.canvas",
			background: "academy.ground",
		},
		initials: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			fontSize: "sm",
			fontWeight: "medium",
		},
		overflow: {
			position: "relative",
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			fontSize: "xs",
			fontWeight: "medium",
		},
		indicator: {
			position: "absolute",
			bottom: "0",
			right: "0",
			width: "2.5",
			height: "2.5",
			borderRadius: "full",
			border: "hairline",
			borderColor: "academy.canvas",
			background: "academy.statusSpruce",
		},
		names: {
			minWidth: "0",
			fontSize: "sm",
			fontWeight: "medium",
			lineHeight: "normal",
			overflowWrap: "anywhere",
		},
	},
});
