import { sva } from "../../styled-system/css";

/**
 * Presentational additions for the Academy's informational and commercial
 * pages. Structural sizing remains in academyLayout so collection and
 * account routes share the same page contract.
 */
export const academyMarketing = sva({
	slots: [
		"actions",
		"card",
		"cardBody",
		"eyebrow",
		"lead",
		"meta",
		"pill",
		"statGrid",
		"stat",
		"statValue",
		"statLabel",
		"faq",
		"utility",
		"utilityMark",
		"utilityActions",
		"contact",
		"contactRow",
		"copyButton",
		"newsletter",
		"newsletterSection",
		"newsletterGrid",
		"newsletterCopy",
		"newsletterBadge",
		"newsletterTitle",
		"newsletterLead",
		"newsletterWidget",
		"newsletterSuccess",
		"newsletterError",
		"newsletterButton",
		"newsletterSpinner",
		"newsletterForm",
		"newsletterInputRow",
		"newsletterField",
		"newsletterSubmit",
		"newsletterDivider",
		"newsletterDividerLine",
		"newsletterDividerText",
		"newsletterSignIn",
	],
	base: {
		actions: { display: "flex", flexWrap: "wrap", gap: "3", marginTop: "6" },
		card: {
			minWidth: "0",
			padding: "6",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			backgroundColor: "academy.panel",
		},
		cardBody: { color: "academy.textSoft", lineHeight: "relaxed" },
		eyebrow: {
			margin: "0",
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "bold",
			letterSpacing: "wide",
			textTransform: "uppercase",
		},
		lead: { margin: "0", color: "academy.textSoft", fontSize: "lg", lineHeight: "relaxed" },
		meta: { margin: "0", color: "academy.textMuted", fontFamily: "academy-mono", fontSize: "xs", letterSpacing: "wide" },
		pill: {
			display: "inline-flex",
			alignItems: "center",
			paddingInline: "3",
			paddingBlock: "1",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-pill",
			color: "academy.textSoft",
			fontSize: "xs",
		},
		statGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(10rem, 1fr))", gap: "4" },
		stat: { padding: "5", borderInlineStart: "focus", borderColor: "academy.accent", backgroundColor: "academy.panel" },
		statValue: { display: "block", color: "academy.text", fontFamily: "academy-display", fontSize: "3xl", fontWeight: "bold", lineHeight: "tight" },
		statLabel: { display: "block", marginTop: "2", color: "academy.textMuted", fontSize: "sm" },
		faq: {
			display: "grid",
			gap: "3",
			"& details": { padding: "5", border: "hairline", borderColor: "academy.border", borderRadius: "academy-m", backgroundColor: "academy.panel" },
			"& summary": { cursor: "pointer", color: "academy.text", fontWeight: "semibold" },
			"& details > p": { marginTop: "4", color: "academy.textSoft", lineHeight: "relaxed" },
		},
		utility: { display: "flex", flexDirection: "column", alignItems: "flex-start", justifyContent: "center", minHeight: "screen", paddingBlock: "16" },
		utilityMark: { display: "grid", placeItems: "center", width: "12", height: "12", marginBottom: "6", border: "focus", borderColor: "academy.accent", borderRadius: "academy-s", color: "academy.accent", fontFamily: "academy-mono", fontSize: "xl" },
		utilityActions: { display: "flex", flexWrap: "wrap", gap: "3", marginTop: "8" },
		contact: { display: "grid", gap: "4", width: "full", padding: "6", border: "hairline", borderColor: "academy.border", borderRadius: "academy-m", backgroundColor: "academy.panel" },
		contactRow: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: "3" },
		copyButton: { display: "inline-flex", alignItems: "center", minHeight: "9", paddingInline: "3", border: "hairline", borderColor: "academy.border", borderRadius: "academy-s", backgroundColor: "transparent", color: "academy.text", fontSize: "sm", fontWeight: "semibold", cursor: "pointer", _hover: { backgroundColor: "academy.ground" }, _focusVisible: { outline: "focus", outlineColor: "academy.accent", outlineOffset: "focus" } },
		newsletter: { width: "full" },
		newsletterSection: { overflow: "hidden", border: "hairline", borderColor: "academy.border" },
		newsletterGrid: { display: "grid", alignItems: "center" },
		newsletterCopy: { display: "flex", flexDirection: "column", minWidth: "0" },
		newsletterBadge: { display: "inline-flex", alignItems: "center", gap: "2", color: "academy.accent", fontFamily: "academy-mono", fontSize: "xs", fontWeight: "semibold", letterSpacing: "wide", textTransform: "uppercase" },
		newsletterTitle: { maxWidth: "academy-copy", margin: "0", color: "academy.text", fontFamily: "academy-display", fontWeight: "bold", letterSpacing: "tight", lineHeight: "tight", textWrap: "balance" },
		newsletterLead: { maxWidth: "academy-copy", margin: "0", color: "academy.textSoft", lineHeight: "relaxed" },
		newsletterWidget: { width: "full", _lg: { justifySelf: "end" } },
		newsletterSuccess: { display: "flex", alignItems: "center", justifyContent: "center", gap: "2", minHeight: "11", paddingInline: "4", paddingBlock: "3", border: "hairline", borderColor: "academy.accent", borderRadius: "academy-s", backgroundColor: "academy.panel", color: "academy.accent", fontSize: "sm", fontWeight: "semibold", "& svg": { width: "5", height: "5", flexShrink: "0" } },
		newsletterError: { display: "flex", alignItems: "center", gap: "2", marginBlockEnd: "2", padding: "3", border: "hairline", borderColor: "academy.border", borderRadius: "academy-s", backgroundColor: "academy.panel", color: "academy.textSoft", fontSize: "xs", lineHeight: "body", "& svg": { width: "4", height: "4", flexShrink: "0", color: "academy.accent" } },
		newsletterButton: { display: "inline-flex", alignItems: "center", justifyContent: "center", gap: "2", width: "full", minHeight: "11", paddingInline: "4", paddingBlock: "3", border: "academy-button", borderRadius: "academy-s", backgroundColor: "academy.accent", color: "academy.accentForeground", fontFamily: "academy-text", fontSize: "sm", fontWeight: "semibold", cursor: "pointer", _hover: { opacity: "0.9" }, _focusVisible: { outline: "focus", outlineColor: "academy.accent", outlineOffset: "focus" }, _disabled: { cursor: "wait", opacity: "0.7" }, "& svg": { width: "4", height: "4", flexShrink: "0" } },
		newsletterSpinner: { width: "4", height: "4", flexShrink: "0", animation: "academy-spinner", _motionReduce: { animation: "none" } },
		newsletterForm: { display: "flex", flexDirection: "column", gap: "2" },
		newsletterInputRow: { position: "relative" },
		newsletterField: { width: "full", minHeight: "11", paddingInlineStart: "3", paddingInlineEnd: "12", border: "hairline", borderColor: "academy.inputBorder", borderRadius: "academy-s", backgroundColor: "academy.input", color: "academy.text", fontFamily: "academy-text", fontSize: "sm", _focusVisible: { outline: "focus", outlineColor: "academy.accent", outlineOffset: "focus" }, _disabled: { opacity: "0.6" } },
		newsletterSubmit: { position: "absolute", insetInlineEnd: "1", insetBlockStart: "1", display: "inline-flex", alignItems: "center", justifyContent: "center", width: "9", height: "9", border: "academy-button", borderRadius: "academy-s", backgroundColor: "academy.accent", color: "academy.accentForeground", cursor: "pointer", _focusVisible: { outline: "focus", outlineColor: "academy.accent", outlineOffset: "focus" }, _disabled: { cursor: "not-allowed", opacity: "0.5" }, "& svg": { width: "4", height: "4" } },
		newsletterDivider: { display: "flex", alignItems: "center", gap: "2" },
		newsletterDividerLine: { flex: "1", height: "0", borderTop: "hairline", borderColor: "academy.border" },
		newsletterDividerText: { color: "academy.textMuted", fontFamily: "academy-mono", fontSize: "xs" },
		newsletterSignIn: { display: "inline-flex", alignItems: "center", justifyContent: "center", width: "full", minHeight: "11", paddingInline: "4", border: "hairline", borderColor: "academy.inputBorder", borderRadius: "academy-s", backgroundColor: "transparent", color: "academy.text", fontSize: "sm", fontWeight: "semibold", textDecoration: "none", _hover: { borderColor: "academy.accent", color: "academy.accent" }, _focusVisible: { outline: "focus", outlineColor: "academy.accent", outlineOffset: "focus" } },
	},
	variants: {
		newsletterVariant: {
			card: {
				newsletter: { paddingBlock: "12" },
				newsletterSection: { padding: "6", borderRadius: "academy-m", backgroundColor: "academy.ground", _lg: { padding: "8" } },
				newsletterGrid: { gap: "5", _lg: { gridTemplateColumns: "minmax(0, 1fr) 18rem", gap: "8" } },
				newsletterCopy: { gap: "2" },
				newsletterTitle: { fontSize: "xl", _lg: { fontSize: "2xl" } },
				newsletterLead: { fontSize: "sm", _lg: { fontSize: "md" } },
				newsletterWidget: { maxWidth: "sm" },
			},
			section: {
				newsletter: { paddingBlock: "8" },
				newsletterSection: { padding: "7", borderRadius: "academy-l", backgroundColor: "academy.panel", _lg: { padding: "10" } },
				newsletterGrid: { gap: "6", _lg: { gridTemplateColumns: "minmax(0, 1fr) 20rem", gap: "10" } },
				newsletterCopy: { gap: "3" },
				newsletterTitle: { fontSize: "2xl", _lg: { fontSize: "3xl" } },
				newsletterLead: { fontSize: "md", _lg: { fontSize: "lg" } },
				newsletterWidget: { maxWidth: "md" },
			},
		},
	},
	defaultVariants: {
		newsletterVariant: "card",
	},
});
