import { sva } from "../../styled-system/css";

/**
 * Listing-specific pieces that sit on top of the shared Academy layout.
 * Keep these intentionally presentational: route data, filtering, and SEO
 * remain in Astro pages.
 */
export const academyCatalog = sva({
	slots: [
		"featured",
		"featuredMedia",
		"featuredImage",
		"featuredBody",
		"featuredKicker",
		"featuredTitle",
		"featuredDescription",
		"filters",
		"feedLink",
		"filterForm",
		"filterField",
		"filterLink",
		"rows",
		"row",
		"rowIndex",
		"rowMain",
		"rowTitle",
		"rowDescription",
		"rowMeta",
		"avatar",
		"identityGrid",
		"identity",
		"identityMark",
		"identityPortrait",
		"identityAvatar",
		"identityInitials",
		"identityLogo",
		"identityBody",
		"identityTitle",
		"identityMeta",
		"identityDescription",
		"identityArrow",
		"resultCount",
		"empty",
		"statGrid",
		"stat",
		"statValue",
		"statLabel",
		"pager",
		"editorialList",
		"editorialRow",
		"editorialImage",
		"editorialBody",
		"editorialTitle",
	],
	base: {
		editorialList: {
			display: "grid",
			borderTop: "hairline",
			borderColor: "academy.border",
		},
		editorialRow: {
			display: "grid",
			gridTemplateColumns: "4.5rem minmax(0, 1fr)",
			gap: "4",
			alignItems: "start",
			paddingBlock: "6",
			borderBottom: "hairline",
			borderColor: "academy.border",
			color: "academy.text",
			textDecoration: "none",
			"&[data-media='false']": { gridTemplateColumns: "minmax(0, 1fr)" },
			_lg: { gridTemplateColumns: "10rem minmax(0, 1fr)", gap: "8" },
			_hover: { "& h3": { color: "academy.accent" } },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		editorialImage: {
			width: "full",
			height: "auto",
			aspectRatio: "academy-video",
			objectFit: "cover",
			borderRadius: "academy-s",
		},
		editorialBody: { display: "grid", gap: "2", minWidth: "0" },
		editorialTitle: {
			margin: "0",
			fontFamily: "academy-display",
			fontSize: "lg",
			fontWeight: "bold",
			lineHeight: "tight",
			_lg: { fontSize: "2xl" },
		},
		featured: {
			display: "grid",
			gap: "6",
			alignItems: "center",
			_lg: { gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "10" },
		},
		featuredMedia: {
			display: "block",
			overflow: "hidden",
			borderRadius: "academy-m",
			background: "academy.ground",
			aspectRatio: "academy-video",
			order: "-1",
			_lg: { order: "0" },
		},
		featuredImage: { width: "full", height: "full", objectFit: "cover" },
		featuredBody: {
			display: "flex",
			flexDirection: "column",
			justifyContent: "center",
			alignItems: "flex-start",
			gap: "4",
		},
		featuredKicker: {
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontWeight: "medium",
			letterSpacing: "widest",
			textTransform: "uppercase",
		},
		featuredTitle: {
			margin: "0",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "3xl",
			fontWeight: "bold",
			letterSpacing: "tight",
			lineHeight: "tight",
			textWrap: "balance",
			_lg: { fontSize: "4xl" },
		},
		featuredDescription: {
			margin: "0",
			color: "academy.textSoft",
			fontSize: "md",
			lineHeight: "body",
		},
		filters: {
			display: "flex",
			flexWrap: "wrap",
			gap: "2",
			alignItems: "center",
		},
		feedLink: {
			color: "academy.text",
			fontSize: "sm",
			fontWeight: "semibold",
			textUnderlineOffset: "0.2em",
			_hover: { color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		filterForm: {
			display: "grid",
			gap: "4",
			alignItems: "end",
			paddingBlock: "6",
			marginBottom: "8",
			borderBlock: "hairline",
			borderColor: "academy.border",
			_sm: { gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr) auto" },
		},
		filterField: {
			display: "grid",
			gap: "2",
			color: "academy.textSoft",
			fontSize: "sm",
			fontWeight: "semibold",
		},
		filterLink: {
			display: "inline-flex",
			alignItems: "center",
			minHeight: "9",
			paddingInline: "3",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-pill",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			textDecoration: "none",
			_hover: { borderColor: "academy.accent", color: "academy.text" },
			"&[aria-current='page']": {
				borderColor: "academy.accent",
				background: "academy.accent",
				color: "academy.accentForeground",
			},
		},
		rows: { display: "grid", borderTop: "hairline" },
		row: {
			display: "grid",
			gap: "3",
			alignItems: "start",
			paddingBlock: "6",
			borderBottom: "hairline",
			color: "academy.text",
			textDecoration: "none",
			_sm: { gridTemplateColumns: "6rem minmax(0, 1fr)", gap: "4" },
			_hover: { color: "academy.accent" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
		},
		rowIndex: {
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "xs",
			paddingBlockStart: "1",
		},
		rowMain: { minWidth: "0" },
		rowTitle: {
			display: "block",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "xl",
			fontWeight: "semibold",
			lineHeight: "tight",
		},
		rowDescription: {
			display: "block",
			marginBlockStart: "2",
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "body",
		},
		rowMeta: {
			display: "flex",
			flexWrap: "wrap",
			gap: "2",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			lineHeight: "body",
			textTransform: "uppercase",
		},
		avatar: {
			width: "12",
			height: "12",
			borderRadius: "full",
			objectFit: "cover",
			background: "academy.ground",
			border: "hairline",
			borderColor: "academy.border",
		},
		identityGrid: {
			display: "grid",
			gridTemplateColumns: "repeat(auto-fill, minmax(min(100%, 20rem), 1fr))",
			gap: "3",
			alignItems: "stretch",
		},
		identity: {
			display: "grid",
			gridTemplateColumns: "auto minmax(0, 1fr) auto",
			alignItems: "center",
			gap: "3",
			minWidth: "0",
			minHeight: "20",
			padding: "4",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			background: "academy.panel",
			color: "academy.text",
			textDecoration: "none",
			transitionProperty: "colors",
			transitionDuration: "fast",
			"&[hidden]": { display: "none" },
			_hover: { borderColor: "academy.accent", background: "academy.ground" },
			_focusVisible: {
				outline: "focus",
				outlineColor: "academy.accent",
				outlineOffset: "focus",
			},
			_motionReduce: { transitionDuration: "none" },
		},
		identityMark: {
			display: "grid",
			placeItems: "center",
			alignSelf: "start",
			width: "12",
			height: "12",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			background: "academy.ground",
		},
		identityPortrait: {
			display: "grid",
			placeItems: "center",
			width: "12",
			height: "12",
			overflow: "hidden",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "full",
			background: "academy.ground",
		},
		identityAvatar: {
			display: "block",
			width: "full",
			height: "full",
			objectFit: "cover",
		},
		identityInitials: {
			color: "academy.textSoft",
			fontFamily: "academy-mono",
			fontSize: "sm",
			fontWeight: "semibold",
			lineHeight: "none",
			"&[hidden]": { display: "none" },
		},
		identityLogo: { width: "8", height: "8", objectFit: "contain" },
		identityBody: { display: "grid", gap: "1", minWidth: "0" },
		identityTitle: {
			minWidth: "0",
			overflowWrap: "anywhere",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "lg",
			fontWeight: "bold",
			lineHeight: "tight",
		},
		identityMeta: {
			color: "academy.textMuted",
			fontSize: "xs",
			lineHeight: "body",
			overflowWrap: "anywhere",
		},
		identityDescription: {
			color: "academy.textSoft",
			fontSize: "sm",
			lineHeight: "body",
			lineClamp: "2",
			overflowWrap: "anywhere",
		},
		identityArrow: {
			alignSelf: "start",
			paddingBlockStart: "1",
			color: "academy.accent",
			fontFamily: "academy-mono",
			fontSize: "lg",
			lineHeight: "none",
		},
		resultCount: {
			margin: "0",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			fontVariantNumeric: "tabular-nums",
		},
		empty: {
			padding: "8",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-s",
			background: "academy.panel",
			textAlign: "center",
			color: "academy.textSoft",
			"&[hidden]": { display: "none" },
			"& h2": {
				margin: "0",
				color: "academy.text",
				fontFamily: "academy-display",
				fontSize: "xl",
				fontWeight: "bold",
				lineHeight: "tight",
			},
			"& p": { marginBlockStart: "2", marginBlockEnd: "0", fontSize: "sm" },
		},
		statGrid: {
			display: "grid",
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
			gap: "3",
			_lg: { gridTemplateColumns: "repeat(4, minmax(0, 1fr))" },
		},
		stat: {
			padding: "4",
			border: "hairline",
			borderColor: "academy.border",
			borderRadius: "academy-m",
			background: "academy.panel",
		},
		statValue: {
			display: "block",
			color: "academy.text",
			fontFamily: "academy-display",
			fontSize: "2xl",
			fontWeight: "bold",
			lineHeight: "tight",
		},
		statLabel: {
			display: "block",
			marginBlockStart: "1",
			color: "academy.textMuted",
			fontFamily: "academy-mono",
			fontSize: "xs",
			textTransform: "uppercase",
		},
		pager: {
			display: "flex",
			justifyContent: "space-between",
			gap: "3",
			marginBlockStart: "8",
		},
	},
});
