/** Read-only public schema capture. Never reads credentials or sends auth headers. */
import { createHash } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { buildClientSchema, getIntrospectionQuery, lexicographicSortSchema, printSchema, type IntrospectionQuery } from 'graphql'

const root = new URL('../', import.meta.url)
await mkdir(new URL('fixtures/', root), { recursive: true })
await mkdir(new URL('evidence/', root), { recursive: true })
const capturedAt = new Date().toISOString()
const captures: Record<string, unknown>[] = []
for (const [name, endpoint] of [['gateway', 'https://api.rawkode.academy/'], ['subgraph', 'https://rawkode.academy/graphql']]) {
  const response = await fetch(endpoint, {
    method: 'POST', headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ query: getIntrospectionQuery() }),
  })
  if (!response.ok) throw new Error(`${endpoint}: HTTP ${response.status}`)
  const result = await response.json() as { data?: IntrospectionQuery; errors?: unknown[] }
  if (result.errors || !result.data) throw new Error(JSON.stringify(result.errors))
  const sdl = printSchema(lexicographicSortSchema(buildClientSchema(result.data))) + '\n'
  await writeFile(new URL(`fixtures/schema-${name}.json`, root), JSON.stringify(result.data, null, 2) + '\n')
  await writeFile(new URL(`fixtures/schema-${name}.graphql`, root), sdl)
  if (name === 'gateway') await writeFile(new URL('fixtures/schema-gateway.ts', root), `// Generated by scripts/capture-schema.ts; public schema only.\nexport const gatewaySDL = ${JSON.stringify(sdl)}\n`)
  captures.push({ name, endpoint, capturedAt, sha256: createHash('sha256').update(sdl).digest('hex') })
}
const revisionResponse = await fetch('https://api.github.com/repos/rawkode-academy/rawkode-academy/commits/main')
if (!revisionResponse.ok) throw new Error(`GitHub revision: ${revisionResponse.status}`)
const revision = (await revisionResponse.json() as { sha: string }).sha
const sourceUrl = `https://raw.githubusercontent.com/rawkode-academy/rawkode-academy/${revision}/projects/rawkode.academy/website/src/subgraph/schema.gql`
const sourceResponse = await fetch(sourceUrl)
if (!sourceResponse.ok) throw new Error(`Source SDL: ${sourceResponse.status}`)
const source = await sourceResponse.text()
await writeFile(new URL('fixtures/schema-source.graphql', root), source)
captures.push({ name: 'source', endpoint: sourceUrl, revision, capturedAt, sha256: createHash('sha256').update(source).digest('hex') })
await writeFile(new URL('evidence/schema-capture.json', root), JSON.stringify({ capturedAt, captures }, null, 2) + '\n')
console.log(JSON.stringify({ capturedAt, revision, captures: captures.length }))
