import {readFileSync,writeFileSync} from 'node:fs'
import assert from 'node:assert/strict'
const fixtures=JSON.parse(readFileSync('.runtime/oidc-fixtures.json','utf8'))
const base='http://127.0.0.1:3100'
const checks:string[]=[]
async function request(path:string,token?:string,method='GET',body?:unknown,origin:string|null=base) {
  return fetch(base+path,{method,redirect:'manual',headers:{'content-type':'application/json',...(token?{cookie:`poc-oidc-session=${token}`} :{}),...(origin?{origin}:{})},body:body===undefined?undefined:JSON.stringify(body)})
}
assert.equal((await request('/api/poc/runtime').then(r=>r.json()) as any).runtime,'Cloudflare-Workers')
assert.equal((await request('/api/auth/session')).status,401)
assert.equal((await request('/api/auth/session',fixtures.tokens.expired)).status,401)
const session=await request('/api/auth/session',fixtures.tokens.a)
assert.equal(session.status,200)
const profile:any=await session.json();assert.equal(profile.user.id,fixtures.a);assert.equal(profile.user.role,'customer')
assert.deepEqual(Object.keys(profile).sort(),['expiresAt','user']);assert.deepEqual(Object.keys(profile.user).sort(),['id','name','role'])
checks.push('Opaque session resolves synthetic customer; anonymous/expired denied; profile allowlist')
assert.equal((await request(`/api/users/${fixtures.a}`,fixtures.tokens.a)).status,200)
assert.ok([403,404].includes((await request(`/api/users/${fixtures.b}`,fixtures.tokens.a)).status))
const people:any=await request('/api/users?limit=100',fixtures.tokens.a).then(r=>r.json())
assert.deepEqual(people.docs.map((u:any)=>u.id),[fixtures.a])
assert.equal((await request(`/api/users/${fixtures.a}`,fixtures.tokens.a,'PATCH',{role:'staff'})).status,403)
checks.push('Own user readable; customer list scoped to self; other customer and self-promotion denied')
for(const path of [`/api/videos/${fixtures.privateVideoId}?draft=true`,'/api/media','/api/pipeline-runs'])assert.ok([403,404].includes((await request(path,fixtures.tokens.a)).status),path)
for(const [path,body] of [['/api/videos',{slug:'hostile'}],['/api/poc/import',{}],['/api/poc/pipeline',{action:'register'}]] as const)assert.ok([401,403].includes((await request(path,fixtures.tokens.a,'POST',body)).status),path)
assert.equal((await request('/api/graphql',fixtures.tokens.a)).status,404)
const admin=await request('/admin',fixtures.tokens.a);assert.ok(admin.status>=300&&admin.status<400)
checks.push('Customer denied admin, private drafts/media/pipeline, REST/import/pipeline mutations; generated GraphQL route is disabled')
assert.equal((await request('/api/users',fixtures.tokens.a,'POST',{name:'x'},'https://attacker.invalid')).status,403)
assert.equal((await request('/api/users',fixtures.tokens.a,'POST',{name:'x'},null)).status,403)
checks.push('Cross-origin and absent-Origin cookie mutations denied at Worker boundary')
for(const path of ['/api/users/login','/api/users/first-register','/api/users/forgot-password','/api/users/reset-password'])assert.ok([400,401,403,404].includes((await request(path,undefined,'POST',{email:'editor@example.invalid',password:'unused',token:'unused'})).status),path)
assert.equal((await request('/api/users/refresh-token',fixtures.tokens.a,'POST',{})).status,403)
checks.push('Local login/bootstrap/password reset and native JWT refresh disabled with default configuration')
const badCallback=await request('/api/auth/callback?state=unknown&code=not-sent')
assert.equal(badCallback.status,400);checks.push('Invalid callback fails closed without token exchange')
const login=await request('/api/auth/login')
assert.equal(login.status,302)
const authorization=new URL(login.headers.get('location')!)
assert.equal(authorization.origin,'https://id.rawkode.academy');assert.equal(authorization.searchParams.get('client_id'),'rawkode-academy-preview');assert.equal(authorization.searchParams.get('redirect_uri'),base+'/api/auth/callback');assert.equal(authorization.searchParams.get('code_challenge_method'),'S256');assert.ok(authorization.searchParams.get('state'));assert.ok(authorization.searchParams.get('nonce'))
checks.push('Live public discovery creates correct authorization URL; redirect was not followed')
assert.equal((await request('/api/auth/logout',fixtures.tokens.a,'POST',{},'https://attacker.invalid')).status,403)
assert.equal((await request('/api/auth/logout',fixtures.tokens.a,'POST',{})).status,200)
assert.equal((await request('/api/auth/session',fixtures.tokens.a)).status,401)
assert.equal((await request('/api/users/logout',fixtures.tokens.b,'POST',{})).status,200)
assert.equal((await request('/api/auth/session',fixtures.tokens.b)).status,401)
checks.push('Payload native admin logout also revokes the OIDC session')
checks.push('Same-origin logout revokes session; subsequent session request denied')
const result={passed:true,at:new Date().toISOString(),runtime:'local Cloudflare workerd/D1',checks,limits:['Successful protocol exchange uses synthetic provider tests, not live sign-in','Sessions were seeded through trusted local CLI; no public test-auth endpoint','Customer project grants not implemented; all private catalogue access denied','Production callback/client deployment not tested']}
writeFileSync('evidence/oidc-worker.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2))
