apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rawkode-chat
  namespace: rawkode-chat
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: rawkode-chat
    creationPolicy: Owner
  data:
    - secretKey: WADDLE_SESSION_KEY
      remoteRef:
        key: /projects/rawkode-chat/WADDLE_SESSION_KEY
