apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rawkode-chat-data
  namespace: rawkode-chat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-single-replica
  resources:
    requests:
      storage: 10Gi
