apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent
  namespace: flux-system
spec:
  interval: 30m
  releaseName: kagent
  targetNamespace: kagent
  dependsOn:
    - name: kagent-crds
  chart:
    spec:
      chart: kagent
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: kagent
        namespace: flux-system
      version: "0.7.23"
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    providers:
      default: openAI
      openAI:
        provider: OpenAI
        model: gpt-4.1-mini
        apiKeySecretRef: kagent-openai
        apiKeySecretKey: OPENAI_API_KEY
    agents:
      k8s-agent:
        enabled: false
      kgateway-agent:
        enabled: false
      istio-agent:
        enabled: false
      promql-agent:
        enabled: false
      observability-agent:
        enabled: false
      argo-rollouts-agent:
        enabled: false
      helm-agent:
        enabled: false
      cilium-policy-agent:
        enabled: false
      cilium-manager-agent:
        enabled: false
      cilium-debug-agent:
        enabled: false
