import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`DROP INDEX \`showId_slug_idx\`;`)
  await db.run(sql`ALTER TABLE \`seasons\` ADD \`source_show_id\` text;`)
  await db.run(sql`CREATE UNIQUE INDEX \`sourceShowId_slug_idx\` ON \`seasons\` (\`source_show_id\`,\`slug\`);`)
  await db.run(sql`DROP INDEX \`version_showId_version_slug_idx\`;`)
  await db.run(sql`ALTER TABLE \`_seasons_v\` ADD \`version_source_show_id\` text;`)
  await db.run(sql`CREATE INDEX \`version_sourceShowId_version_slug_idx\` ON \`_seasons_v\` (\`version_source_show_id\`,\`version_slug\`);`)
  await db.run(sql`DROP INDEX \`seasonId_personSlug_idx\`;`)
  await db.run(sql`DROP INDEX \`seasonId_userId_idx\`;`)
  await db.run(sql`ALTER TABLE \`competitors\` ADD \`source_season_id\` text;`)
  await db.run(sql`CREATE UNIQUE INDEX \`sourceSeasonId_personSlug_idx\` ON \`competitors\` (\`source_season_id\`,\`person_slug\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`sourceSeasonId_userId_idx\` ON \`competitors\` (\`source_season_id\`,\`user_id\`);`)
  await db.run(sql`DROP INDEX \`version_seasonId_version_personSlug_idx\`;`)
  await db.run(sql`DROP INDEX \`version_seasonId_version_userId_idx\`;`)
  await db.run(sql`ALTER TABLE \`_competitors_v\` ADD \`version_source_season_id\` text;`)
  await db.run(sql`CREATE INDEX \`version_sourceSeasonId_version_personSlug_idx\` ON \`_competitors_v\` (\`version_source_season_id\`,\`version_person_slug\`);`)
  await db.run(sql`CREATE INDEX \`version_sourceSeasonId_version_userId_idx\` ON \`_competitors_v\` (\`version_source_season_id\`,\`version_user_id\`);`)
  await db.run(sql`DROP INDEX \`seasonId_slug_idx\`;`)
  await db.run(sql`ALTER TABLE \`brackets\` ADD \`source_season_id\` text;`)
  await db.run(sql`CREATE UNIQUE INDEX \`sourceSeasonId_slug_idx\` ON \`brackets\` (\`source_season_id\`,\`slug\`);`)
  await db.run(sql`DROP INDEX \`version_seasonId_version_slug_idx\`;`)
  await db.run(sql`ALTER TABLE \`_brackets_v\` ADD \`version_source_season_id\` text;`)
  await db.run(sql`CREATE INDEX \`version_sourceSeasonId_version_slug_idx\` ON \`_brackets_v\` (\`version_source_season_id\`,\`version_slug\`);`)
  await db.run(sql`DROP INDEX \`bracketId_competitorId_idx\`;`)
  await db.run(sql`ALTER TABLE \`bracket_applications\` ADD \`source_bracket_id\` text;`)
  await db.run(sql`ALTER TABLE \`bracket_applications\` ADD \`source_competitor_id\` text;`)
  await db.run(sql`CREATE UNIQUE INDEX \`sourceBracketId_sourceCompetitorId_idx\` ON \`bracket_applications\` (\`source_bracket_id\`,\`source_competitor_id\`);`)
  await db.run(sql`DROP INDEX \`version_bracketId_version_competitorId_idx\`;`)
  await db.run(sql`ALTER TABLE \`_bracket_applications_v\` ADD \`version_source_bracket_id\` text;`)
  await db.run(sql`ALTER TABLE \`_bracket_applications_v\` ADD \`version_source_competitor_id\` text;`)
  await db.run(sql`CREATE INDEX \`version_sourceBracketId_version_sourceCompetitorId_idx\` ON \`_bracket_applications_v\` (\`version_source_bracket_id\`,\`version_source_competitor_id\`);`)
  await db.run(sql`DROP INDEX \`bracketId_slug_idx\`;`)
  await db.run(sql`ALTER TABLE \`teams\` ADD \`source_season_id\` text;`)
  await db.run(sql`ALTER TABLE \`teams\` ADD \`source_bracket_id\` text;`)
  await db.run(sql`CREATE UNIQUE INDEX \`sourceBracketId_slug_idx\` ON \`teams\` (\`source_bracket_id\`,\`slug\`);`)
  await db.run(sql`DROP INDEX \`version_bracketId_version_slug_idx\`;`)
  await db.run(sql`ALTER TABLE \`_teams_v\` ADD \`version_source_season_id\` text;`)
  await db.run(sql`ALTER TABLE \`_teams_v\` ADD \`version_source_bracket_id\` text;`)
  await db.run(sql`CREATE INDEX \`version_sourceBracketId_version_slug_idx\` ON \`_teams_v\` (\`version_source_bracket_id\`,\`version_slug\`);`)
  await db.run(sql`DROP INDEX \`teamId_competitorId_idx\`;`)
  await db.run(sql`DROP INDEX \`bracketId_competitorId_1_idx\`;`)
  await db.run(sql`ALTER TABLE \`team_members\` ADD \`source_team_id\` text;`)
  await db.run(sql`ALTER TABLE \`team_members\` ADD \`source_bracket_id\` text;`)
  await db.run(sql`ALTER TABLE \`team_members\` ADD \`source_competitor_id\` text;`)
  await db.run(sql`CREATE UNIQUE INDEX \`sourceTeamId_sourceCompetitorId_idx\` ON \`team_members\` (\`source_team_id\`,\`source_competitor_id\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`sourceBracketId_sourceCompetitorId_1_idx\` ON \`team_members\` (\`source_bracket_id\`,\`source_competitor_id\`);`)
  await db.run(sql`DROP INDEX \`version_teamId_version_competitorId_idx\`;`)
  await db.run(sql`DROP INDEX \`version_bracketId_version_competitorId_1_idx\`;`)
  await db.run(sql`ALTER TABLE \`_team_members_v\` ADD \`version_source_team_id\` text;`)
  await db.run(sql`ALTER TABLE \`_team_members_v\` ADD \`version_source_bracket_id\` text;`)
  await db.run(sql`ALTER TABLE \`_team_members_v\` ADD \`version_source_competitor_id\` text;`)
  await db.run(sql`CREATE INDEX \`version_sourceTeamId_version_sourceCompetitorId_idx\` ON \`_team_members_v\` (\`version_source_team_id\`,\`version_source_competitor_id\`);`)
  await db.run(sql`CREATE INDEX \`version_sourceBracketId_version_sourceCompetitorId_1_idx\` ON \`_team_members_v\` (\`version_source_bracket_id\`,\`version_source_competitor_id\`);`)
  await db.run(sql`DROP INDEX \`bracketId_seed_idx\`;`)
  await db.run(sql`DROP INDEX \`bracketId_competitorId_2_idx\`;`)
  await db.run(sql`DROP INDEX \`bracketId_teamId_idx\`;`)
  await db.run(sql`ALTER TABLE \`bracket_entries\` ADD \`source_bracket_id\` text;`)
  await db.run(sql`ALTER TABLE \`bracket_entries\` ADD \`source_competitor_id\` text;`)
  await db.run(sql`ALTER TABLE \`bracket_entries\` ADD \`source_team_id\` text;`)
  await db.run(sql`CREATE UNIQUE INDEX \`sourceBracketId_seed_idx\` ON \`bracket_entries\` (\`source_bracket_id\`,\`seed\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`sourceBracketId_sourceCompetitorId_2_idx\` ON \`bracket_entries\` (\`source_bracket_id\`,\`source_competitor_id\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`sourceBracketId_sourceTeamId_idx\` ON \`bracket_entries\` (\`source_bracket_id\`,\`source_team_id\`);`)
  await db.run(sql`DROP INDEX \`version_bracketId_version_seed_idx\`;`)
  await db.run(sql`DROP INDEX \`version_bracketId_version_competitorId_2_idx\`;`)
  await db.run(sql`DROP INDEX \`version_bracketId_version_teamId_idx\`;`)
  await db.run(sql`ALTER TABLE \`_bracket_entries_v\` ADD \`version_source_bracket_id\` text;`)
  await db.run(sql`ALTER TABLE \`_bracket_entries_v\` ADD \`version_source_competitor_id\` text;`)
  await db.run(sql`ALTER TABLE \`_bracket_entries_v\` ADD \`version_source_team_id\` text;`)
  await db.run(sql`CREATE INDEX \`version_sourceBracketId_version_seed_idx\` ON \`_bracket_entries_v\` (\`version_source_bracket_id\`,\`version_seed\`);`)
  await db.run(sql`CREATE INDEX \`version_sourceBracketId_version_sourceCompetitorId_2_idx\` ON \`_bracket_entries_v\` (\`version_source_bracket_id\`,\`version_source_competitor_id\`);`)
  await db.run(sql`CREATE INDEX \`version_sourceBracketId_version_sourceTeamId_idx\` ON \`_bracket_entries_v\` (\`version_source_bracket_id\`,\`version_source_team_id\`);`)
  await db.run(sql`DROP INDEX \`matchId_idx\`;`)
  await db.run(sql`ALTER TABLE \`match_results\` ADD \`source_match_id\` text;`)
  await db.run(sql`ALTER TABLE \`match_results\` ADD \`source_winner_team_id\` text;`)
  await db.run(sql`ALTER TABLE \`match_results\` ADD \`source_winner_entry_id\` text;`)
  await db.run(sql`CREATE UNIQUE INDEX \`sourceMatchId_idx\` ON \`match_results\` (\`source_match_id\`);`)
  await db.run(sql`DROP INDEX \`version_matchId_idx\`;`)
  await db.run(sql`ALTER TABLE \`_match_results_v\` ADD \`version_source_match_id\` text;`)
  await db.run(sql`ALTER TABLE \`_match_results_v\` ADD \`version_source_winner_team_id\` text;`)
  await db.run(sql`ALTER TABLE \`_match_results_v\` ADD \`version_source_winner_entry_id\` text;`)
  await db.run(sql`CREATE INDEX \`version_sourceMatchId_idx\` ON \`_match_results_v\` (\`version_source_match_id\`);`)
  await db.run(sql`ALTER TABLE \`team_invites\` ADD \`source_team_id\` text;`)
  await db.run(sql`ALTER TABLE \`team_invites\` ADD \`source_bracket_id\` text;`)
  await db.run(sql`ALTER TABLE \`_team_invites_v\` ADD \`version_source_team_id\` text;`)
  await db.run(sql`ALTER TABLE \`_team_invites_v\` ADD \`version_source_bracket_id\` text;`)
  await db.run(sql`ALTER TABLE \`bracket_breaks\` ADD \`source_bracket_id\` text;`)
  await db.run(sql`ALTER TABLE \`_bracket_breaks_v\` ADD \`version_source_bracket_id\` text;`)
  await db.run(sql`ALTER TABLE \`matches\` ADD \`source_bracket_id\` text;`)
  await db.run(sql`ALTER TABLE \`matches\` ADD \`source_team_a_id\` text;`)
  await db.run(sql`ALTER TABLE \`matches\` ADD \`source_team_b_id\` text;`)
  await db.run(sql`ALTER TABLE \`matches\` ADD \`source_entry_a_id\` text;`)
  await db.run(sql`ALTER TABLE \`matches\` ADD \`source_entry_b_id\` text;`)
  await db.run(sql`ALTER TABLE \`matches\` ADD \`source_winner_team_id\` text;`)
  await db.run(sql`ALTER TABLE \`matches\` ADD \`source_winner_entry_id\` text;`)
  await db.run(sql`ALTER TABLE \`_matches_v\` ADD \`version_source_bracket_id\` text;`)
  await db.run(sql`ALTER TABLE \`_matches_v\` ADD \`version_source_team_a_id\` text;`)
  await db.run(sql`ALTER TABLE \`_matches_v\` ADD \`version_source_team_b_id\` text;`)
  await db.run(sql`ALTER TABLE \`_matches_v\` ADD \`version_source_entry_a_id\` text;`)
  await db.run(sql`ALTER TABLE \`_matches_v\` ADD \`version_source_entry_b_id\` text;`)
  await db.run(sql`ALTER TABLE \`_matches_v\` ADD \`version_source_winner_team_id\` text;`)
  await db.run(sql`ALTER TABLE \`_matches_v\` ADD \`version_source_winner_entry_id\` text;`)
  await db.run(sql`ALTER TABLE \`registrations\` ADD \`source_season_id\` text;`)
  await db.run(sql`ALTER TABLE \`registrations\` ADD \`source_bracket_id\` text;`)
  await db.run(sql`ALTER TABLE \`_registrations_v\` ADD \`version_source_season_id\` text;`)
  await db.run(sql`ALTER TABLE \`_registrations_v\` ADD \`version_source_bracket_id\` text;`)
  await db.run(sql`UPDATE \`seasons\` SET \`source_show_id\` = COALESCE(json_extract(\`source_data\`, '$.showId'), json_extract(\`source_data\`, '$.show_id'), CASE WHEN typeof(\`show_id\`) = 'text' THEN \`show_id\` END) WHERE \`source_show_id\` IS NULL;`)
  await db.run(sql`UPDATE \`competitors\` SET \`source_season_id\` = COALESCE(json_extract(\`source_data\`, '$.seasonId'), json_extract(\`source_data\`, '$.season_id'), CASE WHEN typeof(\`season_id\`) = 'text' THEN \`season_id\` END) WHERE \`source_season_id\` IS NULL;`)
  await db.run(sql`UPDATE \`brackets\` SET \`source_season_id\` = COALESCE(json_extract(\`source_data\`, '$.seasonId'), json_extract(\`source_data\`, '$.season_id'), CASE WHEN typeof(\`season_id\`) = 'text' THEN \`season_id\` END) WHERE \`source_season_id\` IS NULL;`)
  await db.run(sql`UPDATE \`bracket_applications\` SET \`source_bracket_id\` = COALESCE(json_extract(\`source_data\`, '$.bracketId'), json_extract(\`source_data\`, '$.bracket_id'), CASE WHEN typeof(\`bracket_id\`) = 'text' THEN \`bracket_id\` END), \`source_competitor_id\` = COALESCE(json_extract(\`source_data\`, '$.competitorId'), json_extract(\`source_data\`, '$.competitor_id'), CASE WHEN typeof(\`competitor_id\`) = 'text' THEN \`competitor_id\` END) WHERE \`source_bracket_id\` IS NULL OR \`source_competitor_id\` IS NULL;`)
  await db.run(sql`UPDATE \`teams\` SET \`source_season_id\` = COALESCE(json_extract(\`source_data\`, '$.seasonId'), json_extract(\`source_data\`, '$.season_id'), CASE WHEN typeof(\`season_id\`) = 'text' THEN \`season_id\` END), \`source_bracket_id\` = COALESCE(json_extract(\`source_data\`, '$.bracketId'), json_extract(\`source_data\`, '$.bracket_id'), CASE WHEN typeof(\`bracket_id\`) = 'text' THEN \`bracket_id\` END) WHERE \`source_season_id\` IS NULL OR \`source_bracket_id\` IS NULL;`)
  await db.run(sql`UPDATE \`team_members\` SET \`source_team_id\` = COALESCE(json_extract(\`source_data\`, '$.teamId'), json_extract(\`source_data\`, '$.team_id'), CASE WHEN typeof(\`team_id\`) = 'text' THEN \`team_id\` END), \`source_bracket_id\` = COALESCE(json_extract(\`source_data\`, '$.bracketId'), json_extract(\`source_data\`, '$.bracket_id'), CASE WHEN typeof(\`bracket_id\`) = 'text' THEN \`bracket_id\` END), \`source_competitor_id\` = COALESCE(json_extract(\`source_data\`, '$.competitorId'), json_extract(\`source_data\`, '$.competitor_id'), CASE WHEN typeof(\`competitor_id\`) = 'text' THEN \`competitor_id\` END) WHERE \`source_team_id\` IS NULL OR \`source_bracket_id\` IS NULL OR \`source_competitor_id\` IS NULL;`)
  await db.run(sql`UPDATE \`team_invites\` SET \`source_team_id\` = COALESCE(json_extract(\`source_data\`, '$.teamId'), json_extract(\`source_data\`, '$.team_id'), CASE WHEN typeof(\`team_id\`) = 'text' THEN \`team_id\` END), \`source_bracket_id\` = COALESCE(json_extract(\`source_data\`, '$.bracketId'), json_extract(\`source_data\`, '$.bracket_id'), CASE WHEN typeof(\`bracket_id\`) = 'text' THEN \`bracket_id\` END) WHERE \`source_team_id\` IS NULL OR \`source_bracket_id\` IS NULL;`)
  await db.run(sql`UPDATE \`bracket_breaks\` SET \`source_bracket_id\` = COALESCE(json_extract(\`source_data\`, '$.bracketId'), json_extract(\`source_data\`, '$.bracket_id'), CASE WHEN typeof(\`bracket_id\`) = 'text' THEN \`bracket_id\` END) WHERE \`source_bracket_id\` IS NULL;`)
  await db.run(sql`UPDATE \`bracket_entries\` SET \`source_bracket_id\` = COALESCE(json_extract(\`source_data\`, '$.bracketId'), json_extract(\`source_data\`, '$.bracket_id'), CASE WHEN typeof(\`bracket_id\`) = 'text' THEN \`bracket_id\` END), \`source_competitor_id\` = COALESCE(json_extract(\`source_data\`, '$.competitorId'), json_extract(\`source_data\`, '$.competitor_id'), CASE WHEN typeof(\`competitor_id\`) = 'text' THEN \`competitor_id\` END), \`source_team_id\` = COALESCE(json_extract(\`source_data\`, '$.teamId'), json_extract(\`source_data\`, '$.team_id'), CASE WHEN typeof(\`team_id\`) = 'text' THEN \`team_id\` END) WHERE \`source_bracket_id\` IS NULL OR \`source_competitor_id\` IS NULL OR \`source_team_id\` IS NULL;`)
  await db.run(sql`UPDATE \`matches\` SET \`source_bracket_id\` = COALESCE(json_extract(\`source_data\`, '$.bracketId'), json_extract(\`source_data\`, '$.bracket_id'), CASE WHEN typeof(\`bracket_id\`) = 'text' THEN \`bracket_id\` END), \`source_team_a_id\` = COALESCE(json_extract(\`source_data\`, '$.teamAId'), json_extract(\`source_data\`, '$.team_a_id'), CASE WHEN typeof(\`team_a_id\`) = 'text' THEN \`team_a_id\` END), \`source_team_b_id\` = COALESCE(json_extract(\`source_data\`, '$.teamBId'), json_extract(\`source_data\`, '$.team_b_id'), CASE WHEN typeof(\`team_b_id\`) = 'text' THEN \`team_b_id\` END), \`source_entry_a_id\` = COALESCE(json_extract(\`source_data\`, '$.entryAId'), json_extract(\`source_data\`, '$.entry_a_id'), CASE WHEN typeof(\`entry_a_id\`) = 'text' THEN \`entry_a_id\` END), \`source_entry_b_id\` = COALESCE(json_extract(\`source_data\`, '$.entryBId'), json_extract(\`source_data\`, '$.entry_b_id'), CASE WHEN typeof(\`entry_b_id\`) = 'text' THEN \`entry_b_id\` END), \`source_winner_team_id\` = COALESCE(json_extract(\`source_data\`, '$.winnerTeamId'), json_extract(\`source_data\`, '$.winner_team_id'), CASE WHEN typeof(\`winner_team_id\`) = 'text' THEN \`winner_team_id\` END), \`source_winner_entry_id\` = COALESCE(json_extract(\`source_data\`, '$.winnerEntryId'), json_extract(\`source_data\`, '$.winner_entry_id'), CASE WHEN typeof(\`winner_entry_id\`) = 'text' THEN \`winner_entry_id\` END) WHERE \`source_bracket_id\` IS NULL;`)
  await db.run(sql`UPDATE \`match_results\` SET \`source_match_id\` = COALESCE(json_extract(\`source_data\`, '$.matchId'), json_extract(\`source_data\`, '$.match_id'), CASE WHEN typeof(\`match_id\`) = 'text' THEN \`match_id\` END), \`source_winner_team_id\` = COALESCE(json_extract(\`source_data\`, '$.winnerTeamId'), json_extract(\`source_data\`, '$.winner_team_id'), CASE WHEN typeof(\`winner_team_id\`) = 'text' THEN \`winner_team_id\` END), \`source_winner_entry_id\` = COALESCE(json_extract(\`source_data\`, '$.winnerEntryId'), json_extract(\`source_data\`, '$.winner_entry_id'), CASE WHEN typeof(\`winner_entry_id\`) = 'text' THEN \`winner_entry_id\` END) WHERE \`source_match_id\` IS NULL;`)
  await db.run(sql`UPDATE \`registrations\` SET \`source_season_id\` = COALESCE(json_extract(\`source_data\`, '$.seasonId'), json_extract(\`source_data\`, '$.season_id'), CASE WHEN typeof(\`season_id\`) = 'text' THEN \`season_id\` END), \`source_bracket_id\` = COALESCE(json_extract(\`source_data\`, '$.bracketId'), json_extract(\`source_data\`, '$.bracket_id'), CASE WHEN typeof(\`bracket_id\`) = 'text' THEN \`bracket_id\` END) WHERE \`source_season_id\` IS NULL OR \`source_bracket_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_seasons_v\` SET \`version_source_show_id\` = COALESCE(json_extract(\`version_source_data\`, '$.showId'), json_extract(\`version_source_data\`, '$.show_id'), CASE WHEN typeof(\`version_show_id\`) = 'text' THEN \`version_show_id\` END) WHERE \`version_source_show_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_competitors_v\` SET \`version_source_season_id\` = COALESCE(json_extract(\`version_source_data\`, '$.seasonId'), json_extract(\`version_source_data\`, '$.season_id'), CASE WHEN typeof(\`version_season_id\`) = 'text' THEN \`version_season_id\` END) WHERE \`version_source_season_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_brackets_v\` SET \`version_source_season_id\` = COALESCE(json_extract(\`version_source_data\`, '$.seasonId'), json_extract(\`version_source_data\`, '$.season_id'), CASE WHEN typeof(\`version_season_id\`) = 'text' THEN \`version_season_id\` END) WHERE \`version_source_season_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_bracket_applications_v\` SET \`version_source_bracket_id\` = COALESCE(json_extract(\`version_source_data\`, '$.bracketId'), json_extract(\`version_source_data\`, '$.bracket_id'), CASE WHEN typeof(\`version_bracket_id\`) = 'text' THEN \`version_bracket_id\` END), \`version_source_competitor_id\` = COALESCE(json_extract(\`version_source_data\`, '$.competitorId'), json_extract(\`version_source_data\`, '$.competitor_id'), CASE WHEN typeof(\`version_competitor_id\`) = 'text' THEN \`version_competitor_id\` END) WHERE \`version_source_bracket_id\` IS NULL OR \`version_source_competitor_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_teams_v\` SET \`version_source_season_id\` = COALESCE(json_extract(\`version_source_data\`, '$.seasonId'), json_extract(\`version_source_data\`, '$.season_id'), CASE WHEN typeof(\`version_season_id\`) = 'text' THEN \`version_season_id\` END), \`version_source_bracket_id\` = COALESCE(json_extract(\`version_source_data\`, '$.bracketId'), json_extract(\`version_source_data\`, '$.bracket_id'), CASE WHEN typeof(\`version_bracket_id\`) = 'text' THEN \`version_bracket_id\` END) WHERE \`version_source_season_id\` IS NULL OR \`version_source_bracket_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_team_members_v\` SET \`version_source_team_id\` = COALESCE(json_extract(\`version_source_data\`, '$.teamId'), json_extract(\`version_source_data\`, '$.team_id'), CASE WHEN typeof(\`version_team_id\`) = 'text' THEN \`version_team_id\` END), \`version_source_bracket_id\` = COALESCE(json_extract(\`version_source_data\`, '$.bracketId'), json_extract(\`version_source_data\`, '$.bracket_id'), CASE WHEN typeof(\`version_bracket_id\`) = 'text' THEN \`version_bracket_id\` END), \`version_source_competitor_id\` = COALESCE(json_extract(\`version_source_data\`, '$.competitorId'), json_extract(\`version_source_data\`, '$.competitor_id'), CASE WHEN typeof(\`version_competitor_id\`) = 'text' THEN \`version_competitor_id\` END) WHERE \`version_source_team_id\` IS NULL OR \`version_source_bracket_id\` IS NULL OR \`version_source_competitor_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_bracket_entries_v\` SET \`version_source_bracket_id\` = COALESCE(json_extract(\`version_source_data\`, '$.bracketId'), json_extract(\`version_source_data\`, '$.bracket_id'), CASE WHEN typeof(\`version_bracket_id\`) = 'text' THEN \`version_bracket_id\` END), \`version_source_competitor_id\` = COALESCE(json_extract(\`version_source_data\`, '$.competitorId'), json_extract(\`version_source_data\`, '$.competitor_id'), CASE WHEN typeof(\`version_competitor_id\`) = 'text' THEN \`version_competitor_id\` END), \`version_source_team_id\` = COALESCE(json_extract(\`version_source_data\`, '$.teamId'), json_extract(\`version_source_data\`, '$.team_id'), CASE WHEN typeof(\`version_team_id\`) = 'text' THEN \`version_team_id\` END) WHERE \`version_source_bracket_id\` IS NULL OR \`version_source_competitor_id\` IS NULL OR \`version_source_team_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_matches_v\` SET \`version_source_bracket_id\` = COALESCE(json_extract(\`version_source_data\`, '$.bracketId'), json_extract(\`version_source_data\`, '$.bracket_id'), CASE WHEN typeof(\`version_bracket_id\`) = 'text' THEN \`version_bracket_id\` END), \`version_source_team_a_id\` = COALESCE(json_extract(\`version_source_data\`, '$.teamAId'), json_extract(\`version_source_data\`, '$.team_a_id'), CASE WHEN typeof(\`version_team_a_id\`) = 'text' THEN \`version_team_a_id\` END), \`version_source_team_b_id\` = COALESCE(json_extract(\`version_source_data\`, '$.teamBId'), json_extract(\`version_source_data\`, '$.team_b_id'), CASE WHEN typeof(\`version_team_b_id\`) = 'text' THEN \`version_team_b_id\` END), \`version_source_entry_a_id\` = COALESCE(json_extract(\`version_source_data\`, '$.entryAId'), json_extract(\`version_source_data\`, '$.entry_a_id'), CASE WHEN typeof(\`version_entry_a_id\`) = 'text' THEN \`version_entry_a_id\` END), \`version_source_entry_b_id\` = COALESCE(json_extract(\`version_source_data\`, '$.entryBId'), json_extract(\`version_source_data\`, '$.entry_b_id'), CASE WHEN typeof(\`version_entry_b_id\`) = 'text' THEN \`version_entry_b_id\` END), \`version_source_winner_team_id\` = COALESCE(json_extract(\`version_source_data\`, '$.winnerTeamId'), json_extract(\`version_source_data\`, '$.winner_team_id'), CASE WHEN typeof(\`version_winner_team_id\`) = 'text' THEN \`version_winner_team_id\` END), \`version_source_winner_entry_id\` = COALESCE(json_extract(\`version_source_data\`, '$.winnerEntryId'), json_extract(\`version_source_data\`, '$.winner_entry_id'), CASE WHEN typeof(\`version_winner_entry_id\`) = 'text' THEN \`version_winner_entry_id\` END) WHERE \`version_source_bracket_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_match_results_v\` SET \`version_source_match_id\` = COALESCE(json_extract(\`version_source_data\`, '$.matchId'), json_extract(\`version_source_data\`, '$.match_id'), CASE WHEN typeof(\`version_match_id\`) = 'text' THEN \`version_match_id\` END), \`version_source_winner_team_id\` = COALESCE(json_extract(\`version_source_data\`, '$.winnerTeamId'), json_extract(\`version_source_data\`, '$.winner_team_id'), CASE WHEN typeof(\`version_winner_team_id\`) = 'text' THEN \`version_winner_team_id\` END), \`version_source_winner_entry_id\` = COALESCE(json_extract(\`version_source_data\`, '$.winnerEntryId'), json_extract(\`version_source_data\`, '$.winner_entry_id'), CASE WHEN typeof(\`version_winner_entry_id\`) = 'text' THEN \`version_winner_entry_id\` END) WHERE \`version_source_match_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_registrations_v\` SET \`version_source_season_id\` = COALESCE(json_extract(\`version_source_data\`, '$.seasonId'), json_extract(\`version_source_data\`, '$.season_id'), CASE WHEN typeof(\`version_season_id\`) = 'text' THEN \`version_season_id\` END), \`version_source_bracket_id\` = COALESCE(json_extract(\`version_source_data\`, '$.bracketId'), json_extract(\`version_source_data\`, '$.bracket_id'), CASE WHEN typeof(\`version_bracket_id\`) = 'text' THEN \`version_bracket_id\` END) WHERE \`version_source_season_id\` IS NULL OR \`version_source_bracket_id\` IS NULL;`)
  // Recover source IDs from existing Payload relationship IDs when older rows
  // do not contain source JSON or stored text identifiers.
  await db.run(sql`UPDATE \`seasons\` SET \`source_show_id\` = COALESCE(\`source_show_id\`, (SELECT \`legacy_id\` FROM \`shows\` WHERE \`id\` = \`seasons\` . \`show_id\` LIMIT 1)) WHERE \`source_show_id\` IS NULL;`)
  await db.run(sql`UPDATE \`competitors\` SET \`source_season_id\` = COALESCE(\`source_season_id\`, (SELECT \`legacy_id\` FROM \`seasons\` WHERE \`id\` = \`competitors\` . \`season_id\` LIMIT 1)) WHERE \`source_season_id\` IS NULL;`)
  await db.run(sql`UPDATE \`brackets\` SET \`source_season_id\` = COALESCE(\`source_season_id\`, (SELECT \`legacy_id\` FROM \`seasons\` WHERE \`id\` = \`brackets\` . \`season_id\` LIMIT 1)) WHERE \`source_season_id\` IS NULL;`)
  await db.run(sql`UPDATE \`bracket_applications\` SET \`source_bracket_id\` = COALESCE(\`source_bracket_id\`, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`bracket_applications\` . \`bracket_id\` LIMIT 1)), \`source_competitor_id\` = COALESCE(\`source_competitor_id\`, (SELECT \`legacy_id\` FROM \`competitors\` WHERE \`id\` = \`bracket_applications\` . \`competitor_id\` LIMIT 1)) WHERE \`source_bracket_id\` IS NULL OR \`source_competitor_id\` IS NULL;`)
  await db.run(sql`UPDATE \`teams\` SET \`source_season_id\` = COALESCE(\`source_season_id\`, (SELECT \`legacy_id\` FROM \`seasons\` WHERE \`id\` = \`teams\` . \`season_id\` LIMIT 1)), \`source_bracket_id\` = COALESCE(\`source_bracket_id\`, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`teams\` . \`bracket_id\` LIMIT 1)) WHERE \`source_season_id\` IS NULL OR \`source_bracket_id\` IS NULL;`)
  await db.run(sql`UPDATE \`team_members\` SET \`source_team_id\` = COALESCE(\`source_team_id\`, (SELECT \`legacy_id\` FROM \`teams\` WHERE \`id\` = \`team_members\` . \`team_id\` LIMIT 1)), \`source_bracket_id\` = COALESCE(\`source_bracket_id\`, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`team_members\` . \`bracket_id\` LIMIT 1)), \`source_competitor_id\` = COALESCE(\`source_competitor_id\`, (SELECT \`legacy_id\` FROM \`competitors\` WHERE \`id\` = \`team_members\` . \`competitor_id\` LIMIT 1)) WHERE \`source_team_id\` IS NULL OR \`source_bracket_id\` IS NULL OR \`source_competitor_id\` IS NULL;`)
  await db.run(sql`UPDATE \`team_invites\` SET \`source_team_id\` = COALESCE(\`source_team_id\`, (SELECT \`legacy_id\` FROM \`teams\` WHERE \`id\` = \`team_invites\` . \`team_id\` LIMIT 1)), \`source_bracket_id\` = COALESCE(\`source_bracket_id\`, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`team_invites\` . \`bracket_id\` LIMIT 1)) WHERE \`source_team_id\` IS NULL OR \`source_bracket_id\` IS NULL;`)
  await db.run(sql`UPDATE \`bracket_breaks\` SET \`source_bracket_id\` = COALESCE(\`source_bracket_id\`, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`bracket_breaks\` . \`bracket_id\` LIMIT 1)) WHERE \`source_bracket_id\` IS NULL;`)
  await db.run(sql`UPDATE \`bracket_entries\` SET \`source_bracket_id\` = COALESCE(\`source_bracket_id\`, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`bracket_entries\` . \`bracket_id\` LIMIT 1)), \`source_competitor_id\` = COALESCE(\`source_competitor_id\`, (SELECT \`legacy_id\` FROM \`competitors\` WHERE \`id\` = \`bracket_entries\` . \`competitor_id\` LIMIT 1)), \`source_team_id\` = COALESCE(\`source_team_id\`, (SELECT \`legacy_id\` FROM \`teams\` WHERE \`id\` = \`bracket_entries\` . \`team_id\` LIMIT 1)) WHERE \`source_bracket_id\` IS NULL OR \`source_competitor_id\` IS NULL OR \`source_team_id\` IS NULL;`)
  await db.run(sql`UPDATE \`matches\` SET \`source_bracket_id\` = COALESCE(\`source_bracket_id\`, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`matches\` . \`bracket_id\` LIMIT 1)), \`source_team_a_id\` = COALESCE(\`source_team_a_id\`, (SELECT \`legacy_id\` FROM \`teams\` WHERE \`id\` = \`matches\` . \`team_a_id\` LIMIT 1)), \`source_team_b_id\` = COALESCE(\`source_team_b_id\`, (SELECT \`legacy_id\` FROM \`teams\` WHERE \`id\` = \`matches\` . \`team_b_id\` LIMIT 1)), \`source_entry_a_id\` = COALESCE(\`source_entry_a_id\`, (SELECT \`legacy_id\` FROM \`bracket_entries\` WHERE \`id\` = \`matches\` . \`entry_a_id\` LIMIT 1)), \`source_entry_b_id\` = COALESCE(\`source_entry_b_id\`, (SELECT \`legacy_id\` FROM \`bracket_entries\` WHERE \`id\` = \`matches\` . \`entry_b_id\` LIMIT 1)), \`source_winner_team_id\` = COALESCE(\`source_winner_team_id\`, (SELECT \`legacy_id\` FROM \`teams\` WHERE \`id\` = \`matches\` . \`winner_team_id\` LIMIT 1)), \`source_winner_entry_id\` = COALESCE(\`source_winner_entry_id\`, (SELECT \`legacy_id\` FROM \`bracket_entries\` WHERE \`id\` = \`matches\` . \`winner_entry_id\` LIMIT 1)) WHERE \`source_bracket_id\` IS NULL OR \`source_team_a_id\` IS NULL OR \`source_team_b_id\` IS NULL OR \`source_entry_a_id\` IS NULL OR \`source_entry_b_id\` IS NULL OR \`source_winner_team_id\` IS NULL OR \`source_winner_entry_id\` IS NULL;`)
  await db.run(sql`UPDATE \`match_results\` SET \`source_match_id\` = COALESCE(\`source_match_id\`, (SELECT \`legacy_id\` FROM \`matches\` WHERE \`id\` = \`match_results\` . \`match_id\` LIMIT 1)), \`source_winner_team_id\` = COALESCE(\`source_winner_team_id\`, (SELECT \`legacy_id\` FROM \`teams\` WHERE \`id\` = \`match_results\` . \`winner_team_id\` LIMIT 1)), \`source_winner_entry_id\` = COALESCE(\`source_winner_entry_id\`, (SELECT \`legacy_id\` FROM \`bracket_entries\` WHERE \`id\` = \`match_results\` . \`winner_entry_id\` LIMIT 1)) WHERE \`source_match_id\` IS NULL OR \`source_winner_team_id\` IS NULL OR \`source_winner_entry_id\` IS NULL;`)
  await db.run(sql`UPDATE \`registrations\` SET \`source_season_id\` = COALESCE(\`source_season_id\`, (SELECT \`legacy_id\` FROM \`seasons\` WHERE \`id\` = \`registrations\` . \`season_id\` LIMIT 1)), \`source_bracket_id\` = COALESCE(\`source_bracket_id\`, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`registrations\` . \`bracket_id\` LIMIT 1)) WHERE \`source_season_id\` IS NULL OR \`source_bracket_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_seasons_v\` SET \`version_source_show_id\` = COALESCE(\`version_source_show_id\`, (SELECT \`legacy_id\` FROM \`shows\` WHERE \`id\` = \`_seasons_v\` . \`version_show_id\` LIMIT 1)) WHERE \`version_source_show_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_competitors_v\` SET \`version_source_season_id\` = COALESCE(\`version_source_season_id\`, (SELECT \`legacy_id\` FROM \`seasons\` WHERE \`id\` = \`_competitors_v\` . \`version_season_id\` LIMIT 1)) WHERE \`version_source_season_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_brackets_v\` SET \`version_source_season_id\` = COALESCE(\`version_source_season_id\`, (SELECT \`legacy_id\` FROM \`seasons\` WHERE \`id\` = \`_brackets_v\` . \`version_season_id\` LIMIT 1)) WHERE \`version_source_season_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_bracket_applications_v\` SET \`version_source_bracket_id\` = COALESCE(\`version_source_bracket_id\`, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`_bracket_applications_v\` . \`version_bracket_id\` LIMIT 1)), \`version_source_competitor_id\` = COALESCE(\`version_source_competitor_id\`, (SELECT \`legacy_id\` FROM \`competitors\` WHERE \`id\` = \`_bracket_applications_v\` . \`version_competitor_id\` LIMIT 1)) WHERE \`version_source_bracket_id\` IS NULL OR \`version_source_competitor_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_teams_v\` SET \`version_source_season_id\` = COALESCE(\`version_source_season_id\`, (SELECT \`legacy_id\` FROM \`seasons\` WHERE \`id\` = \`_teams_v\` . \`version_season_id\` LIMIT 1)), \`version_source_bracket_id\` = COALESCE(\`version_source_bracket_id\`, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`_teams_v\` . \`version_bracket_id\` LIMIT 1)) WHERE \`version_source_season_id\` IS NULL OR \`version_source_bracket_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_team_members_v\` SET \`version_source_team_id\` = COALESCE(\`version_source_team_id\`, (SELECT \`legacy_id\` FROM \`teams\` WHERE \`id\` = \`_team_members_v\` . \`version_team_id\` LIMIT 1)), \`version_source_bracket_id\` = COALESCE(\`version_source_bracket_id\`, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`_team_members_v\` . \`version_bracket_id\` LIMIT 1)), \`version_source_competitor_id\` = COALESCE(\`version_source_competitor_id\`, (SELECT \`legacy_id\` FROM \`competitors\` WHERE \`id\` = \`_team_members_v\` . \`version_competitor_id\` LIMIT 1)) WHERE \`version_source_team_id\` IS NULL OR \`version_source_bracket_id\` IS NULL OR \`version_source_competitor_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_team_invites_v\` SET \`version_source_team_id\` = COALESCE(json_extract(\`version_source_data\`, '$.teamId'), json_extract(\`version_source_data\`, '$.team_id'), CASE WHEN typeof(\`version_team_id\`) = 'text' THEN \`version_team_id\` END, (SELECT \`legacy_id\` FROM \`teams\` WHERE \`id\` = \`_team_invites_v\` . \`version_team_id\` LIMIT 1)), \`version_source_bracket_id\` = COALESCE(json_extract(\`version_source_data\`, '$.bracketId'), json_extract(\`version_source_data\`, '$.bracket_id'), CASE WHEN typeof(\`version_bracket_id\`) = 'text' THEN \`version_bracket_id\` END, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`_team_invites_v\` . \`version_bracket_id\` LIMIT 1)) WHERE \`version_source_team_id\` IS NULL OR \`version_source_bracket_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_bracket_breaks_v\` SET \`version_source_bracket_id\` = COALESCE(json_extract(\`version_source_data\`, '$.bracketId'), json_extract(\`version_source_data\`, '$.bracket_id'), CASE WHEN typeof(\`version_bracket_id\`) = 'text' THEN \`version_bracket_id\` END, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`_bracket_breaks_v\` . \`version_bracket_id\` LIMIT 1)) WHERE \`version_source_bracket_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_bracket_entries_v\` SET \`version_source_bracket_id\` = COALESCE(\`version_source_bracket_id\`, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`_bracket_entries_v\` . \`version_bracket_id\` LIMIT 1)), \`version_source_competitor_id\` = COALESCE(\`version_source_competitor_id\`, (SELECT \`legacy_id\` FROM \`competitors\` WHERE \`id\` = \`_bracket_entries_v\` . \`version_competitor_id\` LIMIT 1)), \`version_source_team_id\` = COALESCE(\`version_source_team_id\`, (SELECT \`legacy_id\` FROM \`teams\` WHERE \`id\` = \`_bracket_entries_v\` . \`version_team_id\` LIMIT 1)) WHERE \`version_source_bracket_id\` IS NULL OR \`version_source_competitor_id\` IS NULL OR \`version_source_team_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_matches_v\` SET \`version_source_bracket_id\` = COALESCE(\`version_source_bracket_id\`, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`_matches_v\` . \`version_bracket_id\` LIMIT 1)), \`version_source_team_a_id\` = COALESCE(\`version_source_team_a_id\`, (SELECT \`legacy_id\` FROM \`teams\` WHERE \`id\` = \`_matches_v\` . \`version_team_a_id\` LIMIT 1)), \`version_source_team_b_id\` = COALESCE(\`version_source_team_b_id\`, (SELECT \`legacy_id\` FROM \`teams\` WHERE \`id\` = \`_matches_v\` . \`version_team_b_id\` LIMIT 1)), \`version_source_entry_a_id\` = COALESCE(\`version_source_entry_a_id\`, (SELECT \`legacy_id\` FROM \`bracket_entries\` WHERE \`id\` = \`_matches_v\` . \`version_entry_a_id\` LIMIT 1)), \`version_source_entry_b_id\` = COALESCE(\`version_source_entry_b_id\`, (SELECT \`legacy_id\` FROM \`bracket_entries\` WHERE \`id\` = \`_matches_v\` . \`version_entry_b_id\` LIMIT 1)), \`version_source_winner_team_id\` = COALESCE(\`version_source_winner_team_id\`, (SELECT \`legacy_id\` FROM \`teams\` WHERE \`id\` = \`_matches_v\` . \`version_winner_team_id\` LIMIT 1)), \`version_source_winner_entry_id\` = COALESCE(\`version_source_winner_entry_id\`, (SELECT \`legacy_id\` FROM \`bracket_entries\` WHERE \`id\` = \`_matches_v\` . \`version_winner_entry_id\` LIMIT 1)) WHERE \`version_source_bracket_id\` IS NULL OR \`version_source_team_a_id\` IS NULL OR \`version_source_team_b_id\` IS NULL OR \`version_source_entry_a_id\` IS NULL OR \`version_source_entry_b_id\` IS NULL OR \`version_source_winner_team_id\` IS NULL OR \`version_source_winner_entry_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_match_results_v\` SET \`version_source_match_id\` = COALESCE(\`version_source_match_id\`, (SELECT \`legacy_id\` FROM \`matches\` WHERE \`id\` = \`_match_results_v\` . \`version_match_id\` LIMIT 1)), \`version_source_winner_team_id\` = COALESCE(\`version_source_winner_team_id\`, (SELECT \`legacy_id\` FROM \`teams\` WHERE \`id\` = \`_match_results_v\` . \`version_winner_team_id\` LIMIT 1)), \`version_source_winner_entry_id\` = COALESCE(\`version_source_winner_entry_id\`, (SELECT \`legacy_id\` FROM \`bracket_entries\` WHERE \`id\` = \`_match_results_v\` . \`version_winner_entry_id\` LIMIT 1)) WHERE \`version_source_match_id\` IS NULL OR \`version_source_winner_team_id\` IS NULL OR \`version_source_winner_entry_id\` IS NULL;`)
  await db.run(sql`UPDATE \`_registrations_v\` SET \`version_source_season_id\` = COALESCE(\`version_source_season_id\`, (SELECT \`legacy_id\` FROM \`seasons\` WHERE \`id\` = \`_registrations_v\` . \`version_season_id\` LIMIT 1)), \`version_source_bracket_id\` = COALESCE(\`version_source_bracket_id\`, (SELECT \`legacy_id\` FROM \`brackets\` WHERE \`id\` = \`_registrations_v\` . \`version_bracket_id\` LIMIT 1)) WHERE \`version_source_season_id\` IS NULL OR \`version_source_bracket_id\` IS NULL;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`DROP INDEX \`sourceShowId_slug_idx\`;`)
  await db.run(sql`CREATE UNIQUE INDEX \`showId_slug_idx\` ON \`seasons\` (\`show_id\`,\`slug\`);`)
  await db.run(sql`ALTER TABLE \`seasons\` DROP COLUMN \`source_show_id\`;`)
  await db.run(sql`DROP INDEX \`version_sourceShowId_version_slug_idx\`;`)
  await db.run(sql`CREATE INDEX \`version_showId_version_slug_idx\` ON \`_seasons_v\` (\`version_show_id\`,\`version_slug\`);`)
  await db.run(sql`ALTER TABLE \`_seasons_v\` DROP COLUMN \`version_source_show_id\`;`)
  await db.run(sql`DROP INDEX \`sourceSeasonId_personSlug_idx\`;`)
  await db.run(sql`DROP INDEX \`sourceSeasonId_userId_idx\`;`)
  await db.run(sql`CREATE UNIQUE INDEX \`seasonId_personSlug_idx\` ON \`competitors\` (\`season_id\`,\`person_slug\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`seasonId_userId_idx\` ON \`competitors\` (\`season_id\`,\`user_id\`);`)
  await db.run(sql`ALTER TABLE \`competitors\` DROP COLUMN \`source_season_id\`;`)
  await db.run(sql`DROP INDEX \`version_sourceSeasonId_version_personSlug_idx\`;`)
  await db.run(sql`DROP INDEX \`version_sourceSeasonId_version_userId_idx\`;`)
  await db.run(sql`CREATE INDEX \`version_seasonId_version_personSlug_idx\` ON \`_competitors_v\` (\`version_season_id\`,\`version_person_slug\`);`)
  await db.run(sql`CREATE INDEX \`version_seasonId_version_userId_idx\` ON \`_competitors_v\` (\`version_season_id\`,\`version_user_id\`);`)
  await db.run(sql`ALTER TABLE \`_competitors_v\` DROP COLUMN \`version_source_season_id\`;`)
  await db.run(sql`DROP INDEX \`sourceSeasonId_slug_idx\`;`)
  await db.run(sql`CREATE UNIQUE INDEX \`seasonId_slug_idx\` ON \`brackets\` (\`season_id\`,\`slug\`);`)
  await db.run(sql`ALTER TABLE \`brackets\` DROP COLUMN \`source_season_id\`;`)
  await db.run(sql`DROP INDEX \`version_sourceSeasonId_version_slug_idx\`;`)
  await db.run(sql`CREATE INDEX \`version_seasonId_version_slug_idx\` ON \`_brackets_v\` (\`version_season_id\`,\`version_slug\`);`)
  await db.run(sql`ALTER TABLE \`_brackets_v\` DROP COLUMN \`version_source_season_id\`;`)
  await db.run(sql`DROP INDEX \`sourceBracketId_sourceCompetitorId_idx\`;`)
  await db.run(sql`CREATE UNIQUE INDEX \`bracketId_competitorId_idx\` ON \`bracket_applications\` (\`bracket_id\`,\`competitor_id\`);`)
  await db.run(sql`ALTER TABLE \`bracket_applications\` DROP COLUMN \`source_bracket_id\`;`)
  await db.run(sql`ALTER TABLE \`bracket_applications\` DROP COLUMN \`source_competitor_id\`;`)
  await db.run(sql`DROP INDEX \`version_sourceBracketId_version_sourceCompetitorId_idx\`;`)
  await db.run(sql`CREATE INDEX \`version_bracketId_version_competitorId_idx\` ON \`_bracket_applications_v\` (\`version_bracket_id\`,\`version_competitor_id\`);`)
  await db.run(sql`ALTER TABLE \`_bracket_applications_v\` DROP COLUMN \`version_source_bracket_id\`;`)
  await db.run(sql`ALTER TABLE \`_bracket_applications_v\` DROP COLUMN \`version_source_competitor_id\`;`)
  await db.run(sql`DROP INDEX \`sourceBracketId_slug_idx\`;`)
  await db.run(sql`CREATE UNIQUE INDEX \`bracketId_slug_idx\` ON \`teams\` (\`bracket_id\`,\`slug\`);`)
  await db.run(sql`ALTER TABLE \`teams\` DROP COLUMN \`source_season_id\`;`)
  await db.run(sql`ALTER TABLE \`teams\` DROP COLUMN \`source_bracket_id\`;`)
  await db.run(sql`DROP INDEX \`version_sourceBracketId_version_slug_idx\`;`)
  await db.run(sql`CREATE INDEX \`version_bracketId_version_slug_idx\` ON \`_teams_v\` (\`version_bracket_id\`,\`version_slug\`);`)
  await db.run(sql`ALTER TABLE \`_teams_v\` DROP COLUMN \`version_source_season_id\`;`)
  await db.run(sql`ALTER TABLE \`_teams_v\` DROP COLUMN \`version_source_bracket_id\`;`)
  await db.run(sql`DROP INDEX \`sourceTeamId_sourceCompetitorId_idx\`;`)
  await db.run(sql`DROP INDEX \`sourceBracketId_sourceCompetitorId_1_idx\`;`)
  await db.run(sql`CREATE UNIQUE INDEX \`teamId_competitorId_idx\` ON \`team_members\` (\`team_id\`,\`competitor_id\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`bracketId_competitorId_1_idx\` ON \`team_members\` (\`bracket_id\`,\`competitor_id\`);`)
  await db.run(sql`ALTER TABLE \`team_members\` DROP COLUMN \`source_team_id\`;`)
  await db.run(sql`ALTER TABLE \`team_members\` DROP COLUMN \`source_bracket_id\`;`)
  await db.run(sql`ALTER TABLE \`team_members\` DROP COLUMN \`source_competitor_id\`;`)
  await db.run(sql`DROP INDEX \`version_sourceTeamId_version_sourceCompetitorId_idx\`;`)
  await db.run(sql`DROP INDEX \`version_sourceBracketId_version_sourceCompetitorId_1_idx\`;`)
  await db.run(sql`CREATE INDEX \`version_teamId_version_competitorId_idx\` ON \`_team_members_v\` (\`version_team_id\`,\`version_competitor_id\`);`)
  await db.run(sql`CREATE INDEX \`version_bracketId_version_competitorId_1_idx\` ON \`_team_members_v\` (\`version_bracket_id\`,\`version_competitor_id\`);`)
  await db.run(sql`ALTER TABLE \`_team_members_v\` DROP COLUMN \`version_source_team_id\`;`)
  await db.run(sql`ALTER TABLE \`_team_members_v\` DROP COLUMN \`version_source_bracket_id\`;`)
  await db.run(sql`ALTER TABLE \`_team_members_v\` DROP COLUMN \`version_source_competitor_id\`;`)
  await db.run(sql`DROP INDEX \`sourceBracketId_seed_idx\`;`)
  await db.run(sql`DROP INDEX \`sourceBracketId_sourceCompetitorId_2_idx\`;`)
  await db.run(sql`DROP INDEX \`sourceBracketId_sourceTeamId_idx\`;`)
  await db.run(sql`CREATE UNIQUE INDEX \`bracketId_seed_idx\` ON \`bracket_entries\` (\`bracket_id\`,\`seed\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`bracketId_competitorId_2_idx\` ON \`bracket_entries\` (\`bracket_id\`,\`competitor_id\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`bracketId_teamId_idx\` ON \`bracket_entries\` (\`bracket_id\`,\`team_id\`);`)
  await db.run(sql`ALTER TABLE \`bracket_entries\` DROP COLUMN \`source_bracket_id\`;`)
  await db.run(sql`ALTER TABLE \`bracket_entries\` DROP COLUMN \`source_competitor_id\`;`)
  await db.run(sql`ALTER TABLE \`bracket_entries\` DROP COLUMN \`source_team_id\`;`)
  await db.run(sql`DROP INDEX \`version_sourceBracketId_version_seed_idx\`;`)
  await db.run(sql`DROP INDEX \`version_sourceBracketId_version_sourceCompetitorId_2_idx\`;`)
  await db.run(sql`DROP INDEX \`version_sourceBracketId_version_sourceTeamId_idx\`;`)
  await db.run(sql`CREATE INDEX \`version_bracketId_version_seed_idx\` ON \`_bracket_entries_v\` (\`version_bracket_id\`,\`version_seed\`);`)
  await db.run(sql`CREATE INDEX \`version_bracketId_version_competitorId_2_idx\` ON \`_bracket_entries_v\` (\`version_bracket_id\`,\`version_competitor_id\`);`)
  await db.run(sql`CREATE INDEX \`version_bracketId_version_teamId_idx\` ON \`_bracket_entries_v\` (\`version_bracket_id\`,\`version_team_id\`);`)
  await db.run(sql`ALTER TABLE \`_bracket_entries_v\` DROP COLUMN \`version_source_bracket_id\`;`)
  await db.run(sql`ALTER TABLE \`_bracket_entries_v\` DROP COLUMN \`version_source_competitor_id\`;`)
  await db.run(sql`ALTER TABLE \`_bracket_entries_v\` DROP COLUMN \`version_source_team_id\`;`)
  await db.run(sql`DROP INDEX \`sourceMatchId_idx\`;`)
  await db.run(sql`CREATE UNIQUE INDEX \`matchId_idx\` ON \`match_results\` (\`match_id\`);`)
  await db.run(sql`ALTER TABLE \`match_results\` DROP COLUMN \`source_match_id\`;`)
  await db.run(sql`ALTER TABLE \`match_results\` DROP COLUMN \`source_winner_team_id\`;`)
  await db.run(sql`ALTER TABLE \`match_results\` DROP COLUMN \`source_winner_entry_id\`;`)
  await db.run(sql`DROP INDEX \`version_sourceMatchId_idx\`;`)
  await db.run(sql`CREATE INDEX \`version_matchId_idx\` ON \`_match_results_v\` (\`version_match_id\`);`)
  await db.run(sql`ALTER TABLE \`_match_results_v\` DROP COLUMN \`version_source_match_id\`;`)
  await db.run(sql`ALTER TABLE \`_match_results_v\` DROP COLUMN \`version_source_winner_team_id\`;`)
  await db.run(sql`ALTER TABLE \`_match_results_v\` DROP COLUMN \`version_source_winner_entry_id\`;`)
  await db.run(sql`ALTER TABLE \`team_invites\` DROP COLUMN \`source_team_id\`;`)
  await db.run(sql`ALTER TABLE \`team_invites\` DROP COLUMN \`source_bracket_id\`;`)
  await db.run(sql`ALTER TABLE \`_team_invites_v\` DROP COLUMN \`version_source_team_id\`;`)
  await db.run(sql`ALTER TABLE \`_team_invites_v\` DROP COLUMN \`version_source_bracket_id\`;`)
  await db.run(sql`ALTER TABLE \`bracket_breaks\` DROP COLUMN \`source_bracket_id\`;`)
  await db.run(sql`ALTER TABLE \`_bracket_breaks_v\` DROP COLUMN \`version_source_bracket_id\`;`)
  await db.run(sql`ALTER TABLE \`matches\` DROP COLUMN \`source_bracket_id\`;`)
  await db.run(sql`ALTER TABLE \`matches\` DROP COLUMN \`source_team_a_id\`;`)
  await db.run(sql`ALTER TABLE \`matches\` DROP COLUMN \`source_team_b_id\`;`)
  await db.run(sql`ALTER TABLE \`matches\` DROP COLUMN \`source_entry_a_id\`;`)
  await db.run(sql`ALTER TABLE \`matches\` DROP COLUMN \`source_entry_b_id\`;`)
  await db.run(sql`ALTER TABLE \`matches\` DROP COLUMN \`source_winner_team_id\`;`)
  await db.run(sql`ALTER TABLE \`matches\` DROP COLUMN \`source_winner_entry_id\`;`)
  await db.run(sql`ALTER TABLE \`_matches_v\` DROP COLUMN \`version_source_bracket_id\`;`)
  await db.run(sql`ALTER TABLE \`_matches_v\` DROP COLUMN \`version_source_team_a_id\`;`)
  await db.run(sql`ALTER TABLE \`_matches_v\` DROP COLUMN \`version_source_team_b_id\`;`)
  await db.run(sql`ALTER TABLE \`_matches_v\` DROP COLUMN \`version_source_entry_a_id\`;`)
  await db.run(sql`ALTER TABLE \`_matches_v\` DROP COLUMN \`version_source_entry_b_id\`;`)
  await db.run(sql`ALTER TABLE \`_matches_v\` DROP COLUMN \`version_source_winner_team_id\`;`)
  await db.run(sql`ALTER TABLE \`_matches_v\` DROP COLUMN \`version_source_winner_entry_id\`;`)
  await db.run(sql`ALTER TABLE \`registrations\` DROP COLUMN \`source_season_id\`;`)
  await db.run(sql`ALTER TABLE \`registrations\` DROP COLUMN \`source_bracket_id\`;`)
  await db.run(sql`ALTER TABLE \`_registrations_v\` DROP COLUMN \`version_source_season_id\`;`)
  await db.run(sql`ALTER TABLE \`_registrations_v\` DROP COLUMN \`version_source_bracket_id\`;`)
}
