import { sql, type MigrateUpArgs, type MigrateDownArgs } from '@payloadcms/db-d1-sqlite'

// Remove only duplicate import payload and the obsolete collection discriminator.
// Import identity, source path/assets, source hashes and sequence metadata remain.
const drops = [
  'ALTER TABLE videos DROP COLUMN legacy_type',
  'ALTER TABLE videos DROP COLUMN source_format',
  'ALTER TABLE videos DROP COLUMN source_data',
  'ALTER TABLE videos DROP COLUMN source_raw',
  'ALTER TABLE videos DROP COLUMN source_body',
  'ALTER TABLE videos DROP COLUMN editorial_data',
  'ALTER TABLE _videos_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _videos_v DROP COLUMN version_source_format',
  'ALTER TABLE _videos_v DROP COLUMN version_source_data',
  'ALTER TABLE _videos_v DROP COLUMN version_source_raw',
  'ALTER TABLE _videos_v DROP COLUMN version_source_body',
  'ALTER TABLE _videos_v DROP COLUMN version_editorial_data',
  'ALTER TABLE people DROP COLUMN legacy_type',
  'ALTER TABLE people DROP COLUMN source_format',
  'ALTER TABLE people DROP COLUMN source_data',
  'ALTER TABLE people DROP COLUMN source_raw',
  'ALTER TABLE people DROP COLUMN source_body',
  'ALTER TABLE people DROP COLUMN editorial_data',
  'ALTER TABLE _people_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _people_v DROP COLUMN version_source_format',
  'ALTER TABLE _people_v DROP COLUMN version_source_data',
  'ALTER TABLE _people_v DROP COLUMN version_source_raw',
  'ALTER TABLE _people_v DROP COLUMN version_source_body',
  'ALTER TABLE _people_v DROP COLUMN version_editorial_data',
  'ALTER TABLE technologies DROP COLUMN legacy_type',
  'ALTER TABLE technologies DROP COLUMN source_format',
  'ALTER TABLE technologies DROP COLUMN source_data',
  'ALTER TABLE technologies DROP COLUMN source_raw',
  'ALTER TABLE technologies DROP COLUMN source_body',
  'ALTER TABLE technologies DROP COLUMN editorial_data',
  'ALTER TABLE _technologies_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _technologies_v DROP COLUMN version_source_format',
  'ALTER TABLE _technologies_v DROP COLUMN version_source_data',
  'ALTER TABLE _technologies_v DROP COLUMN version_source_raw',
  'ALTER TABLE _technologies_v DROP COLUMN version_source_body',
  'ALTER TABLE _technologies_v DROP COLUMN version_editorial_data',
  'ALTER TABLE shows DROP COLUMN legacy_type',
  'ALTER TABLE shows DROP COLUMN source_format',
  'ALTER TABLE shows DROP COLUMN source_data',
  'ALTER TABLE shows DROP COLUMN source_raw',
  'ALTER TABLE shows DROP COLUMN source_body',
  'ALTER TABLE shows DROP COLUMN editorial_data',
  'ALTER TABLE _shows_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _shows_v DROP COLUMN version_source_format',
  'ALTER TABLE _shows_v DROP COLUMN version_source_data',
  'ALTER TABLE _shows_v DROP COLUMN version_source_raw',
  'ALTER TABLE _shows_v DROP COLUMN version_source_body',
  'ALTER TABLE _shows_v DROP COLUMN version_editorial_data',
  'ALTER TABLE episodes DROP COLUMN legacy_type',
  'ALTER TABLE episodes DROP COLUMN source_format',
  'ALTER TABLE episodes DROP COLUMN source_data',
  'ALTER TABLE episodes DROP COLUMN source_raw',
  'ALTER TABLE episodes DROP COLUMN source_body',
  'ALTER TABLE episodes DROP COLUMN editorial_data',
  'ALTER TABLE _episodes_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _episodes_v DROP COLUMN version_source_format',
  'ALTER TABLE _episodes_v DROP COLUMN version_source_data',
  'ALTER TABLE _episodes_v DROP COLUMN version_source_raw',
  'ALTER TABLE _episodes_v DROP COLUMN version_source_body',
  'ALTER TABLE _episodes_v DROP COLUMN version_editorial_data',
  'ALTER TABLE chapters DROP COLUMN legacy_type',
  'ALTER TABLE chapters DROP COLUMN source_format',
  'ALTER TABLE chapters DROP COLUMN source_data',
  'ALTER TABLE chapters DROP COLUMN source_raw',
  'ALTER TABLE chapters DROP COLUMN source_body',
  'ALTER TABLE chapters DROP COLUMN editorial_data',
  'ALTER TABLE _chapters_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _chapters_v DROP COLUMN version_source_format',
  'ALTER TABLE _chapters_v DROP COLUMN version_source_data',
  'ALTER TABLE _chapters_v DROP COLUMN version_source_raw',
  'ALTER TABLE _chapters_v DROP COLUMN version_source_body',
  'ALTER TABLE _chapters_v DROP COLUMN version_editorial_data',
  'ALTER TABLE learning_resources DROP COLUMN legacy_type',
  'ALTER TABLE learning_resources DROP COLUMN source_format',
  'ALTER TABLE learning_resources DROP COLUMN source_data',
  'ALTER TABLE learning_resources DROP COLUMN source_raw',
  'ALTER TABLE learning_resources DROP COLUMN source_body',
  'ALTER TABLE learning_resources DROP COLUMN editorial_data',
  'ALTER TABLE _learning_resources_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _learning_resources_v DROP COLUMN version_source_format',
  'ALTER TABLE _learning_resources_v DROP COLUMN version_source_data',
  'ALTER TABLE _learning_resources_v DROP COLUMN version_source_raw',
  'ALTER TABLE _learning_resources_v DROP COLUMN version_source_body',
  'ALTER TABLE _learning_resources_v DROP COLUMN version_editorial_data',
  'ALTER TABLE articles DROP COLUMN legacy_type',
  'ALTER TABLE articles DROP COLUMN source_format',
  'ALTER TABLE articles DROP COLUMN source_data',
  'ALTER TABLE articles DROP COLUMN source_raw',
  'ALTER TABLE articles DROP COLUMN source_body',
  'ALTER TABLE articles DROP COLUMN editorial_data',
  'ALTER TABLE _articles_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _articles_v DROP COLUMN version_source_format',
  'ALTER TABLE _articles_v DROP COLUMN version_source_data',
  'ALTER TABLE _articles_v DROP COLUMN version_source_raw',
  'ALTER TABLE _articles_v DROP COLUMN version_source_body',
  'ALTER TABLE _articles_v DROP COLUMN version_editorial_data',
  'ALTER TABLE courses DROP COLUMN legacy_type',
  'ALTER TABLE courses DROP COLUMN source_format',
  'ALTER TABLE courses DROP COLUMN source_data',
  'ALTER TABLE courses DROP COLUMN source_raw',
  'ALTER TABLE courses DROP COLUMN source_body',
  'ALTER TABLE courses DROP COLUMN editorial_data',
  'ALTER TABLE _courses_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _courses_v DROP COLUMN version_source_format',
  'ALTER TABLE _courses_v DROP COLUMN version_source_data',
  'ALTER TABLE _courses_v DROP COLUMN version_source_raw',
  'ALTER TABLE _courses_v DROP COLUMN version_source_body',
  'ALTER TABLE _courses_v DROP COLUMN version_editorial_data',
  'ALTER TABLE course_modules DROP COLUMN legacy_type',
  'ALTER TABLE course_modules DROP COLUMN source_format',
  'ALTER TABLE course_modules DROP COLUMN source_data',
  'ALTER TABLE course_modules DROP COLUMN source_raw',
  'ALTER TABLE course_modules DROP COLUMN source_body',
  'ALTER TABLE course_modules DROP COLUMN editorial_data',
  'ALTER TABLE _course_modules_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _course_modules_v DROP COLUMN version_source_format',
  'ALTER TABLE _course_modules_v DROP COLUMN version_source_data',
  'ALTER TABLE _course_modules_v DROP COLUMN version_source_raw',
  'ALTER TABLE _course_modules_v DROP COLUMN version_source_body',
  'ALTER TABLE _course_modules_v DROP COLUMN version_editorial_data',
  'ALTER TABLE learning_paths DROP COLUMN legacy_type',
  'ALTER TABLE learning_paths DROP COLUMN source_format',
  'ALTER TABLE learning_paths DROP COLUMN source_data',
  'ALTER TABLE learning_paths DROP COLUMN source_raw',
  'ALTER TABLE learning_paths DROP COLUMN source_body',
  'ALTER TABLE learning_paths DROP COLUMN editorial_data',
  'ALTER TABLE _learning_paths_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _learning_paths_v DROP COLUMN version_source_format',
  'ALTER TABLE _learning_paths_v DROP COLUMN version_source_data',
  'ALTER TABLE _learning_paths_v DROP COLUMN version_source_raw',
  'ALTER TABLE _learning_paths_v DROP COLUMN version_source_body',
  'ALTER TABLE _learning_paths_v DROP COLUMN version_editorial_data',
  'ALTER TABLE series DROP COLUMN legacy_type',
  'ALTER TABLE series DROP COLUMN source_format',
  'ALTER TABLE series DROP COLUMN source_data',
  'ALTER TABLE series DROP COLUMN source_raw',
  'ALTER TABLE series DROP COLUMN source_body',
  'ALTER TABLE series DROP COLUMN editorial_data',
  'ALTER TABLE _series_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _series_v DROP COLUMN version_source_format',
  'ALTER TABLE _series_v DROP COLUMN version_source_data',
  'ALTER TABLE _series_v DROP COLUMN version_source_raw',
  'ALTER TABLE _series_v DROP COLUMN version_source_body',
  'ALTER TABLE _series_v DROP COLUMN version_editorial_data',
  'ALTER TABLE adrs DROP COLUMN legacy_type',
  'ALTER TABLE adrs DROP COLUMN source_format',
  'ALTER TABLE adrs DROP COLUMN source_data',
  'ALTER TABLE adrs DROP COLUMN source_raw',
  'ALTER TABLE adrs DROP COLUMN source_body',
  'ALTER TABLE adrs DROP COLUMN editorial_data',
  'ALTER TABLE _adrs_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _adrs_v DROP COLUMN version_source_format',
  'ALTER TABLE _adrs_v DROP COLUMN version_source_data',
  'ALTER TABLE _adrs_v DROP COLUMN version_source_raw',
  'ALTER TABLE _adrs_v DROP COLUMN version_source_body',
  'ALTER TABLE _adrs_v DROP COLUMN version_editorial_data',
  'ALTER TABLE testimonials DROP COLUMN legacy_type',
  'ALTER TABLE testimonials DROP COLUMN source_format',
  'ALTER TABLE testimonials DROP COLUMN source_data',
  'ALTER TABLE testimonials DROP COLUMN source_raw',
  'ALTER TABLE testimonials DROP COLUMN source_body',
  'ALTER TABLE testimonials DROP COLUMN editorial_data',
  'ALTER TABLE _testimonials_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _testimonials_v DROP COLUMN version_source_format',
  'ALTER TABLE _testimonials_v DROP COLUMN version_source_data',
  'ALTER TABLE _testimonials_v DROP COLUMN version_source_raw',
  'ALTER TABLE _testimonials_v DROP COLUMN version_source_body',
  'ALTER TABLE _testimonials_v DROP COLUMN version_editorial_data',
  'ALTER TABLE news DROP COLUMN legacy_type',
  'ALTER TABLE news DROP COLUMN source_format',
  'ALTER TABLE news DROP COLUMN source_data',
  'ALTER TABLE news DROP COLUMN source_raw',
  'ALTER TABLE news DROP COLUMN source_body',
  'ALTER TABLE news DROP COLUMN editorial_data',
  'ALTER TABLE _news_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _news_v DROP COLUMN version_source_format',
  'ALTER TABLE _news_v DROP COLUMN version_source_data',
  'ALTER TABLE _news_v DROP COLUMN version_source_raw',
  'ALTER TABLE _news_v DROP COLUMN version_source_body',
  'ALTER TABLE _news_v DROP COLUMN version_editorial_data',
  'ALTER TABLE changelog DROP COLUMN legacy_type',
  'ALTER TABLE changelog DROP COLUMN source_format',
  'ALTER TABLE changelog DROP COLUMN source_data',
  'ALTER TABLE changelog DROP COLUMN source_raw',
  'ALTER TABLE changelog DROP COLUMN source_body',
  'ALTER TABLE changelog DROP COLUMN editorial_data',
  'ALTER TABLE _changelog_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _changelog_v DROP COLUMN version_source_format',
  'ALTER TABLE _changelog_v DROP COLUMN version_source_data',
  'ALTER TABLE _changelog_v DROP COLUMN version_source_raw',
  'ALTER TABLE _changelog_v DROP COLUMN version_source_body',
  'ALTER TABLE _changelog_v DROP COLUMN version_editorial_data',
  'ALTER TABLE seasons DROP COLUMN legacy_type',
  'ALTER TABLE seasons DROP COLUMN source_format',
  'ALTER TABLE seasons DROP COLUMN source_data',
  'ALTER TABLE seasons DROP COLUMN source_raw',
  'ALTER TABLE seasons DROP COLUMN source_body',
  'ALTER TABLE _seasons_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _seasons_v DROP COLUMN version_source_format',
  'ALTER TABLE _seasons_v DROP COLUMN version_source_data',
  'ALTER TABLE _seasons_v DROP COLUMN version_source_raw',
  'ALTER TABLE _seasons_v DROP COLUMN version_source_body',
  'ALTER TABLE competitors DROP COLUMN legacy_type',
  'ALTER TABLE competitors DROP COLUMN source_format',
  'ALTER TABLE competitors DROP COLUMN source_data',
  'ALTER TABLE competitors DROP COLUMN source_raw',
  'ALTER TABLE competitors DROP COLUMN source_body',
  'ALTER TABLE _competitors_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _competitors_v DROP COLUMN version_source_format',
  'ALTER TABLE _competitors_v DROP COLUMN version_source_data',
  'ALTER TABLE _competitors_v DROP COLUMN version_source_raw',
  'ALTER TABLE _competitors_v DROP COLUMN version_source_body',
  'ALTER TABLE brackets DROP COLUMN legacy_type',
  'ALTER TABLE brackets DROP COLUMN source_format',
  'ALTER TABLE brackets DROP COLUMN source_data',
  'ALTER TABLE brackets DROP COLUMN source_raw',
  'ALTER TABLE brackets DROP COLUMN source_body',
  'ALTER TABLE _brackets_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _brackets_v DROP COLUMN version_source_format',
  'ALTER TABLE _brackets_v DROP COLUMN version_source_data',
  'ALTER TABLE _brackets_v DROP COLUMN version_source_raw',
  'ALTER TABLE _brackets_v DROP COLUMN version_source_body',
  'ALTER TABLE bracket_applications DROP COLUMN legacy_type',
  'ALTER TABLE bracket_applications DROP COLUMN source_format',
  'ALTER TABLE bracket_applications DROP COLUMN source_data',
  'ALTER TABLE bracket_applications DROP COLUMN source_raw',
  'ALTER TABLE bracket_applications DROP COLUMN source_body',
  'ALTER TABLE _bracket_applications_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _bracket_applications_v DROP COLUMN version_source_format',
  'ALTER TABLE _bracket_applications_v DROP COLUMN version_source_data',
  'ALTER TABLE _bracket_applications_v DROP COLUMN version_source_raw',
  'ALTER TABLE _bracket_applications_v DROP COLUMN version_source_body',
  'ALTER TABLE teams DROP COLUMN legacy_type',
  'ALTER TABLE teams DROP COLUMN source_format',
  'ALTER TABLE teams DROP COLUMN source_data',
  'ALTER TABLE teams DROP COLUMN source_raw',
  'ALTER TABLE teams DROP COLUMN source_body',
  'ALTER TABLE _teams_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _teams_v DROP COLUMN version_source_format',
  'ALTER TABLE _teams_v DROP COLUMN version_source_data',
  'ALTER TABLE _teams_v DROP COLUMN version_source_raw',
  'ALTER TABLE _teams_v DROP COLUMN version_source_body',
  'ALTER TABLE team_members DROP COLUMN legacy_type',
  'ALTER TABLE team_members DROP COLUMN source_format',
  'ALTER TABLE team_members DROP COLUMN source_data',
  'ALTER TABLE team_members DROP COLUMN source_raw',
  'ALTER TABLE team_members DROP COLUMN source_body',
  'ALTER TABLE _team_members_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _team_members_v DROP COLUMN version_source_format',
  'ALTER TABLE _team_members_v DROP COLUMN version_source_data',
  'ALTER TABLE _team_members_v DROP COLUMN version_source_raw',
  'ALTER TABLE _team_members_v DROP COLUMN version_source_body',
  'ALTER TABLE team_invites DROP COLUMN legacy_type',
  'ALTER TABLE team_invites DROP COLUMN source_format',
  'ALTER TABLE team_invites DROP COLUMN source_data',
  'ALTER TABLE team_invites DROP COLUMN source_raw',
  'ALTER TABLE team_invites DROP COLUMN source_body',
  'ALTER TABLE _team_invites_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _team_invites_v DROP COLUMN version_source_format',
  'ALTER TABLE _team_invites_v DROP COLUMN version_source_data',
  'ALTER TABLE _team_invites_v DROP COLUMN version_source_raw',
  'ALTER TABLE _team_invites_v DROP COLUMN version_source_body',
  'ALTER TABLE bracket_breaks DROP COLUMN legacy_type',
  'ALTER TABLE bracket_breaks DROP COLUMN source_format',
  'ALTER TABLE bracket_breaks DROP COLUMN source_data',
  'ALTER TABLE bracket_breaks DROP COLUMN source_raw',
  'ALTER TABLE bracket_breaks DROP COLUMN source_body',
  'ALTER TABLE _bracket_breaks_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _bracket_breaks_v DROP COLUMN version_source_format',
  'ALTER TABLE _bracket_breaks_v DROP COLUMN version_source_data',
  'ALTER TABLE _bracket_breaks_v DROP COLUMN version_source_raw',
  'ALTER TABLE _bracket_breaks_v DROP COLUMN version_source_body',
  'ALTER TABLE bracket_entries DROP COLUMN legacy_type',
  'ALTER TABLE bracket_entries DROP COLUMN source_format',
  'ALTER TABLE bracket_entries DROP COLUMN source_data',
  'ALTER TABLE bracket_entries DROP COLUMN source_raw',
  'ALTER TABLE bracket_entries DROP COLUMN source_body',
  'ALTER TABLE _bracket_entries_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _bracket_entries_v DROP COLUMN version_source_format',
  'ALTER TABLE _bracket_entries_v DROP COLUMN version_source_data',
  'ALTER TABLE _bracket_entries_v DROP COLUMN version_source_raw',
  'ALTER TABLE _bracket_entries_v DROP COLUMN version_source_body',
  'ALTER TABLE matches DROP COLUMN legacy_type',
  'ALTER TABLE matches DROP COLUMN source_format',
  'ALTER TABLE matches DROP COLUMN source_data',
  'ALTER TABLE matches DROP COLUMN source_raw',
  'ALTER TABLE matches DROP COLUMN source_body',
  'ALTER TABLE _matches_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _matches_v DROP COLUMN version_source_format',
  'ALTER TABLE _matches_v DROP COLUMN version_source_data',
  'ALTER TABLE _matches_v DROP COLUMN version_source_raw',
  'ALTER TABLE _matches_v DROP COLUMN version_source_body',
  'ALTER TABLE match_results DROP COLUMN legacy_type',
  'ALTER TABLE match_results DROP COLUMN source_format',
  'ALTER TABLE match_results DROP COLUMN source_data',
  'ALTER TABLE match_results DROP COLUMN source_raw',
  'ALTER TABLE match_results DROP COLUMN source_body',
  'ALTER TABLE _match_results_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _match_results_v DROP COLUMN version_source_format',
  'ALTER TABLE _match_results_v DROP COLUMN version_source_data',
  'ALTER TABLE _match_results_v DROP COLUMN version_source_raw',
  'ALTER TABLE _match_results_v DROP COLUMN version_source_body',
  'ALTER TABLE registrations DROP COLUMN legacy_type',
  'ALTER TABLE registrations DROP COLUMN source_format',
  'ALTER TABLE registrations DROP COLUMN source_data',
  'ALTER TABLE registrations DROP COLUMN source_raw',
  'ALTER TABLE registrations DROP COLUMN source_body',
  'ALTER TABLE _registrations_v DROP COLUMN version_legacy_type',
  'ALTER TABLE _registrations_v DROP COLUMN version_source_format',
  'ALTER TABLE _registrations_v DROP COLUMN version_source_data',
  'ALTER TABLE _registrations_v DROP COLUMN version_source_raw',
  'ALTER TABLE _registrations_v DROP COLUMN version_source_body',
] as const

const videoSourceIdentity = [
  'DROP INDEX videos_legacy_id_idx',
  'ALTER TABLE videos DROP COLUMN legacy_id',
  'DROP INDEX _videos_v_version_version_legacy_id_idx',
  'ALTER TABLE _videos_v DROP COLUMN version_legacy_id',
] as const

// static-assets was the one collection whose historical schema made its
// import key required. Rebuild its two tables so editor-created assets can
// omit the optional key while keeping all existing asset/version rows.
const rebuildStaticAssets = [
  `CREATE TABLE static_assets_new (
    id text PRIMARY KEY NOT NULL,
    legacy_id text,
    slug text NOT NULL,
    source_system text,
    source_revision text,
    source_hash text,
    mapping_version text,
    imported_at text,
    import_state text,
    locally_edited integer DEFAULT true,
    source_fields text,
    source_sequence numeric,
    source_order numeric DEFAULT 0,
    source_path text,
    source_assets text,
    tombstone integer DEFAULT false,
    r2_key text,
    mime_type text,
    bytes numeric,
    checksum text,
    alt text,
    updated_at text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    created_at text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
  )`,
  `INSERT INTO static_assets_new (id,legacy_id,slug,source_system,source_revision,source_hash,mapping_version,imported_at,import_state,locally_edited,source_fields,source_sequence,source_order,source_path,source_assets,tombstone,r2_key,mime_type,bytes,checksum,alt,updated_at,created_at)
    SELECT id,legacy_id,slug,source_system,source_revision,source_hash,mapping_version,imported_at,import_state,locally_edited,source_fields,source_sequence,source_order,source_path,source_assets,tombstone,r2_key,mime_type,bytes,checksum,alt,updated_at,created_at FROM static_assets`,
  `CREATE TABLE _static_assets_v_new (
    id integer PRIMARY KEY NOT NULL,
    parent_id text REFERENCES static_assets_new(id) ON UPDATE no action ON DELETE set null,
    version_legacy_id text,
    version_slug text NOT NULL,
    version_source_system text,
    version_source_revision text,
    version_source_hash text,
    version_mapping_version text,
    version_imported_at text,
    version_import_state text,
    version_locally_edited integer DEFAULT true,
    version_source_fields text,
    version_source_sequence numeric,
    version_source_order numeric DEFAULT 0,
    version_source_path text,
    version_source_assets text,
    version_tombstone integer DEFAULT false,
    version_r2_key text,
    version_mime_type text,
    version_bytes numeric,
    version_checksum text,
    version_alt text,
    version_updated_at text,
    version_created_at text,
    created_at text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
    updated_at text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
  )`,
  `INSERT INTO _static_assets_v_new (id,parent_id,version_legacy_id,version_slug,version_source_system,version_source_revision,version_source_hash,version_mapping_version,version_imported_at,version_import_state,version_locally_edited,version_source_fields,version_source_sequence,version_source_order,version_source_path,version_source_assets,version_tombstone,version_r2_key,version_mime_type,version_bytes,version_checksum,version_alt,version_updated_at,version_created_at,created_at,updated_at)
    SELECT id,parent_id,version_legacy_id,version_slug,version_source_system,version_source_revision,version_source_hash,version_mapping_version,version_imported_at,version_import_state,version_locally_edited,version_source_fields,version_source_sequence,version_source_order,version_source_path,version_source_assets,version_tombstone,version_r2_key,version_mime_type,version_bytes,version_checksum,version_alt,version_updated_at,version_created_at,created_at,updated_at FROM _static_assets_v`,
  // Dropping the old parent cascades these optional Payload lock relationships.
  // Preserve them so rekeying the table name does not release editor locks.
  'CREATE TABLE static_assets_lock_rels_backup AS SELECT * FROM payload_locked_documents_rels WHERE static_assets_id IS NOT NULL',
  'DROP TABLE _static_assets_v',
  'DROP TABLE static_assets',
  'ALTER TABLE static_assets_new RENAME TO static_assets',
  'ALTER TABLE _static_assets_v_new RENAME TO _static_assets_v',
  'INSERT INTO payload_locked_documents_rels SELECT * FROM static_assets_lock_rels_backup',
  'DROP TABLE static_assets_lock_rels_backup',
  'CREATE UNIQUE INDEX static_assets_legacy_id_idx ON static_assets(legacy_id)',
  'CREATE INDEX static_assets_slug_idx ON static_assets(slug)',
  'CREATE INDEX static_assets_updated_at_idx ON static_assets(updated_at)',
  'CREATE INDEX static_assets_created_at_idx ON static_assets(created_at)',
  'CREATE INDEX _static_assets_v_parent_idx ON _static_assets_v(parent_id)',
  'CREATE INDEX _static_assets_v_version_version_legacy_id_idx ON _static_assets_v(version_legacy_id)',
  'CREATE INDEX _static_assets_v_version_version_slug_idx ON _static_assets_v(version_slug)',
  'CREATE INDEX _static_assets_v_version_version_updated_at_idx ON _static_assets_v(version_updated_at)',
  'CREATE INDEX _static_assets_v_version_version_created_at_idx ON _static_assets_v(version_created_at)',
  'CREATE INDEX _static_assets_v_created_at_idx ON _static_assets_v(created_at)',
  'CREATE INDEX _static_assets_v_updated_at_idx ON _static_assets_v(updated_at)',
] as const

export async function up({ db }: MigrateUpArgs) {
  for (const statement of rebuildStaticAssets) await db.run(sql.raw(statement))
  for (const statement of videoSourceIdentity) await db.run(sql.raw(statement))
  for (const statement of drops) await db.run(sql.raw(statement))
}

export async function down(_args: MigrateDownArgs) {
  throw new Error('content schema cleanup intentionally drops duplicate source payload; restore from the preserved pre-cutover database instead of rolling this migration back')
}
