import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`videos\` ADD \`source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`_videos_v\` ADD \`version_source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`people\` ADD \`source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`_people_v\` ADD \`version_source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`technologies\` ADD \`source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`_technologies_v\` ADD \`version_source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`shows\` ADD \`source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`_shows_v\` ADD \`version_source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`episodes\` ADD \`source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`_episodes_v\` ADD \`version_source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`chapters\` ADD \`source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`_chapters_v\` ADD \`version_source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`learning_resources\` ADD \`source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`_learning_resources_v\` ADD \`version_source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`articles\` ADD \`source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`_articles_v\` ADD \`version_source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`courses\` ADD \`source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`_courses_v\` ADD \`version_source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`course_modules\` ADD \`source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`_course_modules_v\` ADD \`version_source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`learning_paths\` ADD \`source_fields\` text;`)
  await db.run(sql`ALTER TABLE \`_learning_paths_v\` ADD \`version_source_fields\` text;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`videos\` DROP COLUMN \`source_fields\`;`)
  await db.run(sql`ALTER TABLE \`_videos_v\` DROP COLUMN \`version_source_fields\`;`)
  await db.run(sql`ALTER TABLE \`people\` DROP COLUMN \`source_fields\`;`)
  await db.run(sql`ALTER TABLE \`_people_v\` DROP COLUMN \`version_source_fields\`;`)
  await db.run(sql`ALTER TABLE \`technologies\` DROP COLUMN \`source_fields\`;`)
  await db.run(sql`ALTER TABLE \`_technologies_v\` DROP COLUMN \`version_source_fields\`;`)
  await db.run(sql`ALTER TABLE \`shows\` DROP COLUMN \`source_fields\`;`)
  await db.run(sql`ALTER TABLE \`_shows_v\` DROP COLUMN \`version_source_fields\`;`)
  await db.run(sql`ALTER TABLE \`episodes\` DROP COLUMN \`source_fields\`;`)
  await db.run(sql`ALTER TABLE \`_episodes_v\` DROP COLUMN \`version_source_fields\`;`)
  await db.run(sql`ALTER TABLE \`chapters\` DROP COLUMN \`source_fields\`;`)
  await db.run(sql`ALTER TABLE \`_chapters_v\` DROP COLUMN \`version_source_fields\`;`)
  await db.run(sql`ALTER TABLE \`learning_resources\` DROP COLUMN \`source_fields\`;`)
  await db.run(sql`ALTER TABLE \`_learning_resources_v\` DROP COLUMN \`version_source_fields\`;`)
  await db.run(sql`ALTER TABLE \`articles\` DROP COLUMN \`source_fields\`;`)
  await db.run(sql`ALTER TABLE \`_articles_v\` DROP COLUMN \`version_source_fields\`;`)
  await db.run(sql`ALTER TABLE \`courses\` DROP COLUMN \`source_fields\`;`)
  await db.run(sql`ALTER TABLE \`_courses_v\` DROP COLUMN \`version_source_fields\`;`)
  await db.run(sql`ALTER TABLE \`course_modules\` DROP COLUMN \`source_fields\`;`)
  await db.run(sql`ALTER TABLE \`_course_modules_v\` DROP COLUMN \`version_source_fields\`;`)
  await db.run(sql`ALTER TABLE \`learning_paths\` DROP COLUMN \`source_fields\`;`)
  await db.run(sql`ALTER TABLE \`_learning_paths_v\` DROP COLUMN \`version_source_fields\`;`)
}
