import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`CREATE UNIQUE INDEX \`show_slug_idx\` ON \`seasons\` (\`show_id\`,\`slug\`);`)
  await db.run(sql`CREATE INDEX \`version_show_version_slug_idx\` ON \`_seasons_v\` (\`version_show_id\`,\`version_slug\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`season_personSlug_idx\` ON \`competitors\` (\`season_id\`,\`person_slug\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`season_userId_idx\` ON \`competitors\` (\`season_id\`,\`user_id\`);`)
  await db.run(sql`CREATE INDEX \`version_season_version_personSlug_idx\` ON \`_competitors_v\` (\`version_season_id\`,\`version_person_slug\`);`)
  await db.run(sql`CREATE INDEX \`version_season_version_userId_idx\` ON \`_competitors_v\` (\`version_season_id\`,\`version_user_id\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`season_slug_idx\` ON \`brackets\` (\`season_id\`,\`slug\`);`)
  await db.run(sql`CREATE INDEX \`version_season_version_slug_idx\` ON \`_brackets_v\` (\`version_season_id\`,\`version_slug\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`bracket_competitor_idx\` ON \`bracket_applications\` (\`bracket_id\`,\`competitor_id\`);`)
  await db.run(sql`CREATE INDEX \`version_bracket_version_competitor_idx\` ON \`_bracket_applications_v\` (\`version_bracket_id\`,\`version_competitor_id\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`bracket_slug_idx\` ON \`teams\` (\`bracket_id\`,\`slug\`);`)
  await db.run(sql`CREATE INDEX \`version_bracket_version_slug_idx\` ON \`_teams_v\` (\`version_bracket_id\`,\`version_slug\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`team_competitor_idx\` ON \`team_members\` (\`team_id\`,\`competitor_id\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`bracket_competitor_1_idx\` ON \`team_members\` (\`bracket_id\`,\`competitor_id\`);`)
  await db.run(sql`CREATE INDEX \`version_team_version_competitor_idx\` ON \`_team_members_v\` (\`version_team_id\`,\`version_competitor_id\`);`)
  await db.run(sql`CREATE INDEX \`version_bracket_version_competitor_1_idx\` ON \`_team_members_v\` (\`version_bracket_id\`,\`version_competitor_id\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`bracket_seed_idx\` ON \`bracket_entries\` (\`bracket_id\`,\`seed\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`bracket_competitor_2_idx\` ON \`bracket_entries\` (\`bracket_id\`,\`competitor_id\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`bracket_team_idx\` ON \`bracket_entries\` (\`bracket_id\`,\`team_id\`);`)
  await db.run(sql`CREATE INDEX \`version_bracket_version_seed_idx\` ON \`_bracket_entries_v\` (\`version_bracket_id\`,\`version_seed\`);`)
  await db.run(sql`CREATE INDEX \`version_bracket_version_competitor_2_idx\` ON \`_bracket_entries_v\` (\`version_bracket_id\`,\`version_competitor_id\`);`)
  await db.run(sql`CREATE INDEX \`version_bracket_version_team_idx\` ON \`_bracket_entries_v\` (\`version_bracket_id\`,\`version_team_id\`);`)
  await db.run(sql`CREATE UNIQUE INDEX \`match_idx\` ON \`match_results\` (\`match_id\`);`)
  await db.run(sql`CREATE INDEX \`version_match_idx\` ON \`_match_results_v\` (\`version_match_id\`);`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`DROP INDEX \`show_slug_idx\`;`)
  await db.run(sql`DROP INDEX \`version_show_version_slug_idx\`;`)
  await db.run(sql`DROP INDEX \`season_personSlug_idx\`;`)
  await db.run(sql`DROP INDEX \`season_userId_idx\`;`)
  await db.run(sql`DROP INDEX \`version_season_version_personSlug_idx\`;`)
  await db.run(sql`DROP INDEX \`version_season_version_userId_idx\`;`)
  await db.run(sql`DROP INDEX \`season_slug_idx\`;`)
  await db.run(sql`DROP INDEX \`version_season_version_slug_idx\`;`)
  await db.run(sql`DROP INDEX \`bracket_competitor_idx\`;`)
  await db.run(sql`DROP INDEX \`version_bracket_version_competitor_idx\`;`)
  await db.run(sql`DROP INDEX \`bracket_slug_idx\`;`)
  await db.run(sql`DROP INDEX \`version_bracket_version_slug_idx\`;`)
  await db.run(sql`DROP INDEX \`team_competitor_idx\`;`)
  await db.run(sql`DROP INDEX \`bracket_competitor_1_idx\`;`)
  await db.run(sql`DROP INDEX \`version_team_version_competitor_idx\`;`)
  await db.run(sql`DROP INDEX \`version_bracket_version_competitor_1_idx\`;`)
  await db.run(sql`DROP INDEX \`bracket_seed_idx\`;`)
  await db.run(sql`DROP INDEX \`bracket_competitor_2_idx\`;`)
  await db.run(sql`DROP INDEX \`bracket_team_idx\`;`)
  await db.run(sql`DROP INDEX \`version_bracket_version_seed_idx\`;`)
  await db.run(sql`DROP INDEX \`version_bracket_version_competitor_2_idx\`;`)
  await db.run(sql`DROP INDEX \`version_bracket_version_team_idx\`;`)
  await db.run(sql`DROP INDEX \`match_idx\`;`)
  await db.run(sql`DROP INDEX \`version_match_idx\`;`)
}
