/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/cloudflare-env.d.ts` (hash: 50d282b47443694ee1c6656a563b45fe)
interface __BaseEnv_Env {
	DB: D1Database;
	BRACKETS: D1Database;
	ASSETS: Fetcher;
	BRACKETS_WRITE: Fetcher /* platform-brackets-write-model */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
