/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/cloudflare-env.d.ts` (hash: b8818b98a29088940f93390019586c95)
interface __BaseEnv_Env {
	SESSION: KVNamespace;
	BRACKETS: D1Database;
	ASSETS: Fetcher;
	KLUSTERED_ADMIN_IDS: "HmYDQjc3JVFo7visJIL5FneGFzNAJjDT";
	BRACKETS_WRITE: Fetcher /* platform-brackets-write-model */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "KLUSTERED_ADMIN_IDS">> {}
}
