apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: comtrya-server-secrets
  namespace: code-rawkode-academy
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: comtrya-server-secrets
    creationPolicy: Owner
  data:
    - secretKey: COMTRYA_OPERATOR_CODE
      remoteRef:
        key: /projects/code-rawkode-academy/COMTRYA_OPERATOR_CODE
