apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: code-rawkode-academy
resources:
  - github.com/comtrya/comtrya/opt/kubernetes/base?ref=188af77c7c401d3fbef39878fde02e66a88818f7
  - namespace.yaml
  - external-secret.yaml
  - httproute.yaml

images:
  - name: ghcr.io/comtrya/comtrya-server
    digest: sha256:5e0195724f8ac307b592c8d3738dea8ac9b6a7ad9aeff3480d98ac634bff3a1b
  - name: ghcr.io/comtrya/comtrya-frontend
    digest: sha256:0cad7c6c29bc6877580fb98b7b274856a600ace4dcd5fecd06eaaaaac7b17262

patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: comtrya
      $patch: delete
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: comtrya-server-secrets
      $patch: delete
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: comtrya-server-config
      data:
        COMTRYA_CONFIG_REPO_URL: https://codeberg.org/rawkode-academy/comtrya
        COMTRYA_CONFIG_REPO_REF: main
        COMTRYA_CONFIG_REPO_PATH: ""
        COMTRYA_CONFIG_REPO_USERNAME: null
  - patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: comtrya-data
      spec:
        storageClassName: openebs-single-replica
        resources:
          requests:
            storage: 20Gi
