apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: code-rawkode-academy
resources:
  - github.com/comtrya/comtrya/opt/kubernetes/base?ref=a11ec753dcde03b11c81df4422d6bca40057c911
  - namespace.yaml
  - external-secret.yaml
  - httproute.yaml

images:
  - name: ghcr.io/comtrya/comtrya-server
    digest: sha256:eaa41487af2cb5906f017ceb4073e614df089a1ae158221810c2aabfe7db1261
  - name: ghcr.io/comtrya/comtrya-frontend
    digest: sha256:c608a6baaf2893dd9ec5453110cf14a5355afafc60efa41a7dea425d87ccfb29

patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: comtrya
      $patch: delete
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: comtrya-server-secrets
      $patch: delete
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: comtrya-server-config
      data:
        COMTRYA_CONFIG_REPO_URL: https://codeberg.org/rawkode-academy/comtrya
        COMTRYA_CONFIG_REPO_REF: main
        COMTRYA_CONFIG_REPO_PATH: ""
        COMTRYA_CONFIG_REPO_USERNAME: null
  - patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: comtrya-data
      spec:
        storageClassName: openebs-single-replica
        resources:
          requests:
            storage: 20Gi
