apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: code-rawkode-academy
resources:
  - github.com/comtrya/comtrya/opt/kubernetes/base?ref=4659865d49577b5269b394f315ee95737ff0aad6
  - namespace.yaml
  - external-secret.yaml
  - httproute.yaml

images:
  - name: ghcr.io/comtrya/comtrya-server
    digest: sha256:c2cd9856b08c3b8ab0fe27b85809248d16232a37a64f3f3dd15d8b60b68c1248
  - name: ghcr.io/comtrya/comtrya-frontend
    digest: sha256:8e331fccac77e2a1dde6f1b77fd56124c1b38dacaa3d463e1e17d4705047a0ee

patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: comtrya
      $patch: delete
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: comtrya-server-secrets
      $patch: delete
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: comtrya-server-config
      data:
        COMTRYA_CONFIG_REPO_URL: https://codeberg.org/rawkode-academy/comtrya
        COMTRYA_CONFIG_REPO_REF: main
        COMTRYA_CONFIG_REPO_PATH: ""
        COMTRYA_CONFIG_REPO_USERNAME: null
  - patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: comtrya-data
      spec:
        storageClassName: openebs-single-replica
        resources:
          requests:
            storage: 20Gi
