apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: your-app-secrets
  namespace: your-app-namespace
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: your-app-namespace
      secretsScope:
        projectSlug: replace-with-project-slug
        envSlug: replace-with-env-slug
        secretsPath: replace-with-secrets-path
  managedKubeSecretReferences:
    - secretName: app-secrets
      secretNamespace: your-app-namespace
      creationPolicy: Owner
      template:
        includeAllSecrets: true
        secretType: Opaque
