apiVersion: v1
kind: Namespace
metadata:
  name: your-app-namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: universal-auth-credentials
  namespace: your-app-namespace
type: Opaque
stringData:
  clientId: replace-with-client-id
  clientSecret: replace-with-client-secret
