environment: production

state:
  bucket: rawkode.cloud
  region: fr-par

cluster:
  talos_version: v1.12.3
  kubernetes_version: v1.35.0
  talos_schematic: 8a286c8c4c0697d0be932714af929c56dc55dc4d3deb9cc00aa3663c46c7738a

scaleway:
  vpc_name: rawkode-cloud
  private_network_name: rawkode-cloud
  zone: fr-par-1

nodePools:
  - name: main
    type: controlplane
    offer: EM-A610R-NVMe
    billing_cycle: hourly
    disks:
      os: /dev/nvme0n1
      data: /dev/nvme1n1

teleport:
  domain: rawkode.cloud

infisical:
  site_url: https://app.infisical.com
  project_id: 6575a392d7a5ef0555ade86b
  environment: production
  secret_path: /projects/rawkode-cloud
