apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - cert-manager
  - external-secrets
  - secrets-store-csi-driver
  - infisical-csi-provider
  - netbird-operator
  - kagent
  - openebs
  - zot
  - gateway
  - teleport
  - rocko
